# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List
import bluetooth

ADDR_PUBLIC: int
"""Public BLE device address type (0)."""
ADDR_RANDOM: int
"""Random BLE device address type (1)."""

def advertise(interval_us: int, adv_data: bytes | None = None, resp_data: bytes | None = None, connectable: bool = True, limited_disc: bool = False, br_edr: bool = False, name: str | None = None, services: list | None = None, appearance: int = 0, manufacturer: tuple | None = None, timeout_ms: int | None = None) -> DeviceConnection:
    """
    Async coroutine that begins advertising and waits for an incoming
    central connection. Returns a DeviceConnection representing the
    connected central, or raises asyncio.TimeoutError on
    timeout.

    interval_us

    Advertising interval, in microseconds.

    adv_data

    Raw advertising payload. If unset, adv_data is built from the
    remaining keyword arguments.

    resp_data

    Raw scan response payload. Auto-populated to overflow from
    adv_data if needed.

    connectable

    If True, this is a connectable advertisement.

    limited_disc

    Use the limited-discoverable flag instead of general.

    br_edr

    Set the BR/EDR-supported flag.

    name

    Optional complete local name to embed.

    services

    Iterable of bluetooth.UUID to advertise.

    appearance

    16-bit appearance value (see Bluetooth assigned numbers).

    manufacturer

    Tuple of (company_id, data_bytes) to advertise as
    manufacturer specific data.

    timeout_ms

    Stop advertising after this many milliseconds without a
    connection. None means advertise until connected.
    """
    ...
def config(*args, **kwargs) -> Any:
    """
    Forwards to bluetooth.BLE.config(), ensuring the BLE radio is
    active first.

    args

    Optional single parameter name to query.

    kwargs

    Keyword arguments to set configuration values.
    """
    ...
def register_services(*services: Service) -> None:
    """
    Register one or more Service objects (and their characteristics
    and descriptors) with the GATT server. Must be called once before
    starting advertise. Subsequent calls replace the previous
    registration.

    services

    One or more Service instances.
    """
    ...
def scan(duration_ms: int, interval_us: int | None = None, window_us: int | None = None, active: bool = False) -> scan:
    """
    Returns a scan async context-manager / async-iterator that yields
    ScanResult instances for each unique device discovered (or for
    each new piece of advertising data from a known device).

    duration_ms

    How long to scan, in milliseconds. Pass 0 to scan
    indefinitely until the context manager exits.

    interval_us

    Scan interval in microseconds. Defaults to 1,280,000.

    window_us

    Scan window in microseconds (must be less than or equal to
    interval_us). Defaults to 11,250.

    active

    If True, perform an active scan (request scan response
    data). Defaults to False.
    """
    ...
def stop() -> None:
    """
    Deactivate the underlying BLE radio and run any registered
    sub-module shutdown handlers. After calling this, scanners,
    advertisers, connections and L2CAP channels are all torn down.
    """
    ...

class DeviceDisconnectedError(Exception):
    """
    Raised inside an async operation (e.g. read, write, notified) when
    the underlying connection drops while waiting.
    """
    ...
class GattError(Exception):
    """
    Raised when a remote GATT operation (read / write / indicate)
    completes with a non-zero status. The status code is available on
    the _status attribute.
    """
    ...
class L2CAPConnectionError(Exception):
    """
    Raised by DeviceConnection.l2cap_connect when establishing the
    channel fails. The Bluetooth status code is the first argument.
    """
    ...
class L2CAPDisconnectedError(Exception):
    """
    Raised when an L2CAP channel send/recv/flush operation is
    attempted on (or interrupted by) a disconnected channel.
    """
    ...

class BufferedCharacteristic:
    """
    A Characteristic whose backing GATT buffer can be configured.
    Useful for receiving values larger than the default attribute
    size, or for queuing back-to-back writes.

    max_len

    Buffer size, in bytes.

    append

    If True, sequential writes append into the buffer instead
    of overwriting.

    Other arguments forward to Characteristic.
    """
    def __init__(self, service: Service, uuid: bluetooth.UUID, max_len: int = 20, append: bool = False, **kwargs) -> None: ...

class Characteristic:
    """
    Override hook invoked synchronously when a remote read is
    received. Return 0 to allow the read or a non-zero ATT
    error code to reject it. Default implementation returns 0.
    """
    def __init__(self, service: Service, uuid: bluetooth.UUID, read: bool = False, write: bool = False, write_no_response: bool = False, notify: bool = False, indicate: bool = False, initial: bytes | None = None, capture: bool = False) -> None: ...
    descriptors: Any
    """
    Override hook invoked synchronously when a remote read is
    received. Return 0 to allow the read or a non-zero ATT
    error code to reject it. Default implementation returns 0.
    """
    flags: Any
    """
    Override hook invoked synchronously when a remote read is
    received. Return 0 to allow the read or a non-zero ATT
    error code to reject it. Default implementation returns 0.
    """
    uuid: Any
    """
    Override hook invoked synchronously when a remote read is
    received. Return 0 to allow the read or a non-zero ATT
    error code to reject it. Default implementation returns 0.
    """
    def indicate(self, connection: DeviceConnection, data: bytes | None = None, timeout_ms: int = 1000) -> Awaitable[None]:
        """
        Async. Send a GATT Indicate to connection and wait for the
        client confirmation. Raises GattError on a non-zero status.

        connection

        The target client connection.

        data

        Payload to indicate, or None to send the local value.

        timeout_ms

        Maximum time to wait for confirmation.
        """
        ...
    def notify(self, connection: DeviceConnection, data: bytes | None = None) -> None:
        """
        Send a GATT Notify to connection.

        connection

        The target client connection.

        data

        Payload to send. If None, the current local value is
        sent.
        """
        ...
    def on_read(self, connection: DeviceConnection) -> int:
        """
        Override hook invoked synchronously when a remote read is
        received. Return 0 to allow the read or a non-zero ATT
        error code to reject it. Default implementation returns 0.
        """
        ...
    def read(self) -> bytes:
        """Read the current value from the local GATT database."""
        ...
    def write(self, data: bytes, send_update: bool = False) -> None:
        """
        Update the value in the local GATT database.

        data

        New value bytes.

        send_update

        If True, also notify/indicate every subscribed
        connection.
        """
        ...
    def written(self, timeout_ms: int | None = None) -> Awaitable[DeviceConnection | tuple[DeviceConnection, bytes]]:
        """
        Async. Wait for a remote write. Returns the writing
        DeviceConnection, or (connection, data) if the
        characteristic was created with capture=True.

        timeout_ms

        Maximum time to wait. None waits forever.
        """
        ...

class ClientCharacteristic:
    """
    Return an async iterator of ClientDescriptor objects. Use
    with async for and run the loop to completion.
    """
    def __init__(self) -> None: ...
    properties: Any
    """
    Return an async iterator of ClientDescriptor objects. Use
    with async for and run the loop to completion.
    """
    service: Any
    """
    Return an async iterator of ClientDescriptor objects. Use
    with async for and run the loop to completion.
    """
    uuid: Any
    """
    Return an async iterator of ClientDescriptor objects. Use
    with async for and run the loop to completion.
    """
    def descriptor(self, uuid: bluetooth.UUID, timeout_ms: int = 2000) -> Awaitable[ClientDescriptor | None]:
        """
        Async. Discover a single descriptor by UUID, or None if
        not found.
        """
        ...
    def descriptors(self, timeout_ms: int = 2000) -> ClientDiscover:
        """
        Return an async iterator of ClientDescriptor objects. Use
        with async for and run the loop to completion.
        """
        ...
    def indicated(self, timeout_ms: int | None = None) -> Awaitable[bytes]:
        """
        Async. Wait for the next indication on this characteristic and
        return its payload.

        timeout_ms

        Maximum time to wait.
        """
        ...
    def notified(self, timeout_ms: int | None = None) -> Awaitable[bytes]:
        """
        Async. Wait for the next notification on this characteristic
        and return its payload. Returns immediately if a notification
        is already queued.

        timeout_ms

        Maximum time to wait. None waits forever.
        """
        ...
    def read(self, timeout_ms: int = 1000) -> Awaitable[bytes]:
        """
        Async. Issue a GATT Read and return the value. Raises
        GattError on a non-zero status.

        timeout_ms

        Read timeout.
        """
        ...
    def subscribe(self, notify: bool = True, indicate: bool = False) -> Awaitable[None]:
        """
        Async. Write the Client Characteristic Configuration
        Descriptor (CCCD) to subscribe (or unsubscribe) for
        notifications and/or indications.

        notify

        Enable notifications.

        indicate

        Enable indications.
        """
        ...
    def write(self, data: bytes, response: bool | None = None, timeout_ms: int = 1000) -> Awaitable[None]:
        """
        Async. Issue a GATT Write.

        data

        Value to write.

        response

        True to require a write-response (and raise
        GattError on failure). False for write-without-
        response. None (default) auto-selects based on what
        the peer advertises.

        timeout_ms

        Write timeout (only relevant if response is True).
        """
        ...

class ClientDescriptor:
    """The descriptor UUID."""
    def __init__(self) -> None: ...
    characteristic: Any
    """The descriptor UUID."""
    uuid: Any
    """The descriptor UUID."""

class ClientService:
    """
    Return an async iterator of ClientCharacteristic objects.
    Use with async for and run the loop to completion.

    uuid

    Optional UUID filter.

    timeout_ms

    Per-discovery timeout.
    """
    def __init__(self) -> None: ...
    connection: Any
    """
    Return an async iterator of ClientCharacteristic objects.
    Use with async for and run the loop to completion.

    uuid

    Optional UUID filter.

    timeout_ms

    Per-discovery timeout.
    """
    uuid: Any
    """
    Return an async iterator of ClientCharacteristic objects.
    Use with async for and run the loop to completion.

    uuid

    Optional UUID filter.

    timeout_ms

    Per-discovery timeout.
    """
    def characteristic(self, uuid: bluetooth.UUID, timeout_ms: int = 2000) -> Awaitable[ClientCharacteristic | None]:
        """
        Async. Discover a single characteristic by UUID, or None
        if not found.
        """
        ...
    def characteristics(self, uuid: bluetooth.UUID | None = None, timeout_ms: int = 2000) -> ClientDiscover:
        """
        Return an async iterator of ClientCharacteristic objects.
        Use with async for and run the loop to completion.

        uuid

        Optional UUID filter.

        timeout_ms

        Per-discovery timeout.
        """
        ...

class Descriptor:
    """
    A local GATT descriptor. Constructing one automatically appends it
    to characteristic. Inherits read,
    write and written from Characteristic.

    characteristic

    The owning Characteristic.

    uuid

    The descriptor UUID.

    read, write

    Booleans selecting the supported GATT operations.

    initial

    Optional initial value (bytes).
    """
    def __init__(self, characteristic: Characteristic, uuid: bluetooth.UUID, read: bool = False, write: bool = False, initial: bytes | None = None) -> None: ...

class Device:
    """
    Async. Initiate a GAP connection to this device and return the
    resulting DeviceConnection. Cancels any in-progress scan.

    timeout_ms

    How long to wait for the connection to complete.

    scan_duration_ms

    Initial scan duration before connecting (controller
    specific).

    min_conn_interval_us / max_conn_interval_us

    Optional connection interval bounds, in microseconds.
    """
    def __init__(self, addr_type: int, addr: bytes | str) -> None: ...
    addr: Any
    """
    Async. Initiate a GAP connection to this device and return the
    resulting DeviceConnection. Cancels any in-progress scan.

    timeout_ms

    How long to wait for the connection to complete.

    scan_duration_ms

    Initial scan duration before connecting (controller
    specific).

    min_conn_interval_us / max_conn_interval_us

    Optional connection interval bounds, in microseconds.
    """
    addr_type: Any
    """
    Async. Initiate a GAP connection to this device and return the
    resulting DeviceConnection. Cancels any in-progress scan.

    timeout_ms

    How long to wait for the connection to complete.

    scan_duration_ms

    Initial scan duration before connecting (controller
    specific).

    min_conn_interval_us / max_conn_interval_us

    Optional connection interval bounds, in microseconds.
    """
    def addr_hex(self) -> str:
        """Return the address formatted as a colon-separated hex string."""
        ...
    def connect(self, timeout_ms: int = 10000, scan_duration_ms: int | None = None, min_conn_interval_us: int | None = None, max_conn_interval_us: int | None = None) -> Awaitable[DeviceConnection]:
        """
        Async. Initiate a GAP connection to this device and return the
        resulting DeviceConnection. Cancels any in-progress scan.

        timeout_ms

        How long to wait for the connection to complete.

        scan_duration_ms

        Initial scan duration before connecting (controller
        specific).

        min_conn_interval_us / max_conn_interval_us

        Optional connection interval bounds, in microseconds.
        """
        ...

class DeviceConnection:
    """
    Async. Open an L2CAP channel to the remote on the given PSM.

    psm

    Protocol/Service Multiplexer to connect to.

    mtu

    Maximum receive size, in bytes.

    timeout_ms

    Connection timeout.
    """
    def __init__(self) -> None: ...
    authenticated: Any
    """
    Async. Open an L2CAP channel to the remote on the given PSM.

    psm

    Protocol/Service Multiplexer to connect to.

    mtu

    Maximum receive size, in bytes.

    timeout_ms

    Connection timeout.
    """
    bonded: Any
    """
    Async. Open an L2CAP channel to the remote on the given PSM.

    psm

    Protocol/Service Multiplexer to connect to.

    mtu

    Maximum receive size, in bytes.

    timeout_ms

    Connection timeout.
    """
    device: Any
    """
    Async. Open an L2CAP channel to the remote on the given PSM.

    psm

    Protocol/Service Multiplexer to connect to.

    mtu

    Maximum receive size, in bytes.

    timeout_ms

    Connection timeout.
    """
    encrypted: Any
    """
    Async. Open an L2CAP channel to the remote on the given PSM.

    psm

    Protocol/Service Multiplexer to connect to.

    mtu

    Maximum receive size, in bytes.

    timeout_ms

    Connection timeout.
    """
    key_size: Any
    """
    Async. Open an L2CAP channel to the remote on the given PSM.

    psm

    Protocol/Service Multiplexer to connect to.

    mtu

    Maximum receive size, in bytes.

    timeout_ms

    Connection timeout.
    """
    mtu: Any
    """
    Async. Open an L2CAP channel to the remote on the given PSM.

    psm

    Protocol/Service Multiplexer to connect to.

    mtu

    Maximum receive size, in bytes.

    timeout_ms

    Connection timeout.
    """
    def disconnect(self, timeout_ms: int = 2000) -> Awaitable[None]:
        """
        Async. Disconnect and wait for the disconnection IRQ.

        timeout_ms

        Maximum time to wait for the disconnection.
        """
        ...
    def disconnected(self, timeout_ms: int | None = None, disconnect: bool = False) -> Awaitable[None]:
        """
        Async. Wait for the connection to be terminated by either
        side. If disconnect is True it actively disconnects
        first.

        timeout_ms

        Maximum time to wait. None means wait forever.

        disconnect

        If True, initiate disconnection.
        """
        ...
    def exchange_mtu(self, mtu: int | None = None, timeout_ms: int = 1000) -> Awaitable[int]:
        """
        Async. Initiate an ATT MTU exchange and return the negotiated
        MTU.

        mtu

        Optional preferred MTU to set on the underlying BLE
        interface before the exchange.

        timeout_ms

        Timeout for the exchange.
        """
        ...
    def is_connected(self) -> bool:
        """Return whether the connection is still active."""
        ...
    def l2cap_accept(self, psm: int, mtu: int, timeout_ms: int | None = None) -> Awaitable[L2CAPChannel]:
        """
        Async. Listen on the given PSM and return an L2CAPChannel
        once the remote opens it.

        psm

        Protocol/Service Multiplexer to listen on.

        mtu

        Maximum receive size, in bytes.

        timeout_ms

        Maximum time to wait for the remote to connect.
        """
        ...
    def l2cap_connect(self, psm: int, mtu: int, timeout_ms: int = 1000) -> Awaitable[L2CAPChannel]:
        """
        Async. Open an L2CAP channel to the remote on the given PSM.

        psm

        Protocol/Service Multiplexer to connect to.

        mtu

        Maximum receive size, in bytes.

        timeout_ms

        Connection timeout.
        """
        ...
    def pair(self, bond: bool = True, le_secure: bool = True, mitm: bool = False, io: int = 3, timeout_ms: int = 20000) -> Awaitable[None]:
        """
        Async. Initiate pairing on this connection. Updates the
        encrypted / authenticated / bonded / key_size
        attributes when complete.

        bond

        Persist pairing keys.

        le_secure

        Use LE Secure Connections.

        mitm

        Require man-in-the-middle protection.

        io

        IO capability constant (e.g. 3 for no input/output).

        timeout_ms

        Pairing timeout.
        """
        ...
    def service(self, uuid: bluetooth.UUID, timeout_ms: int = 2000) -> Awaitable[ClientService | None]:
        """
        Async. Discover a single remote service matching uuid, or
        None if not found.
        """
        ...
    def services(self, uuid: bluetooth.UUID | None = None, timeout_ms: int = 2000) -> ClientDiscover:
        """
        Return an async iterator of remote ClientService objects.
        Use with async for and run the loop to completion.

        uuid

        Optional UUID filter. None returns every service.

        timeout_ms

        Per-discovery timeout.
        """
        ...
    def timeout(self, timeout_ms: int | None) -> DeviceTimeout:
        """
        Return a context manager that cancels its body if either the
        timeout elapses (raising asyncio.TimeoutError) or the
        device disconnects (raising DeviceDisconnectedError).

        timeout_ms

        Timeout in milliseconds, or None for no timeout.
        """
        ...

class L2CAPChannel:
    """
    Async. Wait until the channel is disconnected by either side.

    timeout_ms

    Maximum time to wait.
    """
    def __init__(self) -> None: ...
    our_mtu: Any
    """
    Async. Wait until the channel is disconnected by either side.

    timeout_ms

    Maximum time to wait.
    """
    peer_mtu: Any
    """
    Async. Wait until the channel is disconnected by either side.

    timeout_ms

    Maximum time to wait.
    """
    def available(self) -> bool:
        """
        Synchronously return True if buffered receive data is
        ready (i.e. recvinto will not block).
        """
        ...
    def disconnect(self, timeout_ms: int = 1000) -> Awaitable[None]:
        """
        Async. Disconnect the channel and wait for the disconnection
        IRQ.

        timeout_ms

        Maximum time to wait.
        """
        ...
    def disconnected(self, timeout_ms: int = 1000) -> Awaitable[None]:
        """
        Async. Wait until the channel is disconnected by either side.

        timeout_ms

        Maximum time to wait.
        """
        ...
    def flush(self, timeout_ms: int | None = None) -> Awaitable[None]:
        """
        Async. Wait until any stalled send has been drained by the
        controller.

        timeout_ms

        Maximum time to wait.
        """
        ...
    def recvinto(self, buf: bytearray, timeout_ms: int | None = None) -> Awaitable[int]:
        """
        Async. Receive into buf, returning the number of bytes
        read. Awaits new data if the channel is empty.

        buf

        Pre-allocated buffer to fill.

        timeout_ms

        Maximum time to wait. None waits forever.
        """
        ...
    def send(self, buf: bytes, timeout_ms: int | None = None, chunk_size: int | None = None) -> Awaitable[None]:
        """
        Async. Send buf on the channel, fragmenting larger payloads
        into MTU-sized chunks. Awaits flow-control credits as needed.

        buf

        Bytes-like object to send.

        timeout_ms

        Maximum time to wait per chunk.

        chunk_size

        Optional override for the per-call chunk size. Capped to
        min(our_mtu * 2, peer_mtu).
        """
        ...

class ScanResult:
    """
    Generator yielding (company_id, data) tuples from
    manufacturer-specific advertising fields.

    filter

    If given, only yield entries whose company ID matches.
    """
    def __init__(self) -> None: ...
    adv_data: Any
    """
    Generator yielding (company_id, data) tuples from
    manufacturer-specific advertising fields.

    filter

    If given, only yield entries whose company ID matches.
    """
    connectable: Any
    """
    Generator yielding (company_id, data) tuples from
    manufacturer-specific advertising fields.

    filter

    If given, only yield entries whose company ID matches.
    """
    device: Any
    """
    Generator yielding (company_id, data) tuples from
    manufacturer-specific advertising fields.

    filter

    If given, only yield entries whose company ID matches.
    """
    resp_data: Any
    """
    Generator yielding (company_id, data) tuples from
    manufacturer-specific advertising fields.

    filter

    If given, only yield entries whose company ID matches.
    """
    rssi: Any
    """
    Generator yielding (company_id, data) tuples from
    manufacturer-specific advertising fields.

    filter

    If given, only yield entries whose company ID matches.
    """
    def manufacturer(self, filter: int | None = None) -> Iterator[tuple[int, bytes]]:
        """
        Generator yielding (company_id, data) tuples from
        manufacturer-specific advertising fields.

        filter

        If given, only yield entries whose company ID matches.
        """
        ...
    def name(self) -> Optional[str]:
        """
        Decode the complete (or shortened) advertised local name from
        the payload, or None if not present.
        """
        ...
    def services(self) -> Iterator[bluetooth.UUID]:
        """
        Generator yielding each bluetooth.UUID advertised in
        the 16/32/128-bit service-list fields.
        """
        ...

class Service:
    """List of Characteristic objects bound to this service."""
    def __init__(self, uuid: bluetooth.UUID) -> None: ...
    characteristics: Any
    """List of Characteristic objects bound to this service."""
    uuid: Any
    """List of Characteristic objects bound to this service."""

