# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List

def namedtuple(name: str, fields: str | Sequence[str]) -> type:
    """
    This is factory function to create a new namedtuple type with a specific
    name and set of fields. A namedtuple is a subclass of tuple which allows
    to access its fields not just by numeric index, but also with an attribute
    access syntax using symbolic field names. Fields is a sequence of strings
    specifying field names. For compatibility with CPython it can also be a
    a string with space-separated field named (but this is less efficient).
    Example of use:

    from collections import namedtuple

    MyTuple = namedtuple("MyTuple", ("id", "name"))
    t1 = MyTuple(1, "foo")
    t2 = MyTuple(2, "bar")
    print(t1.name)
    assert t2.name == t2[1]
    """
    ...

class OrderedDict:
    """
    Remove and return a (key, value) pair from the dictionary.
    Pairs are returned in LIFO order.

    Difference to CPython

    OrderedDict.popitem() does not support the last=False argument and
    will always remove and return the last item if present.

    A workaround for this is to use pop(<first_key>) to remove the first item:

    first_key = next(iter(d))
    d.pop(first_key)
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def popitem(self) -> Tuple:
        """
        Remove and return a (key, value) pair from the dictionary.
        Pairs are returned in LIFO order.

        Difference to CPython

        OrderedDict.popitem() does not support the last=False argument and
        will always remove and return the last item if present.

        A workaround for this is to use pop(<first_key>) to remove the first item:

        first_key = next(iter(d))
        d.pop(first_key)
        """
        ...

class deque:
    """
    Extend the deque by appending all the items from iterable to
    the right of the deque.
    Raises IndexError if overflow checking is enabled and there is
    no more room in the deque.
    """
    def __init__(self, iterable: Iterable, maxlen: int, flags: int = 0) -> None: ...
    def append(self, x: Any) -> None:
        """
        Add x to the right side of the deque.
        Raises IndexError if overflow checking is enabled and there is
        no more room in the queue.
        """
        ...
    def appendleft(self, x: Any) -> None:
        """
        Add x to the left side of the deque.
        Raises IndexError if overflow checking is enabled and there is
        no more room in the queue.
        """
        ...
    def extend(self, iterable: Iterable) -> None:
        """
        Extend the deque by appending all the items from iterable to
        the right of the deque.
        Raises IndexError if overflow checking is enabled and there is
        no more room in the deque.
        """
        ...
    def pop(self) -> Any:
        """
        Remove and return an item from the right side of the deque.
        Raises IndexError if no items are present.
        """
        ...
    def popleft(self) -> Any:
        """
        Remove and return an item from the left side of the deque.
        Raises IndexError if no items are present.
        """
        ...

