# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List

AUTO: int
"""Supported values for the format parameter."""
GZIP: int
"""Supported values for the format parameter."""
RAW: int
"""Supported values for the format parameter."""
ZLIB: int
"""Supported values for the format parameter."""

class DeflateIO:
    """
    This class can be used to wrap a stream which is any
    stream-like object such as a file, socket, or stream
    (including io.BytesIO). It is itself a stream and implements the
    standard read/readinto/write/close methods.

    The stream must be a blocking stream. Non-blocking streams are currently
    not supported.

    The format can be set to any of the constants defined below, and defaults
    to AUTO which for decompressing will auto-detect gzip or zlib streams,
    and for compressing it will generate a raw stream.

    The wbits parameter sets the base-2 logarithm of the DEFLATE dictionary
    window size. So for example, setting wbits to 10 sets the window size
    to 1024 bytes. Valid values are 5 to 15 inclusive (corresponding to
    window sizes of 32 to 32k bytes).

    If wbits is set to 0 (the default), then for compression a window size
    of 256 bytes will be used (as if wbits was set to 8). For decompression, it
    depends on the format:

    RAW will use 256 bytes (corresponding to wbits set to 8).

    ZLIB (or AUTO with zlib detected) will use the value from the zlib
    header.

    GZIP (or AUTO with gzip detected) will use 32 kilobytes
    (corresponding to wbits set to 15).

    See the window size notes below for more information
    about the window size, zlib, and gzip streams.

    If close is set to True then the underlying stream will be closed
    automatically when the deflate.DeflateIO stream is closed. This is
    useful if you want to return a deflate.DeflateIO stream that wraps
    another stream and not have the caller need to know about managing the
    underlying stream.

    If compression is enabled, a given deflate.DeflateIO instance
    supports both reading and writing. For example, a bidirectional stream like
    a socket can be wrapped, which allows for compression/decompression in both
    directions.
    """
    def __init__(self, stream: Any, format: int = AUTO, wbits: int = 0, close: bool = False, /) -> None: ...

