# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List
import machine

class DHT11:
    """
    Return the temperature from the most recent measure() call,
    as an integer in degrees Celsius.
    """
    def __init__(self, pin: machine.Pin) -> None: ...
    def humidity(self) -> int:
        """
        Return the relative humidity from the most recent measure()
        call, as an integer percentage (0–100).
        """
        ...
    def temperature(self) -> int:
        """
        Return the temperature from the most recent measure() call,
        as an integer in degrees Celsius.
        """
        ...

class DHT22:
    """
    Return the temperature from the most recent measure() call,
    as a float in degrees Celsius. Negative values are supported.
    """
    def __init__(self, pin: machine.Pin) -> None: ...
    def humidity(self) -> float:
        """
        Return the relative humidity from the most recent measure()
        call, as a float percentage (0.0–100.0).
        """
        ...
    def temperature(self) -> float:
        """
        Return the temperature from the most recent measure() call,
        as a float in degrees Celsius. Negative values are supported.
        """
        ...

class DHTBase:
    """
    Trigger a measurement on the sensor and read the 5-byte response
    into the internal buffer. Raises Exception with the message
    "checksum error" if the data checksum is invalid.

    Call this method before reading temperature() or
    humidity(). The DHT sensors require at least 1 second
    (DHT11) or 2 seconds (DHT22) between consecutive measurements.
    """
    def __init__(self, pin: machine.Pin) -> None: ...
    def measure(self) -> None:
        """
        Trigger a measurement on the sensor and read the 5-byte response
        into the internal buffer. Raises Exception with the message
        "checksum error" if the data checksum is invalid.

        Call this method before reading temperature() or
        humidity(). The DHT sensors require at least 1 second
        (DHT11) or 2 seconds (DHT22) between consecutive measurements.
        """
        ...

