# Auto-generated by tools/genpyi.py -- do not edit
"""
This module allows compression and decompression of binary data with the
DEFLATE algorithm used by the gzip
file format.  It provides one-shot compress()/decompress()
helpers and a streaming GzipFile wrapper around an underlying
file or stream object.

Availability:

- This module is not included on the OpenMV Cam by default, as it
  duplicates functionality already provided by the deflate
  module.
- A copy can be installed (or frozen into custom firmware)
  from micropython-lib (source).
  See packages for more information. This documentation describes that module.
- Compression is only available if compression is available in the built-in
  deflate module – that is, not on the STM32-based OpenMV
  Cams (see its availability note above).
"""

from typing import Any

def compress(data: bytes, /) -> bytes:
    """Compresses data into a bytes object."""
    ...
def decompress(data: bytes, /) -> bytes:
    """Decompresses data into a bytes object."""
    ...
def open(filename: str, mode: str, /) -> GzipFile:
    """Wrapper around built-in open() returning a GzipFile instance."""
    ...

class GzipFile:
    """
    This class can be used to wrap a fileobj which is any
    stream-like object such as a file, socket, or stream
    (including io.BytesIO). It is itself a stream and implements the
    standard read/readinto/write/close methods.

    When the mode argument is "rb", reads from the GzipFile instance will
    decompress the data in the underlying stream and return decompressed data.

    If compression support is enabled then the mode argument can be set to
    "wb", and writes to the GzipFile instance will be compressed and written
    to the underlying stream.

    By default the GzipFile class will read and write data using the gzip file
    format, including a header and footer with checksum and a window size of 512
    bytes.

    The file, compresslevel, and mtime arguments are not
    supported. fileobj and mode must always be specified as keyword
    arguments.
    """
    def __init__(self, *, fileobj, mode: str) -> None: ...

