# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List

def heapify(x: list) -> None:
    """Convert the list x into a heap.  This is an in-place operation."""
    ...
def heappop(heap: list) -> Any:
    """
    Pop the first item from the heap, and return it.  Raise IndexError if
    heap is empty.

    The returned item will be the smallest item in the heap.
    """
    ...
def heappush(heap: list, item: Any) -> None:
    """Push the item onto the heap."""
    ...

