# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List
import machine

class HS3003:
    """
    Trigger a measurement and return the temperature in degrees Celsius,
    computed as (raw >> 2) / 16383 * 165 - 40.
    """
    def __init__(self, bus: machine.I2C, address: int = 0x44) -> None: ...
    def humidity(self) -> float:
        """
        Trigger a measurement and return the relative humidity in percent
        (%RH), computed as (raw & 0x3FFF) / 16383 * 100.
        """
        ...
    def temperature(self) -> float:
        """
        Trigger a measurement and return the temperature in degrees Celsius,
        computed as (raw >> 2) / 16383 * 165 - 40.
        """
        ...

