# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List

def open(name: str, mode: str = 'r', **kwargs) -> Any:
    """
    Open a file. Builtin open() function is aliased to this function.
    All ports (which provide access to file system) are required to support
    mode parameter, but support for other arguments vary by port.
    """
    ...

class BytesIO:
    """Get the current contents of the underlying buffer which holds data."""
    def __init__(self, string: bytes = b'') -> None: ...
    def getvalue(self) -> Any:
        """Get the current contents of the underlying buffer which holds data."""
        ...

class StringIO:
    """Get the current contents of the underlying buffer which holds data."""
    def __init__(self, string: str = '') -> None: ...

