# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List

SEC_CHAP: int
"""The type of connection security."""
SEC_NONE: int
"""The type of connection security."""
SEC_PAP: int
"""The type of connection security."""
802_1X: int
"""Setup in firmware update mode."""
MODE_AP: int
"""Setup in firmware update mode."""
MODE_BSP: int
"""Setup in firmware update mode."""
MODE_FIRMWARE: int
"""Setup in firmware update mode."""
MODE_P2P: int
"""Setup in firmware update mode."""
MODE_STA: int
"""Setup in firmware update mode."""
OPEN: int
"""Setup in firmware update mode."""
WPA_PSK: int
"""Setup in firmware update mode."""
PM_NONE: int
"""
Allowed values for the WLAN.config(pm=...) network interface parameter:

PM_PERFORMANCE: enable WiFi power management to balance power
savings and WiFi performance

PM_POWERSAVE: enable WiFi power management with additional power
savings and reduced WiFi performance

PM_NONE: disable wifi power management
"""
PM_PERFORMANCE: int
"""
Allowed values for the WLAN.config(pm=...) network interface parameter:

PM_PERFORMANCE: enable WiFi power management to balance power
savings and WiFi performance

PM_POWERSAVE: enable WiFi power management with additional power
savings and reduced WiFi performance

PM_NONE: disable wifi power management
"""
PM_POWERSAVE: int
"""
Allowed values for the WLAN.config(pm=...) network interface parameter:

PM_PERFORMANCE: enable WiFi power management to balance power
savings and WiFi performance

PM_POWERSAVE: enable WiFi power management with additional power
savings and reduced WiFi performance

PM_NONE: disable wifi power management
"""

def country(code: str | None = None) -> Optional[str]:
    """
    Get or set the two-letter ISO 3166-1 Alpha-2 country code to be used for
    radio compliance.

    If the code parameter is provided, the country will be set to this value.
    If the function is called without parameters, it returns the current
    country.

    The default code "XX" represents the “worldwide” region.
    """
    ...
def hostname(name: str | None = None) -> Optional[str]:
    """
    Get or set the hostname that will identify this device on the network. It will
    be used by all interfaces.

    This hostname is used for:

    Sending to the DHCP server in the client request. (If using DHCP)

    Broadcasting via mDNS. (If enabled)

    If the name parameter is provided, the hostname will be set to this value.
    If the function is called without parameters, it returns the current
    hostname.

    A change in hostname is typically only applied during connection. For DHCP
    this is because the hostname is part of the DHCP client request, and the
    implementation of mDNS in most ports only initialises the hostname once
    during connection. For this reason, you must set the hostname before
    activating/connecting your network interfaces.

    The length of the hostname is limited to 32 characters.
    MicroPython ports may choose to set a lower
    limit for memory reasons. If the given name does not fit, a ValueError
    is raised.

    The default hostname is typically the name of the board.
    """
    ...
def ipconfig(param: str) -> Any:
    """
    Get or set global IP-configuration parameters.
    Supported parameters are the following (availability of a particular
    parameter depends on the port and the specific network interface):

    dns Get/set DNS server. This method can support both, IPv4 and
    IPv6 addresses.

    prefer (4/6) Specify which address type to return, if a domain
    name has both A and AAAA records. Note, that this does not clear the
    local DNS cache, so that any previously obtained addresses might not
    change.
    """
    ...
def phy_mode(mode: int | None = None) -> Optional[int]:
    """
    Get or set the PHY mode.

    If the mode parameter is provided, the PHY mode will be set to this value.
    If the function is called without parameters, it returns the current PHY
    mode.

    The possible modes are defined as constants:

    MODE_11B – IEEE 802.11b,

    MODE_11G – IEEE 802.11g,

    MODE_11N – IEEE 802.11n.

    Availability: ESP8266.
    """
    ...

class AbstractNIC:
    """
    Get or set general network interface parameters. These methods allow to work
    with additional parameters beyond standard IP configuration (as dealt with by
    ipconfig()). These include network-specific and hardware-specific
    parameters. For setting parameters, the keyword argument
    syntax should be used, and multiple parameters can be set at once. For
    querying, a parameter name should be quoted as a string, and only one
    parameter can be queried at a time:

    # Set WiFi access point name (formally known as SSID) and WiFi channel
    ap.config(ssid='My AP', channel=11)
    # Query params one by one
    print(ap.config('ssid'))
    print(ap.config('channel'))
    """
    def __init__(self, id: int | None = None, *args: Any, **kwargs: Any) -> None: ...
    def active(self, is_active: bool | None = None, /) -> bool:
        """
        Activate (“up”) or deactivate (“down”) the network interface, if
        a boolean argument is passed. Otherwise, query current state if
        no argument is provided. Most other methods require an active
        interface (behaviour of calling them on inactive interface is
        undefined).
        """
        ...
    def config(self, **kwargs: Any) -> None:
        """
        Get or set general network interface parameters. These methods allow to work
        with additional parameters beyond standard IP configuration (as dealt with by
        ipconfig()). These include network-specific and hardware-specific
        parameters. For setting parameters, the keyword argument
        syntax should be used, and multiple parameters can be set at once. For
        querying, a parameter name should be quoted as a string, and only one
        parameter can be queried at a time:

        # Set WiFi access point name (formally known as SSID) and WiFi channel
        ap.config(ssid='My AP', channel=11)
        # Query params one by one
        print(ap.config('ssid'))
        print(ap.config('channel'))
        """
        ...
    def connect(self, service_id: str | None = None, key: str | None = None, *, bssid: bytes | None = None, **kwargs: Any) -> None:
        """
        Connect the interface to a network. This method is optional, and
        available only for interfaces which are not “always connected”.
        If no parameters are given, connect to the default (or the only)
        service. If a single parameter is given, it is the primary identifier
        of a service to connect to. It may be accompanied by a key
        (password) required to access said service. There can be further
        arbitrary keyword-only parameters, depending on the networking medium
        type and/or particular device. Parameters can be used to: a)
        specify alternative service identifier types; b) provide additional
        connection parameters. For various medium types, there are different
        sets of predefined/recommended parameters, among them:

        WiFi: bssid keyword to connect to a specific BSSID (MAC address)
        """
        ...
    def disconnect(self) -> None:
        """Disconnect from network."""
        ...
    def ifconfig(self, config: Tuple[str, str, str, str] | None = None) -> Optional[Tuple[str, str, str, str]]:
        """
        This function is deprecated, use ipconfig() instead.

        Get/set IP-level network interface parameters: IP address, subnet mask,
        gateway and DNS server. When called with no arguments, this method returns
        a 4-tuple with the above information. To set the above values, pass a
        4-tuple with the required information.  For example:

        nic.ifconfig(('192.168.0.4', '255.255.255.0', '192.168.0.1', '8.8.8.8'))
        """
        ...
    def ipconfig(self, **kwargs: Any) -> None:
        """
        Get or set interface-specific IP-configuration interface parameters.
        Supported parameters are the following (availability of a particular
        parameter depends on the port and the specific network interface):

        dhcp4 (True/False) obtain an IPv4 address, gateway and dns
        server via DHCP. This method does not block and wait for an address
        to be obtained. To check if an address was obtained, use the read-only
        property has_dhcp4.

        gw4 Get/set the IPv4 default-gateway.

        dhcp6 (True/False) obtain a DNS server via stateless DHCPv6.
        Obtaining IP Addresses via DHCPv6 is currently not implemented.

        autoconf6 (True/False) obtain a stateless IPv6 address via
        the network prefix shared in router advertisements. To check if a
        stateless address was obtained, use the read-only
        property has_autoconf6.

        addr4 (e.g. 192.168.0.4/24) obtain the current IPv4 address
        and network mask as (ip, subnet)-tuple, regardless of how this
        address was obtained. This method can be used to set a static IPv4
        address either as (ip, subnet)-tuple or in CIDR-notation.

        addr6 (e.g. fe80::1234:5678) obtain a list of current IPv6
        addresses as (ip, state, preferred_lifetime, valid_lifetime)-tuple.
        This include link-local, slaac and static addresses.
        preferred_lifetime and valid_lifetime represent the remaining
        valid and preferred lifetime of each IPv6 address, in seconds.
        state indicates the current state of the address:

        0x08 - 0x0f indicates the address is tentative, counting the
        number of probes sent.

        0x10 The address is deprecated (but still valid)

        0x30 The address is preferred (and valid)

        0x40 The address is duplicated and can not be used.

        This method can be used to set a static IPv6
        address, by setting this parameter to the address, like fe80::1234:5678.
        """
        ...
    def isconnected(self) -> bool:
        """Returns True if connected to network, otherwise returns False."""
        ...
    def scan(self, **kwargs: Any) -> List[Tuple]:
        """
        Scan for the available network services/connections. Returns a
        list of tuples with discovered service parameters. For various
        network media, there are different variants of predefined/
        recommended tuple formats, among them:

        WiFi: (ssid, bssid, channel, RSSI, security, hidden). There
        may be further fields, specific to a particular device.

        The function may accept additional keyword arguments to filter scan
        results (e.g. scan for a particular service, on a particular channel,
        for services of a particular set, etc.), and to affect scan
        duration and other parameters. Where possible, parameter names
        should match those in connect().
        """
        ...
    def status(self, param: str | None = None) -> Any:
        """
        Query dynamic status information of the interface.  When called with no
        argument the return value describes the network link status.  Otherwise
        param should be a string naming the particular status parameter to
        retrieve.

        The return types and values are dependent on the network
        medium/technology.  Some of the parameters that may be supported are:

        WiFi STA: use 'rssi' to retrieve the RSSI of the AP signal

        WiFi AP: use 'stations' to retrieve a list of all the STAs
        connected to the AP.  The list contains tuples of the form
        (MAC, RSSI).
        """
        ...

class LAN:
    """
    Sets or gets parameters of the LAN interface. The only parameter that can be
    retrieved is the MAC address, using:

    mac = LAN.config("mac")

    The parameters that can be set are:

    trace=n sets trace levels; suitable values are:

    2: trace TX

    4: trace RX

    8: full trace

    low_power=bool sets or clears low power mode, valid values being False
    or True.
    """
    def __init__(self, id: int, *, phy_type: int = ..., phy_addr: int = ..., ref_clk_mode: int = ...) -> None: ...
    def active(self, state: bool | None = None) -> bool:
        """
        With a parameter, it sets the interface active if state is true, otherwise it
        sets it inactive.
        Without a parameter, it returns the state.
        """
        ...
    def config(self, config_parameters: str | Any) -> Any:
        """
        Sets or gets parameters of the LAN interface. The only parameter that can be
        retrieved is the MAC address, using:

        mac = LAN.config("mac")

        The parameters that can be set are:

        trace=n sets trace levels; suitable values are:

        2: trace TX

        4: trace RX

        8: full trace

        low_power=bool sets or clears low power mode, valid values being False
        or True.
        """
        ...
    def ifconfig(self, config: Tuple[str, str, str, str] | None = None) -> Optional[Tuple[str, str, str, str]]:
        """
        Get/set IP address, subnet mask, gateway and DNS.

        When called with no arguments, this method returns a 4-tuple with the above information.

        To set the above values, pass a 4-tuple with the required information.  For example:

        nic.ifconfig(('192.168.0.4', '255.255.255.0', '192.168.0.1', '8.8.8.8'))
        """
        ...
    def isconnected(self) -> bool:
        """
        Returns True if the physical Ethernet link is connected and up.
        Returns False otherwise.
        """
        ...
    def status(self) -> int:
        """Returns the LAN status."""
        ...

class PPP:
    """The type of connection security."""
    def __init__(self, stream: Any) -> None: ...
    def config(self, config_parameters: str | Any) -> Any:
        """
        Sets or gets parameters of the PPP interface. The only parameter that can be
        retrieved and set is the underlying stream, using:

        stream = PPP.config("stream")
        PPP.config(stream=stream)
        """
        ...
    def connect(self, security: int = SEC_NONE, user: str | None = None, key: str | None = None) -> None:
        """
        Initiate a PPP connection with the given parameters:

        security is the type of security, either PPP.SEC_NONE, PPP.SEC_PAP,
        or PPP.SEC_CHAP.

        user is an optional user name to use with the security mode.

        key is an optional password to use with the security mode.

        When this method is called the underlying stream has its interrupt configured to call
        PPP.poll via stream.irq(ppp.poll, stream.IRQ_RXIDLE).  This makes sure the
        stream is polled, and data passed up the PPP stack, wheverver data becomes available
        on the stream.

        The connection proceeds asynchronously, in the background.
        """
        ...
    def disconnect(self) -> None:
        """Terminate the connection.  This must be called to cleanly close the PPP connection."""
        ...
    def ifconfig(self, config: Tuple[str, str, str, str] | None = None) -> Optional[Tuple[str, str, str, str]]:
        """See AbstractNIC.ifconfig."""
        ...
    def ipconfig(self, **kwargs: Any) -> None:
        """See AbstractNIC.ipconfig."""
        ...
    def isconnected(self) -> bool:
        """
        Returns True if the PPP link is connected and up.
        Returns False otherwise.
        """
        ...
    def poll(self, irq_arg: Any | None = None) -> None:
        """
        Poll the underlying stream for data, and pass it up the PPP stack.
        This is called automatically if the stream is a UART with a RXIDLE interrupt,
        so it’s not usually necessary to call it manually.

        The optional irq_arg argument is ignored, this argument exists only so this
        function is compatible with the machine.UART.irq() handler argument.
        """
        ...
    def status(self) -> int:
        """Returns the PPP status."""
        ...

class WINC:
    """Setup in firmware update mode."""
    def __init__(self, mode: int = MODE_STATION) -> None: ...
    def active(self, is_active: bool | None = None) -> bool:
        """
        Activate (“up”) or deactivate (“down”) network interface, if boolean
        argument is passed. Otherwise, query current state if no argument is
        provided. Most other methods require active interface.
        """
        ...
    def connect(self, ssid: str, key: str | None = None, security: int = WPA_PSK, channel: int = 1) -> None:
        """
        Connect to a wifi network with ssid ssid using key key with
        security security and channel channel.

        After connecting to the network use the usocket module to open TCP/UDP
        ports to send and receive data.

        This method takes a little while to return.
        """
        ...
    def connected_sta(self) -> List[str]:
        """This method returns a list containing the connected client’s IP adress."""
        ...
    def disconnect(self) -> None:
        """Disconnect from the wifi network."""
        ...
    def fw_dump(self, path: str) -> None:
        """
        Dumps the wifi shield firmware to a binary file at path. You must
        have put the module into firmware mode to use this.
        """
        ...
    def fw_update(self, path: str) -> None:
        """
        Programs the wifi shield with binary image found at path. You must
        have put the module into firmware mode to use this.
        """
        ...
    def fw_version(self) -> Tuple[int, int, int, int, int, int, int]:
        """
        Returns a tuple containing the wifi shield firmware version number.

        [0]: Firmware Major Version Number (int)

        [1]: Firmware Minor Version Number (int)

        [2]: Firmware Patch Version Number (int)

        [3]: Driver Major Version Number (int)

        [4]: Driver Minor Version Number (int)

        [5]: Driver Patch Version Number (int)

        [6]: Hardware Revision Number - Chip ID (int)
        """
        ...
    def ifconfig(self, config: Tuple[str, str, str, str] | None = None) -> Tuple[str, str, str, str]:
        """
        Returns a tuple containing:

        [0]: IP Address String (XXX.XXX.XXX.XXX)

        [1]: Subnet Address String (XXX.XXX.XXX.XXX)

        [2]: Gateway String (XXX.XXX.XXX.XXX)

        [3]: DNS Address String (XXX.XXX.XXX.XXX)

        While connected to the network.

        You may optionally pass a tuple/list of the ip_addr, subnet_addr,
        gateway_addr, and dns_addr strings in ipv4 (XXX.XXX.XXX.XXX) format
        to set a static IP address versus an address obtained through DHCP (which happens by default).

        Example usage:

        wlan = network.WINC()
        wlan.ifconfig(('192.168.1.100', '255.255.255.0', '192.168.1.1', '192.168.1.1'))
        wlan.connect(SSID, key=KEY, security=wlan.WPA_PSK)
        """
        ...
    def isconnected(self) -> bool:
        """
        Returns True if connected to an access point and an IP address has been
        obtained.
        """
        ...
    def netinfo(self) -> Tuple[int, int, str, str, str]:
        """
        Returns a tuple containing:

        [0]: RSSI - received signal strength indicator (int)

        [1]: Authorization Type (see constants)

        [2]: Set Service Identifier String (SSID)

        [3]: MAC Address String (XX:XX:XX:XX:XX:XX) (BSSID)

        [4]: IP Address String (XXX.XXX.XXX.XXX)

        While connected to the network.
        """
        ...
    def rssi(self) -> int:
        """
        Returns the received signal strength indicator (int) of the currently
        connected network.
        """
        ...
    def scan(self) -> List[Tuple[str, str, int, int, int, int]]:
        """
        Returns a list containing:

        [0]: Set Service Identifier String (SSID)

        [1]: MAC Address String (XX:XX:XX:XX:XX:XX) (BSSID)

        [2]: Channel Number (int)

        [3]: RSSI - received signal strength indicator (int)

        [4]: Authorization Type (see constants)

        [5]: 1 (int)

        You don’t need to be connected to call this.
        """
        ...
    def start_ap(self, ssid: str, key: str | None = None, security: int = OPEN, channel: int = 1) -> None:
        """
        When running in AP mode this method must be called after creating
        a WINC object to configure and start the AP .

        ssid: The AP SSID (must be set).

        key: The AP encryption key. A Key is required only if security is WEP.

        security: AP security mode (only OPEN or WEP are supported).

        channel: WiFi channel, change this if you have another AP running at the same channel.
        """
        ...
    def wait_for_sta(self, timeout: int) -> List[str]:
        """
        This method blocks and waits for a client to connect. If timeout is 0
        this will block forever. This method returns a list containing the
        connected client’s IP adress.
        """
        ...

class WLAN:
    """
    Allowed values for the WLAN.config(pm=...) network interface parameter:

    PM_PERFORMANCE: enable WiFi power management to balance power
    savings and WiFi performance

    PM_POWERSAVE: enable WiFi power management with additional power
    savings and reduced WiFi performance

    PM_NONE: disable wifi power management
    """
    def __init__(self, interface_id: int) -> None: ...
    def active(self, is_active: bool | None = None) -> bool:
        """
        Activate (“up”) or deactivate (“down”) network interface, if boolean
        argument is passed. Otherwise, query current state if no argument is
        provided. Most other methods require active interface.
        """
        ...
    def config(self, **kwargs: Any) -> None:
        """
        Get or set general network interface parameters. These methods allow to work
        with additional parameters beyond standard IP configuration (as dealt with by
        AbstractNIC.ipconfig()). These include network-specific and hardware-specific
        parameters. For setting parameters, keyword argument syntax should be used,
        multiple parameters can be set at once. For querying, parameters name should
        be quoted as a string, and only one parameter can be queries at time:

        # Set WiFi access point name (formally known as SSID) and WiFi channel
        ap.config(ssid='My AP', channel=11)
        # Query params one by one
        print(ap.config('ssid'))
        print(ap.config('channel'))

        Following are commonly supported parameters (availability of a specific parameter
        depends on network technology type, driver, and MicroPython port).





        Parameter

        Description

        mac

        MAC address (bytes)

        ssid

        WiFi access point name (string)

        channel

        WiFi channel (integer). Depending on the port this may only be supported on the AP interface.

        hidden

        Whether SSID is hidden (boolean)

        security

        Security protocol supported (enumeration, see module constants)

        key

        Access key (string)

        hostname

        The hostname that will be sent to DHCP (STA interfaces) and mDNS (if supported, both STA and AP). (Deprecated, use network.hostname() instead)

        reconnects

        Number of reconnect attempts to make (integer, 0=none, -1=unlimited)

        txpower

        Maximum transmit power in dBm (integer or float)

        pm

        WiFi Power Management setting (see below for allowed values)
        """
        ...
    def connect(self, ssid: str | None = None, key: str | None = None, *, bssid: bytes | None = None) -> None:
        """
        Connect to the specified wireless network, using the specified key.
        If bssid is given then the connection will be restricted to the
        access-point with that MAC address (the ssid must also be specified
        in this case).
        """
        ...
    def disconnect(self) -> None:
        """Disconnect from the currently connected wireless network."""
        ...
    def ifconfig(self, config: Tuple[str, str, str, str] | None = None) -> Optional[Tuple[str, str, str, str]]:
        """
        Get/set IP-level network interface parameters: IP address, subnet mask,
        gateway and DNS server. When called with no arguments, this method returns
        a 4-tuple with the above information. To set the above values, pass a
        4-tuple with the required information.  For example:

        nic.ifconfig(('192.168.0.4', '255.255.255.0', '192.168.0.1', '8.8.8.8'))
        """
        ...
    def isconnected(self) -> bool:
        """
        In case of STA mode, returns True if connected to a WiFi access
        point and has a valid IP address.  In AP mode returns True when a
        station is connected. Returns False otherwise.
        """
        ...
    def scan(self) -> List[Tuple[bytes, bytes, int, int, int, int]]:
        """
        Scan for the available wireless networks.
        Hidden networks – where the SSID is not broadcast – will also be scanned
        if the WLAN interface allows it.

        Scanning is only possible on STA interface. Returns list of tuples with
        the information about WiFi access points:

        (ssid, bssid, channel, RSSI, security, hidden)

        bssid is hardware address of an access point, in binary form, returned as
        bytes object. You can use binascii.hexlify() to convert it to ASCII form.

        There are five values for security:

        0 – open

        1 – WEP

        2 – WPA-PSK

        3 – WPA2-PSK

        4 – WPA/WPA2-PSK

        and two for hidden:

        0 – visible

        1 – hidden
        """
        ...
    def status(self, param: str | None = None) -> Any:
        """
        Return the current status of the wireless connection.

        When called with no argument the return value describes the network link status.
        The possible statuses are defined as constants in the network module:

        STAT_IDLE – no connection and no activity,

        STAT_CONNECTING – connecting in progress,

        STAT_WRONG_PASSWORD – failed due to incorrect password,

        STAT_NO_AP_FOUND – failed because no access point replied,

        STAT_CONNECT_FAIL – failed due to other problems,

        STAT_GOT_IP – connection successful.

        When called with one argument param should be a string naming the status
        parameter to retrieve, and different parameters are supported depending on the
        mode the WiFi is in.

        In STA mode, passing 'rssi' returns a signal strength indicator value, whose
        format varies depending on the port (this is available on all ports that support
        WiFi network interfaces, except for CC3200).

        In AP mode, passing 'stations' returns a list of connected WiFi stations
        (this is available on all ports that support WiFi network interfaces, except for
        CC3200).  The format of the station information entries varies across ports,
        providing either the raw BSSID of the connected station, the IP address of the
        connected station, or both.
        """
        ...

