# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List

version_major: int
"""The firmware major version number."""
version_minor: int
"""The firmware minor version number."""
version_patch: int
"""The firmware patch version number."""

def arch() -> str:
    """Returns the board architecture string."""
    ...
def board_id() -> str:
    """Returns the board id string."""
    ...
def board_type() -> str:
    """Returns the board type string."""
    ...
def debug_mode() -> bool:
    """
    Returns True if the OpenMV debug protocol is currently active
    (i.e. the cam is connected to the IDE), False otherwise.
    """
    ...
def version_string() -> str:
    """Returns the firmware version string (e.g. "2.8.0")."""
    ...

