# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List
import machine

class PCA9674A:
    """Resets and re-initializes the I/O expander, and re-attaches the IRQ callback if one was provided."""
    def __init__(self, bus: machine.I2C, irq_pin: str, address: int = 63, callback: Callable | None = None) -> None: ...
    def read(self) -> int:
        """Returns the 8-bit value of the I/O expander pins."""
        ...
    def reset(self) -> None:
        """Resets and re-initializes the I/O expander, and re-attaches the IRQ callback if one was provided."""
        ...
    def write(self, value: int) -> None:
        """Writes the 8-bit value to the I/O expander pins."""
        ...

