# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List
import image

B128X128: int
"""
128x128 resolution. For use with Image.find_displacement() and other FFT
based algorithms.
"""
B128X64: int
"""
128x64 resolution. For use with Image.find_displacement() and other FFT
based algorithms.
"""
B160X160: int
"""160x160 resolution (for the HM01B0)."""
B320X320: int
"""320x320 resolution (for the HM01B0)."""
B64X32: int
"""
64x32 resolution. For use with Image.find_displacement() and other FFT
based algorithms.
"""
B64X64: int
"""
64x64 resolution. For use with Image.find_displacement() and other FFT
based algorithms.
"""
BAYER: int
"""RAW BAYER pixel format. 8-bits per pixel."""
BINARY: int
"""BINARY (bitmap) pixel format. Each pixel is 1-bit."""
BOSON320: int
"""sensor.get_id() returns this for the BOSON 320x256 camera."""
BOSON640: int
"""sensor.get_id() returns this for the BOSON 640x512 camera."""
CIF: int
"""352x288 resolution."""
FHD: int
"""1920x1080 resolution. Only for the OV5640 camera."""
FROGEYE2020: int
"""sensor.get_id() returns this for the FROGEYE2020 camera."""
GC2145: int
"""sensor.get_id() returns this for the GC2145 camera."""
GENX320: int
"""sensor.get_id() returns this for the GENX320 camera."""
GENX320ES: int
"""sensor.get_id() returns this for the GENX320 (engineering sample) camera."""
GENX320_BIASES_ACTIVE_MARKER: int
"""Active-marker biases preset for the GENX320."""
GENX320_BIASES_DEFAULT: int
"""Default biases preset for the GENX320."""
GENX320_BIASES_HIGH_SPEED: int
"""High-speed biases preset for the GENX320."""
GENX320_BIASES_LOW_LIGHT: int
"""Low-light biases preset for the GENX320."""
GENX320_BIASES_LOW_NOISE: int
"""Low-noise biases preset for the GENX320."""
GENX320_BIAS_DIFF_OFF: int
"""GENX320 DIFF_OFF bias selector."""
GENX320_BIAS_DIFF_ON: int
"""GENX320 DIFF_ON bias selector."""
GENX320_BIAS_FO: int
"""GENX320 FO bias selector."""
GENX320_BIAS_HPF: int
"""GENX320 HPF bias selector."""
GENX320_BIAS_REFR: int
"""GENX320 REFR bias selector."""
GRAYSCALE: int
"""GRAYSCALE pixel format (Y from YUV422). Each pixel is 8-bits, 1-byte."""
HD: int
"""1280x720 resolution. Only for the OV2640/OV5640 cameras."""
HM01B0: int
"""sensor.get_id() returns this for the HM01B0 camera."""
HM0360: int
"""sensor.get_id() returns this for the HM0360 camera."""
HQQQQVGA: int
"""40x20 resolution."""
HQQQVGA: int
"""80x40 resolution."""
HQQVGA: int
"""160x80 resolution."""
HQVGA: int
"""240x160 resolution."""
HVGA: int
"""480x320 resolution."""
IOCTL_GENX320_SET_AFK: int
"""Set GENX320 anti-flickering-filter parameters. See sensor.ioctl()."""
IOCTL_GENX320_SET_BIAS: int
"""Set a single GENX320 sensor bias. See sensor.ioctl()."""
IOCTL_GENX320_SET_BIASES: int
"""Set the GENX320 sensor bias preset. See sensor.ioctl()."""
IOCTL_GET_FOV_WIDE: int
"""
Get the current field-of-view-over-FPS optimization state. See
sensor.ioctl().
"""
IOCTL_GET_NIGHT_MODE: int
"""Get the current night-mode state. See sensor.ioctl()."""
IOCTL_GET_READOUT_WINDOW: int
"""Get the sensor readout window. See sensor.ioctl()."""
IOCTL_GET_RGB_STATS: int
"""
Get the (r, gb, gr, b) RGB statistics from the sensor. See
sensor.ioctl().
"""
IOCTL_GET_TRIGGERED_MODE: int
"""Get the current triggered-mode state. See sensor.ioctl()."""
IOCTL_HIMAX_MD_CLEAR: int
"""Clear the HM01B0 motion detection interrupt. See sensor.ioctl()."""
IOCTL_HIMAX_MD_ENABLE: int
"""Enable/disable HM01B0 motion detection. See sensor.ioctl()."""
IOCTL_HIMAX_MD_THRESHOLD: int
"""Set the HM01B0 motion detection threshold. See sensor.ioctl()."""
IOCTL_HIMAX_MD_WINDOW: int
"""Set the HM01B0 motion detection window. See sensor.ioctl()."""
IOCTL_HIMAX_OSC_ENABLE: int
"""Enable/disable the HM01B0 internal oscillator. See sensor.ioctl()."""
IOCTL_LEPTON_GET_ATTRIBUTE: int
"""Get a FLIR Lepton attribute. See sensor.ioctl()."""
IOCTL_LEPTON_GET_AUX_TEMP: int
"""Get the FLIR Lepton AUX temperature in celsius. See sensor.ioctl()."""
IOCTL_LEPTON_GET_FPA_TEMP: int
"""Get the FLIR Lepton FPA temperature in celsius. See sensor.ioctl()."""
IOCTL_LEPTON_GET_HEIGHT: int
"""Get the FLIR Lepton image height in pixels. See sensor.ioctl()."""
IOCTL_LEPTON_GET_MODE: int
"""Get FLIR Lepton measurement-mode state. See sensor.ioctl()."""
IOCTL_LEPTON_GET_RADIOMETRY: int
"""Get the FLIR Lepton type (radiometric or not). See sensor.ioctl()."""
IOCTL_LEPTON_GET_RANGE: int
"""Get the FLIR Lepton measurement-mode temperature range. See sensor.ioctl()."""
IOCTL_LEPTON_GET_REFRESH: int
"""Get the FLIR Lepton refresh rate in Hz. See sensor.ioctl()."""
IOCTL_LEPTON_GET_RESOLUTION: int
"""Get the FLIR Lepton ADC resolution in bits. See sensor.ioctl()."""
IOCTL_LEPTON_GET_WIDTH: int
"""Get the FLIR Lepton image width in pixels. See sensor.ioctl()."""
IOCTL_LEPTON_RUN_COMMAND: int
"""Execute a 16-bit FLIR Lepton SDK command. See sensor.ioctl()."""
IOCTL_LEPTON_SET_ATTRIBUTE: int
"""Set a FLIR Lepton attribute. See sensor.ioctl()."""
IOCTL_LEPTON_SET_MODE: int
"""Set FLIR Lepton measurement mode. See sensor.ioctl()."""
IOCTL_LEPTON_SET_RANGE: int
"""Set the FLIR Lepton measurement-mode temperature range. See sensor.ioctl()."""
IOCTL_PAUSE_AUTO_FOCUS: int
"""Pause auto focus on the OV5640 FPC camera module. See sensor.ioctl()."""
IOCTL_RESET_AUTO_FOCUS: int
"""Reset auto focus on the OV5640 FPC camera module. See sensor.ioctl()."""
IOCTL_SET_FOV_WIDE: int
"""
Optimize sensor.set_framesize() for field-of-view over FPS. See
sensor.ioctl().
"""
IOCTL_SET_NIGHT_MODE: int
"""Enable/disable night mode on the sensor. See sensor.ioctl()."""
IOCTL_SET_READOUT_WINDOW: int
"""Set the sensor readout window. See sensor.ioctl()."""
IOCTL_SET_TRIGGERED_MODE: int
"""Set triggered mode (e.g. for the MT9V034). See sensor.ioctl()."""
IOCTL_TRIGGER_AUTO_FOCUS: int
"""Trigger auto focus on the OV5640 FPC camera module. See sensor.ioctl()."""
IOCTL_WAIT_ON_AUTO_FOCUS: int
"""
Wait on auto focus to complete on the OV5640 FPC camera module. See
sensor.ioctl().
"""
JPEG: int
"""JPEG mode. Compressed JPEG output. Only works for the OV2640/OV5640 cameras."""
LCD: int
"""128x160 resolution (for use with the LCD shield)."""
LEPTON: int
"""sensor.get_id() returns this for the LEPTON1/2/3 cameras."""
MT9M114: int
"""sensor.get_id() returns this for the MT9M114 camera."""
MT9V022: int
"""sensor.get_id() returns this for the MT9V022 camera."""
MT9V024: int
"""sensor.get_id() returns this for the MT9V024 camera."""
MT9V032: int
"""sensor.get_id() returns this for the MT9V032 camera."""
MT9V034: int
"""sensor.get_id() returns this for the MT9V034 camera."""
NEGATIVE: int
"""Pass to sensor.set_special_effect() for negative-image output."""
NORMAL: int
"""Pass to sensor.set_special_effect() for normal (no SDE) output."""
OV2640: int
"""sensor.get_id() returns this for the OV2640 camera."""
OV5640: int
"""sensor.get_id() returns this for the OV5640 camera."""
OV7670: int
"""sensor.get_id() returns this for the OV7670 camera."""
OV7690: int
"""sensor.get_id() returns this for the OV7690 camera."""
OV7725: int
"""sensor.get_id() returns this for the OV7725 camera."""
OV9650: int
"""sensor.get_id() returns this for the OV9650 camera."""
PAG7920: int
"""sensor.get_id() returns this for the PAG7920 camera."""
PAG7936: int
"""sensor.get_id() returns this for the PAG7936 camera."""
PAJ6100: int
"""sensor.get_id() returns this for the PAJ6100 camera."""
QCIF: int
"""176x144 resolution."""
QHD: int
"""2560x1440 resolution. Only for the OV5640 camera."""
QQCIF: int
"""88x72 resolution."""
QQQQVGA: int
"""40x30 resolution."""
QQQVGA: int
"""80x60 resolution."""
QQSIF: int
"""88x60 resolution."""
QQVGA: int
"""160x120 resolution."""
QQVGA2: int
"""128x160 resolution (for use with the LCD shield)."""
QSIF: int
"""176x120 resolution."""
QVGA: int
"""320x240 resolution."""
QXGA: int
"""2048x1536 resolution. Only for the OV5640 camera."""
RGB565: int
"""
RGB565 pixel format. Each pixel is 16-bits, 2-bytes. 5-bits red, 6-bits
green, 5-bits blue.
"""
SIF: int
"""352x240 resolution."""
SVGA: int
"""800x600 resolution. Only for the OV2640/OV5640 cameras."""
SXGA: int
"""1280x1024 resolution. Only for the OV2640/OV5640 cameras."""
SXGAM: int
"""1280x960 resolution (for the MT9M114)."""
UXGA: int
"""1600x1200 resolution. Only for the OV2640/OV5640 cameras."""
VGA: int
"""640x480 resolution."""
WQXGA: int
"""2560x1600 resolution. Only for the OV5640 camera."""
WQXGA2: int
"""2592x1944 resolution. Only for the OV5640 camera."""
WVGA: int
"""720x480 resolution (for the MT9V034)."""
WVGA2: int
"""752x480 resolution (for the MT9V034)."""
WXGA: int
"""1280x768 resolution (for the MT9M114)."""
XGA: int
"""1024x768 resolution. Only for the OV2640/OV5640 cameras."""
YUV422: int
"""YUV422 pixel format (8-bits Y1, 8-bits U, 8-bits Y2, 8-bits V, etc.)."""

def __read_reg(address: int) -> int:
    """
    Read camera register at address.

    See the camera data sheet for register info.
    """
    ...
def __write_reg(address: int, value: int) -> None:
    """
    Write value to camera register at address.

    See the camera data sheet for register info.
    """
    ...
def alloc_extra_fb(width: int, height: int, pixformat: int) -> image.Image:
    """
    Deprecated since version 4.5: This function is deprecated and will raise OSError. Use the new
    csi module instead.
    """
    ...
def dealloc_extra_fb() -> None:
    """
    Deprecated since version 4.5: This function is deprecated and will raise OSError. Use the new
    csi module instead.
    """
    ...
def disable_delays(disable: bool | None = None) -> Optional[bool]:
    """
    If disable is True then disable all settling time delays in the
    sensor module.

    If called with no arguments returns True if delays are disabled.
    """
    ...
def disable_full_flush(disable: bool | None = None) -> Optional[bool]:
    """
    If disable is True then automatic framebuffer flushing on frame
    drop is disabled.

    If called with no arguments returns True if automatic flushing is
    disabled.
    """
    ...
def flush() -> None:
    """Copies whatever was in the frame buffer to the IDE preview."""
    ...
def get_auto_rotation() -> bool:
    """Returns True if auto rotation mode is enabled."""
    ...
def get_blc_regs() -> List[int]:
    """
    Returns the sensor BLC registers as a list of integers. For use with
    sensor.set_auto_blc().
    """
    ...
def get_color_palette() -> Optional[int]:
    """
    Returns the current color palette setting, or None if the active
    palette is unrecognized.
    """
    ...
def get_exposure_us() -> int:
    """Returns the current camera exposure value in microseconds."""
    ...
def get_fb() -> Optional[image.Image]:
    """
    Returns the image object returned by a previous call of sensor.snapshot().
    Returns None if sensor.snapshot() has not been called before.
    """
    ...
def get_frame_available() -> bool:
    """Returns True if a frame is available to read by calling sensor.snapshot()."""
    ...
def get_framebuffers() -> int:
    """Returns the current number of frame buffers allocated."""
    ...
def get_framerate() -> int:
    """Returns the frame rate in Hz for the camera module."""
    ...
def get_framesize() -> int:
    """Returns the current frame size for the camera module."""
    ...
def get_gain_db() -> float:
    """Returns the current camera gain value in decibels."""
    ...
def get_hmirror() -> bool:
    """Returns True if horizontal mirror mode is enabled."""
    ...
def get_id() -> int:
    """Returns the camera module ID. See the sensor constants below."""
    ...
def get_pixformat() -> int:
    """Returns the current pixformat for the camera module."""
    ...
def get_rgb_gain_db() -> Tuple[float, float, float]:
    """
    Returns a tuple with the current camera red, green, and blue gain values
    in decibels.
    """
    ...
def get_transpose() -> bool:
    """Returns True if transpose mode is enabled."""
    ...
def get_vflip() -> bool:
    """Returns True if vertical flip mode is enabled."""
    ...
def get_windowing() -> Tuple[int, int, int, int]:
    """
    Returns the roi tuple (x, y, w, h) previously set with
    sensor.set_windowing().
    """
    ...
def height() -> int:
    """Returns the sensor resolution height."""
    ...
def ioctl(request: int, *args: Any) -> Any:
    """
    Executes a sensor specific method. request is one of the
    IOCTL_* constants documented below. The remaining arguments and the
    return value depend on request:

    sensor.IOCTL_SET_READOUT_WINDOW - Pass a rect tuple (x, y, w, h) or a size tuple (w, h).

    sensor.IOCTL_GET_READOUT_WINDOW - Returns the current readout window rect tuple (x, y, w, h).

    sensor.IOCTL_SET_TRIGGERED_MODE - Pass True or False.

    sensor.IOCTL_GET_TRIGGERED_MODE - Returns the current triggered-mode state as a bool.

    sensor.IOCTL_SET_FOV_WIDE - Pass True or False to optimize sensor.set_framesize() for field-of-view over FPS.

    sensor.IOCTL_GET_FOV_WIDE - Returns the current field-of-view-over-FPS optimization state as a bool.

    sensor.IOCTL_SET_NIGHT_MODE - Pass True or False to enable/disable night mode.

    sensor.IOCTL_GET_NIGHT_MODE - Returns the current night-mode state as a bool.

    sensor.IOCTL_TRIGGER_AUTO_FOCUS - Triggers auto focus on the OV5640 FPC camera module.

    sensor.IOCTL_PAUSE_AUTO_FOCUS - Pauses auto focus on the OV5640 FPC camera module.

    sensor.IOCTL_RESET_AUTO_FOCUS - Resets auto focus on the OV5640 FPC camera module.

    sensor.IOCTL_WAIT_ON_AUTO_FOCUS - Waits for auto focus to finish on the OV5640 FPC camera module. Optional second argument is the timeout in milliseconds (default 5000).

    sensor.IOCTL_LEPTON_GET_WIDTH - Returns the FLIR Lepton image width in pixels.

    sensor.IOCTL_LEPTON_GET_HEIGHT - Returns the FLIR Lepton image height in pixels.

    sensor.IOCTL_LEPTON_GET_RADIOMETRY - Returns the FLIR Lepton type (radiometric or not).

    sensor.IOCTL_LEPTON_GET_REFRESH - Returns the FLIR Lepton refresh rate in Hz.

    sensor.IOCTL_LEPTON_GET_RESOLUTION - Returns the FLIR Lepton ADC resolution in bits.

    sensor.IOCTL_LEPTON_RUN_COMMAND - Pass a 16-bit command id (FLIR Lepton SDK).

    sensor.IOCTL_LEPTON_SET_ATTRIBUTE - Pass the 16-bit attribute id and a bytes/bytearray payload (multiple of 16-bits).

    sensor.IOCTL_LEPTON_GET_ATTRIBUTE - Pass the 16-bit attribute id and the number of 16-bit words to read. Returns a bytearray.

    sensor.IOCTL_LEPTON_GET_FPA_TEMP - Returns the FLIR Lepton FPA temperature in celsius.

    sensor.IOCTL_LEPTON_GET_AUX_TEMP - Returns the FLIR Lepton AUX temperature in celsius.

    sensor.IOCTL_LEPTON_SET_MODE - Pass enable followed by an optional high_temp flag.

    sensor.IOCTL_LEPTON_GET_MODE - Returns the tuple (measurement-mode-enabled, high-temp-enabled).

    sensor.IOCTL_LEPTON_SET_RANGE - Pass min_temp_c and max_temp_c floats.

    sensor.IOCTL_LEPTON_GET_RANGE - Returns the sorted (min, max) 2-tuple temperature range in celsius.

    sensor.IOCTL_HIMAX_MD_ENABLE - Pass True/False to enable/disable motion detection on the HM01B0.

    sensor.IOCTL_HIMAX_MD_WINDOW - Pass a rect tuple (x, y, w, h) or a size tuple (w, h).

    sensor.IOCTL_HIMAX_MD_THRESHOLD - Pass a threshold value (0-255).

    sensor.IOCTL_HIMAX_MD_CLEAR - Clears the motion detection interrupt on the HM01B0.

    sensor.IOCTL_HIMAX_OSC_ENABLE - Pass True/False to enable/disable the HM01B0 oscillator.

    sensor.IOCTL_GET_RGB_STATS - Returns the tuple (r, gb, gr, b) of RGB statistics from the camera sensor.

    sensor.IOCTL_GENX320_SET_BIASES - Pass one of the GENX320_BIASES_* constants to set the GENX320 sensor biases.

    sensor.IOCTL_GENX320_SET_BIAS - Pass one of the GENX320_BIAS_* constants and an integer bias value.

    sensor.IOCTL_GENX320_SET_AFK - Pass either enable (True/False) alone or enable, freq_low_in_hz, freq_high_in_hz.
    """
    ...
def reset() -> None:
    """Initializes the camera sensor."""
    ...
def set_auto_blc(enable: int, regs: List[int] | None = None) -> None:
    """
    Sets the auto black level calibration (BLC) control on the camera.

    enable is 1 to enable or 0 to disable.

    regs if disabled, you can manually set the BLC register values via the
    values previously read from sensor.get_blc_regs(). The list length must
    match the sensor’s BLC register count.
    """
    ...
def set_auto_exposure(enable: int, exposure_us: int = -1) -> None:
    """
    enable turns auto exposure control on (1) or off (0).

    If enable is 0 you may set a fixed exposure time in microseconds
    with exposure_us. exposure_us is a keyword-only argument.
    """
    ...
def set_auto_gain(enable: int, gain_db: float | None = None, gain_db_ceiling: float | None = None) -> None:
    """
    enable turns auto gain control on (1) or off (0).

    If enable is 0 you may set a fixed gain in decibels with gain_db.

    If enable is non-zero you may set the maximum gain ceiling in decibels
    with gain_db_ceiling for the automatic gain control algorithm.

    gain_db and gain_db_ceiling are keyword-only arguments.
    """
    ...
def set_auto_rotation(enable: bool) -> None:
    """
    Turns auto rotation mode on (True) or off (False). Defaults to off.
    Only works when the OpenMV Cam has an imu installed.
    """
    ...
def set_auto_whitebal(enable: int, rgb_gain_db: Tuple[float, float, float] | None = None) -> None:
    """
    enable turns auto white balance on (1) or off (0).

    If enable is 0 you may set a fixed gain in decibels for the red,
    green, and blue channels respectively with rgb_gain_db.
    rgb_gain_db is a keyword-only argument.
    """
    ...
def set_brightness(brightness: int) -> bool:
    """
    Set the camera image brightness. Valid range is -3 to +3. Returns
    True on success.
    """
    ...
def set_color_palette(palette: int) -> None:
    """
    Sets the color palette for the FLIR Lepton (and similar) grayscale to
    RGB565 conversion. palette is one of image.PALETTE_RAINBOW,
    image.PALETTE_IRONBOW, image.PALETTE_DEPTH, image.PALETTE_EVT_DARK,
    or image.PALETTE_EVT_LIGHT.
    """
    ...
def set_colorbar(enable: bool) -> bool:
    """
    Turns color bar test mode on (True) or off (False). Returns True
    on success.
    """
    ...
def set_contrast(contrast: int) -> bool:
    """
    Set the camera image contrast. Valid range is -3 to +3. Returns
    True on success.
    """
    ...
def set_frame_callback(cb: Callable[[], None] | None) -> None:
    """
    Registers callback cb to be executed (in interrupt context) whenever
    the camera module generates a new frame and the frame is ready to be read
    via sensor.snapshot().

    cb takes no arguments.

    Pass a non-callable (e.g. None) to unregister.
    """
    ...
def set_framebuffers(count: int) -> None:
    """
    Sets the number of frame buffers used to receive image data.

    count may be 1 (single buffer), 2 (double buffer), 3
    (triple buffer), or 4 or greater to put the sensor driver into video
    FIFO mode where received frames are stored in a FIFO of count buffers.
    """
    ...
def set_framerate(rate: int) -> None:
    """Sets the frame rate in Hz for the camera module."""
    ...
def set_framesize(framesize: int) -> None:
    """
    Sets the frame size for the camera module. See the framesize constants
    below for valid values.
    """
    ...
def set_gainceiling(gainceiling: int) -> bool:
    """
    Set the camera image gain ceiling. Valid values are 2, 4, 8,
    16, 32, 64, or 128. Returns True on success.
    """
    ...
def set_hmirror(enable: bool) -> None:
    """Turns horizontal mirror mode on (True) or off (False). Defaults to off."""
    ...
def set_lens_correction(enable: bool, radi: int, coef: int) -> bool:
    """
    enable True to enable, False to disable.
    radi integer radius of pixels to correct.
    coef power of correction.

    Returns True on success.
    """
    ...
def set_pixformat(pixformat: int) -> None:
    """
    Sets the pixel format for the camera module. pixformat is one of:

    sensor.BINARY

    sensor.GRAYSCALE

    sensor.RGB565

    sensor.BAYER

    sensor.YUV422

    sensor.JPEG (only for the OV2640/OV5640)
    """
    ...
def set_quality(quality: int) -> bool:
    """
    Set the camera image JPEG compression quality. Valid range is 0 to 100.
    Returns True on success. Only for the OV2640/OV5640 cameras.
    """
    ...
def set_saturation(saturation: int) -> bool:
    """
    Set the camera image saturation. Valid range is -3 to +3. Returns
    True on success.
    """
    ...
def set_special_effect(sde: int) -> bool:
    """
    Sets the special digital effect (SDE) on the sensor. sde is one of
    sensor.NORMAL or sensor.NEGATIVE. Returns True on success.
    """
    ...
def set_transpose(enable: bool) -> None:
    """
    Turns transpose mode on (True) or off (False). Defaults to off.

    vflip=False, hmirror=False, transpose=False -> 0 degree rotation

    vflip=True,  hmirror=False, transpose=True  -> 90 degree rotation

    vflip=True,  hmirror=True,  transpose=False -> 180 degree rotation

    vflip=False, hmirror=True,  transpose=True  -> 270 degree rotation
    """
    ...
def set_vflip(enable: bool) -> None:
    """Turns vertical flip mode on (True) or off (False). Defaults to off."""
    ...
def set_vsync_callback(cb: Callable[[int], None] | None) -> None:
    """
    Registers callback cb to be executed (in interrupt context) whenever
    the camera module generates a new frame (but before the frame is received).

    cb takes one argument: the current state of the vsync pin after changing.

    Pass a non-callable (e.g. None) to unregister.
    """
    ...
def set_windowing(roi: Tuple[int, int] | Tuple[int, int, int, int] | List[int]) -> None:
    """
    Sets the resolution of the camera to a sub-resolution inside of the current
    resolution.

    roi is a rect tuple/list (x, y, w, h). You may also pass (w, h)
    and the roi will be centered on the frame. The arguments may also be
    passed unpacked as positional integers.
    """
    ...
def shutdown(enable: bool) -> None:
    """
    Puts the camera into a lower power mode than sleep. The camera must be
    reset on being woken up.
    """
    ...
def skip_frames(n: int | None = None, time: int = 300) -> None:
    """
    Skips n frames or time milliseconds (whichever is specified) to let
    the camera image stabilize after changing camera settings.

    If neither n nor time is specified this method skips frames for
    300 milliseconds.

    If both are specified this method skips n frames but will timeout
    after time milliseconds.
    """
    ...
def sleep(enable: bool) -> None:
    """Puts the camera to sleep if enable is True. Otherwise, wakes it back up."""
    ...
def snapshot() -> image.Image:
    """
    Takes a picture using the camera and returns an image.Image object.

    If sensor.set_auto_rotation() is enabled this method returns a new
    already rotated image.Image object.
    """
    ...
def width() -> int:
    """Returns the sensor resolution width."""
    ...

