# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List
import machine

SET_CHARGE_PUMP: int
"""Command 0x8D – charge pump configuration."""
SET_COL_ADDR: int
"""Command 0x21 – column address range."""
SET_COM_OUT_DIR: int
"""Command 0xC0 – COM output scan direction."""
SET_COM_PIN_CFG: int
"""Command 0xDA – COM pins hardware configuration."""
SET_CONTRAST: int
"""Command 0x81 – set display contrast."""
SET_DISP: int
"""Command 0xAE – display on/off."""
SET_DISP_CLK_DIV: int
"""
Command 0xD5 – display clock divide ratio / oscillator
frequency.
"""
SET_DISP_OFFSET: int
"""Command 0xD3 – display offset."""
SET_DISP_START_LINE: int
"""Command 0x40 – display start line."""
SET_ENTIRE_ON: int
"""Command 0xA4 – resume display from RAM contents."""
SET_MEM_ADDR: int
"""Command 0x20 – memory addressing mode."""
SET_MUX_RATIO: int
"""Command 0xA8 – multiplex ratio."""
SET_NORM_INV: int
"""Command 0xA6 – normal/inverse display select."""
SET_PAGE_ADDR: int
"""Command 0x22 – page address range."""
SET_PRECHARGE: int
"""Command 0xD9 – pre-charge period."""
SET_SEG_REMAP: int
"""Command 0xA0 – segment remap."""
SET_VCOM_DESEL: int
"""Command 0xDB – VCOMH deselect level."""

class SSD1306:
    """
    Draw a string using the built-in 8x8 font.

    string – Text to draw.

    x – Starting column coordinate.

    y – Starting row coordinate.

    col – Foreground color (default 1).
    """
    def __init__(self, width: int, height: int, external_vcc: bool) -> None: ...
    def contrast(self, contrast: int) -> None:
        """
        Set the display contrast.

        contrast – Contrast value in the range 0–255.
        """
        ...
    def fill(self, col: int) -> None:
        """
        Fill the entire framebuffer with a single color.

        col – Color value (0 for off, 1 for on).
        """
        ...
    def init_display(self) -> None:
        """
        Send the initialization command sequence to the display, clear
        the framebuffer, and refresh. Called automatically by
        __init__.
        """
        ...
    def invert(self, invert: int) -> None:
        """
        Invert the display colors.

        invert – 0 for normal output, 1 for inverted
        output. Only the least significant bit is used.
        """
        ...
    def pixel(self, x: int, y: int, col: int) -> None:
        """
        Set the color of a single pixel.

        x – Column coordinate.

        y – Row coordinate.

        col – Color value (0 or 1).
        """
        ...
    def poweroff(self) -> None:
        """Turn the display off (sleep mode)."""
        ...
    def scroll(self, dx: int, dy: int) -> None:
        """
        Shift the framebuffer contents by the given offsets. Pixels
        shifted out of bounds are lost; vacated pixels are left
        untouched.

        dx – Horizontal shift in pixels.

        dy – Vertical shift in pixels.
        """
        ...
    def show(self) -> None:
        """Flush the internal framebuffer to the display."""
        ...
    def text(self, string: str, x: int, y: int, col: int = 1) -> None:
        """
        Draw a string using the built-in 8x8 font.

        string – Text to draw.

        x – Starting column coordinate.

        y – Starting row coordinate.

        col – Foreground color (default 1).
        """
        ...

class SSD1306_I2C:
    """Send a buffer of pixel data to the display over I2C."""
    def __init__(self, width: int, height: int, i2c: machine.I2C, addr: int = 0x3C, external_vcc: bool = False) -> None: ...
    def write_cmd(self, cmd: int) -> None:
        """Send a single command byte to the display over I2C."""
        ...
    def write_data(self, buf: bytes) -> None:
        """Send a buffer of pixel data to the display over I2C."""
        ...

class SSD1306_SPI:
    """Toggle the reset line to power the display on."""
    def __init__(self, width: int, height: int, spi: machine.SPI, dc: machine.Pin, res: machine.Pin, cs: machine.Pin, external_vcc: bool = False) -> None: ...
    def poweron(self) -> None:
        """Toggle the reset line to power the display on."""
        ...
    def write_cmd(self, cmd: int) -> None:
        """Send a single command byte to the display over SPI."""
        ...
    def write_framebuf(self) -> None:
        """Transmit the entire framebuffer to the display over SPI."""
        ...

