# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List

GPIOA: int
"""Base address of the GPIOA peripheral."""
GPIOB: int
"""Base address of the GPIOB peripheral."""
GPIO_BSRR: int
"""Offset of the GPIO bit set/reset register."""
GPIO_IDR: int
"""Offset of the GPIO input data register."""
GPIO_ODR: int
"""Offset of the GPIO output data register."""
mem16: int
"""
Subscriptable 16-bit (halfword) memory accessor. mem16[addr] reads an
int in the range 0-65535; mem16[addr] = value writes the low 16
bits. addr must be aligned to 2 bytes.
"""
mem32: int
"""
Subscriptable 32-bit (word) memory accessor. mem32[addr] reads an
int in the range 0-0xFFFFFFFF; mem32[addr] = value writes the low
32 bits. addr must be aligned to 4 bytes.
"""
mem8: int
"""
Subscriptable 8-bit memory accessor. mem8[addr] reads an int in the
range 0-255 from the byte at addr; mem8[addr] = value writes the
low 8 bits of value. addr may be any byte-aligned address.
"""

def rfcore_fw_version(id: int) -> Tuple[int, int, int, int, int]:
    """
    Get the version of the firmware running on the second CPU.  Pass in 0 for
    id to get the FUS version, and 1 to get the WS version.

    Returns a 5-tuple with the full version number.
    """
    ...
def rfcore_status() -> int:
    """
    Returns the status of the second CPU as an integer (the first word of device
    info table).
    """
    ...
def rfcore_sys_hci(ogf: int, ocf: int, data: bytes, timeout_ms: int = 0) -> bytes:
    """
    Execute a HCI command on the SYS channel.  The execution is synchronous.

    Returns a bytes object with the result of the SYS command.
    """
    ...
def subghz_cs(level: bool) -> None:
    """
    Sets the internal SPI CS pin attached to the radio peripheral. The level
    argument is active-low: a truthy value means “CS pin high” and de-asserts the
    signal, a falsey value means “CS pin low” and asserts the signal.

    The internal-only SPI bus corresponding to this CS signal can be instantiated
    using machine.SPI() id value "SUBGHZ".
    """
    ...
def subghz_irq(handler: Callable[..., Any] | None) -> None:
    """
    Sets the internal SUBGHZ radio interrupt handler to the provided
    function. The handler function is called as a “hard” interrupt in response to
    radio peripheral interrupts. See isr_rules for more information about
    interrupt handlers in MicroPython.

    Calling this function with the handler argument set to None disables the IRQ.

    Due to a hardware limitation, each time this IRQ fires MicroPython disables
    it before calling the handler. In order to receive another interrupt, Python
    code should call subghz_irq() to set the handler again. This has the side
    effect of re-enabling the IRQ.
    """
    ...
def subghz_is_busy() -> bool:
    """
    Return a bool corresponding to the internal “RFBUSYS” signal from the
    radio peripheral. Before sending a new command to the radio over SPI then
    this function should be polled until it returns False, to confirm the
    busy signal is de-asserted.
    """
    ...

