# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List

class Motor:
    """
    Set the motor speed and direction.

    pwm: Signed duty cycle in the range -100 to 100. Positive
    values drive the motor forward, negative values drive it in reverse.
    The absolute value is applied as the PWM duty cycle percentage to the
    power pin.
    """
    def __init__(self, channel: int) -> None: ...
    def set_speed(self, pwm: int) -> None:
        """
        Set the motor speed and direction.

        pwm: Signed duty cycle in the range -100 to 100. Positive
        values drive the motor forward, negative values drive it in reverse.
        The absolute value is applied as the PWM duty cycle percentage to the
        power pin.
        """
        ...

class Stepper:
    """
    Advance the stepper by num phase transitions, applying the next
    phase from phase_list() and waiting the configured inter-step
    delay (via pyb.udelay) between transitions.

    num: Number of phase steps to advance. Each call to step
    advances exactly this many phases; direction is fixed (the underlying
    phase generator only iterates forward).
    """
    def __init__(self, stepnumber: int = 200, rpms: int = 2, power: int = 50) -> None: ...
    def phase_list(self) -> Generator[tuple[int, int, int, int], None, None]:
        """
        Generator that endlessly yields the four-phase drive pattern
        (1, 0, 0, 0), (0, 0, 1, 0), (0, 1, 0, 0), (0, 0, 0, 1)
        used by step(). Each tuple element is the value to write to
        pin1, pin2, pin3, pin4 respectively.
        """
        ...
    def set_power(self, power: int) -> None:
        """
        Set the PWM duty cycle applied to both power channels.

        power: Duty cycle percentage in the range 0 to 100.
        """
        ...
    def set_speed(self, rpms: int) -> None:
        """
        Update the stepping speed.

        rpms: Target rotation speed in revolutions per minute. The
        per-half-step delay (in microseconds) is recomputed as
        1000000 / (rpms * stepnumber) / 2.
        """
        ...
    def step(self, num: int) -> None:
        """
        Advance the stepper by num phase transitions, applying the next
        phase from phase_list() and waiting the configured inter-step
        delay (via pyb.udelay) between transitions.

        num: Number of phase steps to advance. Each call to step
        advances exactly this many phases; direction is fixed (the underlying
        phase generator only iterates forward).
        """
        ...

