# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List

def collect() -> None:
    """
    Runs a collection cycle on the Micro Allocator, releasing memory that is
    no longer in use.
    """
    ...
def init() -> None:
    """Initializes the Micro Allocator."""
    ...
def print_stats(index: int = -1) -> None:
    """
    Prints allocator statistics for the pool selected by index to the
    serial terminal. When index is -1 (the default), statistics for
    all pools are printed.
    """
    ...
def stats(index: int = -1) -> tuple[int, int, int, int, int, int, int]:
    """
    Returns a 7-tuple of statistics for the allocator pool selected by
    index. When index is -1 (the default), aggregated statistics
    across all pools are returned.

    The tuple contains:

    used_count — number of currently allocated blocks.

    free_count — number of free blocks.

    persist_count — number of persistent blocks.

    used_bytes — total bytes currently allocated.

    free_bytes — total bytes free.

    persist_bytes — total bytes held by persistent allocations.

    peak_bytes — peak bytes ever allocated.
    """
    ...

