# Auto-generated by tools/genpyi.py -- do not edit
"""
Typically imported via from ulab import scipy.

The scipy module itself exposes no functions of its own — all of its
functionality lives in the submodules listed below.
"""

from typing import Any

