# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List

def erf(x: ndarray | Iterable[float] | float) -> ndarray:
    """
    Element-wise Gauss error function,
    erf(x) = (2 / sqrt(pi)) * integral(exp(-t**2), 0, x).
    Parameters

    x – a scalar, scalar-valued iterable, or
    numpy.ndarray.

    Returns

    a float numpy.ndarray with the same shape as the
    input.
    """
    ...
def erfc(x: ndarray | Iterable[float] | float) -> ndarray:
    """
    Element-wise complementary error function, erfc(x) = 1 - erf(x),
    computed in a way that retains accuracy for large x.
    Parameters

    x – a scalar, scalar-valued iterable, or
    numpy.ndarray.

    Returns

    a float numpy.ndarray with the same shape as the
    input.
    """
    ...
def gamma(x: ndarray | Iterable[float] | float) -> ndarray:
    """
    Element-wise Gamma function.
    Parameters

    x – a scalar, scalar-valued iterable, or
    numpy.ndarray.

    Returns

    a float numpy.ndarray with the same shape as the
    input.
    """
    ...
def gammaln(x: ndarray | Iterable[float] | float) -> ndarray:
    """
    Element-wise natural logarithm of the absolute value of the Gamma
    function.
    Parameters

    x – a scalar, scalar-valued iterable, or
    numpy.ndarray.

    Returns

    a float numpy.ndarray with the same shape as the
    input.
    """
    ...

