# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List
import ml
import numpy

class YoloLC:
    """
    Create a YOLO LC postprocessor.
    threshold Score threshold applied before non-maximum suppression.
    anchors 2D numpy.ndarray of shape (N, 2) holding (w, h)
    anchor box dimensions the model was trained on. If None, a built-in
    default set of 5 YOLO LC anchors is used.
    nms_threshold Threshold passed to non-maximum suppression.
    nms_sigma Sigma value passed to non-maximum suppression.
    """
    def __init__(self, threshold: float = 0.6, anchors: numpy.ndarray = None, nms_threshold: float = 0.1, nms_sigma: float = 0.1) -> None: ...
    def __call__(self, model: ml.Model, inputs: list, outputs: list) -> list:
        """Inherited from YoloV2. See YoloV2.__call__()."""
        ...

class YoloV2:
    """
    Create a YOLO V2 postprocessor.
    threshold Score threshold applied before non-maximum suppression.
    anchors 2D numpy.ndarray of shape (N, 2) holding (w, h)
    anchor box dimensions the model was trained on. If None, a built-in
    default set of 5 anchors is used.
    nms_threshold Threshold passed to non-maximum suppression.
    nms_sigma Sigma value passed to non-maximum suppression.
    """
    def __init__(self, threshold: float = 0.6, anchors: numpy.ndarray = None, nms_threshold: float = 0.1, nms_sigma: float = 0.1) -> None: ...
    def __call__(self, model: ml.Model, inputs: list, outputs: list) -> list:
        """
        Invoked by ml.Model.predict() to post-process model outputs.
        model The ml.Model instance the post-processor is attached to.
        inputs List of model input objects (used to obtain the input ROI).
        outputs List of raw model output tensors.
        Returns a list of per-class lists of ((x, y, w, h), score) tuples.
        E.g. [[((x, y, w, h), score), ...], ...]. Empty class lists are kept
        so each list index matches the model’s class index.
        """
        ...

