# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List

class Model:
    """
    List of label strings loaded from the .txt file alongside the model, or None if no such
    file exists.
    """
    def __init__(self, path: str, postprocess: object = None) -> None: ...
    input_dtype: Any
    """
    List of label strings loaded from the .txt file alongside the model, or None if no such
    file exists.
    """
    input_scale: Any
    """
    List of label strings loaded from the .txt file alongside the model, or None if no such
    file exists.
    """
    input_shape: Any
    """
    List of label strings loaded from the .txt file alongside the model, or None if no such
    file exists.
    """
    input_zero_point: Any
    """
    List of label strings loaded from the .txt file alongside the model, or None if no such
    file exists.
    """
    labels: Any
    """
    List of label strings loaded from the .txt file alongside the model, or None if no such
    file exists.
    """
    len: Any
    """
    List of label strings loaded from the .txt file alongside the model, or None if no such
    file exists.
    """
    output_dtype: Any
    """
    List of label strings loaded from the .txt file alongside the model, or None if no such
    file exists.
    """
    output_scale: Any
    """
    List of label strings loaded from the .txt file alongside the model, or None if no such
    file exists.
    """
    output_shape: Any
    """
    List of label strings loaded from the .txt file alongside the model, or None if no such
    file exists.
    """
    output_zero_point: Any
    """
    List of label strings loaded from the .txt file alongside the model, or None if no such
    file exists.
    """
    postprocess: Any
    """
    List of label strings loaded from the .txt file alongside the model, or None if no such
    file exists.
    """
    ram: Any
    """
    List of label strings loaded from the .txt file alongside the model, or None if no such
    file exists.
    """
    def predict(self, inputs: list, *, callback: object = None) -> list:
        """
        Runs inference on the model and returns the output tensors.

        inputs is a list with one entry per model input tensor. Each entry may be:

        An ndarray whose shape matches the corresponding entry in Model.input_shape. Values
        are quantized using the input tensor’s scale and zero point (float32 inputs are passed
        through unchanged).

        An image.Image object. The wrapper automatically wraps it in a
        ml.preprocessing.Normalization object to convert it to the expected tensor.

        A callable. It will be invoked with (bytearray, shape, dtype) and is expected to fill
        the bytearray with the input tensor data.

        callback is an optional per-call post-processing callable. When supplied, it overrides
        the postprocess set on the constructor for this call only. The callback receives
        (model, inputs, outputs) and its return value is returned by predict.

        Returns a list of ndarray outputs, one per model output tensor. If no post-processor is
        active the outputs are dequantized to float32; if a post-processor is active the raw
        output tensors (using each tensor’s native dtype) are passed to it instead.
        """
        ...

