# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List

class Normalization:
    """
    When called with a single image.Image argument, returns a new Normalization
    object bound to that image. The bound object is what ml.Model.predict() invokes
    internally to fill the input tensor. If roi was not set on the original
    instance, it is initialized to the full image size.

    When called with (buffer, shape, dtype), fills buffer in-place with the
    normalized input tensor for the previously bound image. shape must be
    (1, H, W, C) with C equal to 1 (grayscale) or 3 (RGB).
    dtype is the ulab numpy type code (e.g. ord('f') for float32, ord('b')
    for int8, ord('B') for uint8). Float tensors apply scale, mean, and
    stdev; integer tensors are written directly (with an offset for int8).
    """
    def __init__(self, scale: tuple[float, float] = (0.0, 1.0), mean: tuple[float, float, float] = (0.0, 0.0, 0.0), stdev: tuple[float, float, float] = (1.0, 1.0, 1.0), roi: tuple[int, int, int, int] = None) -> None: ...
    def __call__(self, buffer: bytearray, shape: tuple[int, int, int, int], dtype: int) -> None:
        """
        When called with a single image.Image argument, returns a new Normalization
        object bound to that image. The bound object is what ml.Model.predict() invokes
        internally to fill the input tensor. If roi was not set on the original
        instance, it is initialized to the full image size.

        When called with (buffer, shape, dtype), fills buffer in-place with the
        normalized input tensor for the previously bound image. shape must be
        (1, H, W, C) with C equal to 1 (grayscale) or 3 (RGB).
        dtype is the ulab numpy type code (e.g. ord('f') for float32, ord('b')
        for int8, ord('B') for uint8). Float tensors apply scale, mean, and
        stdev; integer tensors are written directly (with an offset for int8).
        """
        ...

