# Auto-generated by tools/genpyi.py -- do not edit
"""
Rejects state-changing requests that originate cross-site. The check
runs as a before_request hook and uses the browser-supplied
Sec-Fetch-Site header (with the Origin header as a fallback for
older browsers, when paired with a microdot.cors.CORS
instance).
"""

from typing import Any

class CSRF:
    """
    app

    The microdot.Microdot instance to install on. Optional;
    call initialize() later if not given.

    cors

    The microdot.cors.CORS instance that defines the
    application’s trusted origins. Required for falling back to the
    Origin header on browsers that do not send
    Sec-Fetch-Site. Optional; without it, only the
    Sec-Fetch-Site check applies.

    protect_all

    If True (default), every route except GET, HEAD, and
    OPTIONS is protected automatically. Routes can be exempted
    individually with exempt(). If False, no routes are
    protected by default and individual routes opt in with
    protect().

    allow_subdomains

    If True, requests from subdomains of the application’s
    origins are accepted (same-site Sec-Fetch-Site, or matching
    origin suffix).
    """
    def __init__(self, app: Microdot | None = None, cors=None, protect_all: bool = True, allow_subdomains: bool = False) -> None: ...
    SAFE_METHODS: list
    """
    Class attribute listing methods that are not protected by default
    – ['GET', 'HEAD', 'OPTIONS'].
    """
    def exempt(self, f) -> Any:
        """
        Decorator that exempts a route from CSRF protection. Place it
        directly after the route decorator:

            @app.post('/webhook')
            @csrf.exempt
            async def webhook(request):
                # accepts cross-site POSTs
        """
        ...
    def initialize(self, app: Microdot, cors=None) -> Any:
        """Attach to app if construction was deferred."""
        ...
    def protect(self, f) -> Any:
        """
        Decorator that forces CSRF protection on a route that would
        otherwise be exempt (e.g. a GET route or every route when
        protect_all=False).
        """
        ...

