# Auto-generated by tools/genpyi.py -- do not edit
"""
A per-user key/value store backed by a jwt in a single
session cookie. The JWT is signed with a secret known only to the
application, so the client can read the cookie but cannot tamper with
the payload without the server detecting it.
"""

from typing import Any

def with_session(f) -> Any:
    """
    Decorator that passes the session dictionary to the route handler as
    a second argument:

        from microdot import Microdot
        from microdot.session import Session, with_session

        app = Microdot()
        Session(app, secret_key=load_secret())

        @app.get('/counter')
        @with_session
        async def counter(request, session):
            session['n'] = session.get('n', 0) + 1
            session.save()
            return {'n': session['n']}

    The decorator does not auto-save – call SessionDict.save()
    when the session was modified.
    """
    ...

class Session:
    """
    app

    The microdot.Microdot instance to install on. Optional;
    call initialize() later if not given.

    secret_key

    Symmetric key used to sign the session JWT. Required before any
    session is read or written – accessing get() without one
    raises ValueError. Store it outside source control; on a
    camera this is typically a file on the FAT filesystem.

    cookie_options

    Dict of options forwarded to
    microdot.Response.set_cookie() whenever the session cookie
    is written. Defaults set path='/' and http_only=True.
    Add secure=True for HTTPS-only deployments.
    """
    def __init__(self, app: Microdot | None = None, secret_key: bytes | str | None = None, cookie_options: dict | None = None) -> None: ...
    cookie_options: dict
    """
    The dict of options applied to the session cookie when it is
    written, forwarded to microdot.Response.set_cookie().
    Defaults set path='/' and http_only=True after
    initialize() runs.
    """
    secret_key: bytes | str | None
    """
    The signing secret used to sign and verify the session JWT.
    Settable post-construction. None until set; reading the
    session without it raises ValueError.
    """
    def decode(self, session: str, secret_key=None) -> dict:
        """
        Verify and decode a JWT-string session value. Returns {} on
        any verification failure.
        """
        ...
    def encode(self, payload: dict, secret_key=None) -> str:
        """
        Encode payload as a JWT with the session’s secret. Used
        internally; exposed for callers that want to mint compatible
        tokens.
        """
        ...
    def get(self, request) -> SessionDict:
        """
        Return the session dictionary for request. The dictionary is
        lazily decoded from the session cookie on first access and
        cached on request.g._session for the rest of the request.
        Tampered / unsignable cookies return an empty dict.
        """
        ...
    def initialize(self, app: Microdot, secret_key=None, cookie_options=None) -> Any:
        """
        Attach to app if construction was deferred. secret_key /
        cookie_options override constructor values if given.
        """
        ...

class SessionDict:
    """
    The dict-like object returned by Session.get(). Subclasses
    dict, so all standard mutations work; two extra methods commit
    the changes back into the response.
    """
    def __init__(self, request, session_dict) -> None: ...
    def delete(self) -> Any:
        """
        Remove the session by emitting a cookie-deletion header on the
        response.
        """
        ...
    def save(self) -> Any:
        """
        Write the (possibly mutated) session back into the response as a
        new session cookie. Without this call, in-place edits are
        lost when the request ends.
        """
        ...

