# Auto-generated by tools/genpyi.py -- do not edit
"""
Parses Content-Type: multipart/form-data request bodies – the
encoding browsers use for forms that include <input type="file">
fields. Two flavors of API:

- A streaming FormDataIter that yields fields one at a time –
  useful when the application has to handle very large uploads piece
  by piece on a memory-constrained device.
- A with_form_data() decorator that buffers everything and
  populates request.form /
  request.files – the convenient API
  for normal-sized uploads.
"""

from typing import Any

def with_form_data(f) -> Any:
    """
    Decorator that parses the multipart body up front and populates
    request.form and
    request.files before the handler
    runs:

        from microdot import Microdot
        from microdot.multipart import with_form_data

        app = Microdot()

        @app.post('/upload')
        @with_form_data
        async def upload(request):
            print('fields:', dict(request.form))
            for name, file in request.files.items():
                await file.save('/sdcard/' + sanitize(file.filename))
            return 'ok'

    File uploads are buffered via FileUpload.copy(), so the
    handler can iterate request.files and request.form freely.
    Temporary files are cleaned up automatically when the request
    ends.
    """
    ...

class FileUpload:
    """
    A single uploaded file. Instances are yielded by
    FormDataIter and collected into
    request.files by
    with_form_data(). Applications do not normally construct
    FileUpload directly.
    """
    def __init__(self, filename: str, content_type: str | None, read) -> None: ...
    content_type: str | None
    """
    The MIME type from the part’s Content-Type header, or
    None if not provided.
    """
    filename: str
    """
    The file’s original name as the client sent it (untrusted – do
    not pass to open() without sanitizing).
    """
    max_memory_size: int
    """
    Class attribute. Threshold (in bytes) above which
    copy() switches from in-memory buffering to a temporary
    file. Default 1024.
    """
    def close(self) -> Any:
        """
        Release any temporary file created by copy(). Called
        automatically when the request finishes if the upload reached
        request.files via with_form_data().
        """
        ...
    def copy(self, max_memory_size: int | None = None) -> Any:
        """
        Buffer the upload (either in RAM or in a temp file, depending on
        max_memory_size) so the rest of the multipart body can be
        parsed without the original stream being invalidated. The
        with_form_data() decorator calls this automatically.
        """
        ...
    def read(self, n: int = -1) -> Any:
        """Read up to n bytes from the upload stream. -1 reads to end."""
        ...
    def save(self, path_or_file) -> Any:
        """
        Save the upload to path_or_file, which can be a filesystem
        path or an already-open file object.
        """
        ...

class FormDataIter:
    """
    Async iterator over the parts of request’s multipart body.
    Yielded values are (name, value) tuples; value is a str
    for regular fields and a FileUpload for file fields.

    Used directly when memory matters more than ergonomics:

        from microdot.multipart import FormDataIter, FileUpload

        @app.post('/upload')
        async def upload(request):
            async for name, value in FormDataIter(request):
                if isinstance(value, FileUpload):
                    await value.save('/sdcard/' + value.filename)
                else:
                    print(name, '=', value)
            return 'ok'

    When iterating over file fields, the file must be consumed
    (via FileUpload.read() or FileUpload.save()) before
    the next async for iteration – the underlying stream is
    invalidated when iteration advances.
    """
    def __init__(self, request) -> None: ...
    buffer_size: int
    """
    Class attribute. Chunk size used while reading from the request
    stream. Default 256 bytes. Increase for higher throughput at the
    cost of RAM.
    """

