# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List
import machine

ACCGYRO_MODE: int
"""Accelerometer + gyroscope non-fusion mode (0x05)."""
ACCMAG_MODE: int
"""Accelerometer + magnetometer non-fusion mode (0x04)."""
ACCONLY_MODE: int
"""Accelerometer-only non-fusion mode (0x01)."""
AMG_MODE: int
"""Accelerometer + magnetometer + gyroscope non-fusion mode (0x07)."""
AXIS_P0: int
AXIS_P1: int
AXIS_P2: int
AXIS_P3: int
AXIS_P4: int
"""Default axis placement used by the constructor."""
AXIS_P5: int
AXIS_P6: int
AXIS_P7: int
COMPASS_MODE: int
"""Compass fusion mode using accelerometer + magnetometer (0x09)."""
CONFIG_MODE: int
"""
Configuration mode (0x00). The device must be in this mode to change
configuration registers.
"""
GYRONLY_MODE: int
"""Gyroscope-only non-fusion mode (0x03)."""
IMUPLUS_MODE: int
"""IMU fusion mode using accelerometer + gyroscope (0x08)."""
M4G_MODE: int
"""Magnet-for-gyroscope fusion mode (0x0A)."""
MAGGYRO_MODE: int
"""Magnetometer + gyroscope non-fusion mode (0x06)."""
MAGONLY_MODE: int
"""Magnetometer-only non-fusion mode (0x02)."""
NDOF_FMC_OFF_MODE: int
"""9-DOF fusion mode with fast magnetometer calibration disabled (0x0B)."""
NDOF_MODE: int
"""
9-DOF fusion mode with fast magnetometer calibration enabled (0x0C).
This is the default mode used by the constructor.
"""

class BNO055:
    """
    Return the gravity vector as a 3-element list [x, y, z] of floats
    in m/s^2.
    """
    def __init__(self, bus: machine.I2C, address: int = 0x28, mode: int = NDOF_MODE, axis: bytes = AXIS_P4) -> None: ...
    def accelerometer(self) -> list:
        """
        Return the accelerometer reading as a 3-element list [x, y, z] of
        floats in m/s^2.
        """
        ...
    def axis(self, placement: bytes = None) -> bytes:
        """
        Get or set the axis remap configuration. With no argument, returns the
        current 2-byte axis configuration. With a placement argument,
        writes the supplied 2-byte axis configuration. Use one of the
        AXIS_P0..``AXIS_P7`` constants below.
        """
        ...
    def euler(self) -> list:
        """
        Return the fused orientation as a 3-element list [yaw, roll, pitch]
        of floats in degrees.
        """
        ...
    def gravity(self) -> list:
        """
        Return the gravity vector as a 3-element list [x, y, z] of floats
        in m/s^2.
        """
        ...
    def gyroscope(self) -> list:
        """
        Return the gyroscope reading as a 3-element list [x, y, z] of
        floats in degrees per second.
        """
        ...
    def linear_acceleration(self) -> list:
        """
        Return the gravity-compensated linear acceleration as a 3-element list
        [x, y, z] of floats in m/s^2.
        """
        ...
    def magnetometer(self) -> list:
        """
        Return the magnetometer reading as a 3-element list [x, y, z] of
        floats in micro-Tesla.
        """
        ...
    def operation_mode(self, mode: int = None) -> int:
        """
        Get or set the operation mode register. With no argument, returns the
        current mode as an int. With a mode argument, writes the new
        mode to the device. See the operation-mode constants below.
        """
        ...
    def page(self, num: int = None) -> None:
        """
        Get or set the register page. With no argument, reads the current page
        register. With a num argument, selects the page.
        """
        ...
    def power_mode(self, mode: int = None) -> bytes:
        """
        Get or set the power mode register. With no argument, returns the
        current power-mode register contents. With a mode argument, writes
        the new power mode to the device.
        """
        ...
    def quaternion(self) -> list:
        """
        Return the fused orientation as a 4-element list [w, x, y, z] of
        floats scaled to the unit quaternion range.
        """
        ...
    def read_id(self) -> bytes:
        """
        Return the 4-byte ID block read from register 0x00. The expected
        value is b'\xA0\xFB\x32\x0F'.
        """
        ...
    def read_registers(self, register: int, size: int = 1) -> bytes:
        """
        Read size bytes from the given device register and return them as
        a bytes object.
        """
        ...
    def system_trigger(self, data: int) -> None:
        """
        Write data to the system trigger register (0x3F). This is used
        internally to issue a soft reset (0x20) and to select the external
        oscillator (0x80).
        """
        ...
    def temperature(self) -> int:
        """Return the chip temperature register value as an unsigned byte."""
        ...
    def write_registers(self, register: int, data: bytes) -> None:
        """Write the given data bytes to the device starting at register."""
        ...

