# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Callable, Iterable, Iterator

def abs(x: Any) -> Any:
    """
    Return the absolute value of a number. The argument may be an integer, a
    float, or any object implementing __abs__().
    """
    ...
def all(iterable: Iterable[Any]) -> bool:
    """
    Return True if all elements of iterable are truthy (or if the iterable
    is empty).
    """
    ...
def any(iterable: Iterable[Any]) -> bool:
    """
    Return True if any element of iterable is truthy. Returns False if
    the iterable is empty.
    """
    ...
def bin(x: int) -> str:
    """
    Convert an integer to a binary string prefixed with "0b". The argument
    must be a Python integer or implement __index__().
    """
    ...
def callable(obj: Any) -> bool:
    """Return True if obj appears callable, False otherwise."""
    ...
def chr(i: int) -> str:
    """Return a string of one character whose Unicode code point is the integer i."""
    ...
def classmethod(func: Callable[..., Any]) -> classmethod:
    """Transform a method into a class method. Typically used as a decorator."""
    ...
def compile(source: str | bytes, filename: str, mode: str) -> Any:
    """
    Compile source into a code object that can be executed by exec() or
    eval(). mode is one of "exec", "eval" or "single".
    """
    ...
def delattr(obj, name: str) -> None:
    """
    The argument name should be a string, and this function deletes the named
    attribute from the object given by obj.
    """
    ...
def dir(obj: Any = None) -> list:
    """
    Without arguments, return the list of names in the current local scope. With
    an argument, return a list of valid attributes for that object.
    """
    ...
def divmod(a: Any, b: Any) -> tuple:
    """
    Return the pair (a // b, a % b) as a tuple, for two (non-complex)
    numbers.
    """
    ...
def enumerate(iterable: Iterable[Any], start: int = 0) -> Iterator[tuple]:
    """
    Return an enumerate object yielding (index, value) pairs from iterable,
    with the index starting at start.
    """
    ...
def eval(expression: str | bytes, globals: dict | None = None, locals: dict | None = None) -> Any:
    """
    Evaluate a Python expression given as a string (or compiled code object) and
    return the result.
    """
    ...
def exec(object: str | bytes, globals: dict | None = None, locals: dict | None = None) -> None:
    """Dynamically execute Python code provided as a string or compiled code object."""
    ...
def filter(function: Callable[[Any], Any] | None, iterable: Iterable[Any]) -> Iterator[Any]:
    """
    Construct an iterator from those elements of iterable for which function
    returns true. If function is None, the identity function is assumed.
    """
    ...
def getattr(obj: Any, name: str, default: Any = None) -> Any:
    """
    Return the value of the named attribute of obj. If the attribute does not
    exist, default is returned if provided, otherwise AttributeError is
    raised.
    """
    ...
def globals() -> dict:
    """Return a dictionary representing the current module’s global symbol table."""
    ...
def hasattr(obj: Any, name: str) -> bool:
    """
    Return True if obj has an attribute with the given name, False
    otherwise.
    """
    ...
def hash(obj: Any) -> int:
    """
    Return the hash value of obj (if it has one). Hash values are integers
    used to quickly compare dictionary keys during a dictionary lookup.
    """
    ...
def hex(x: int) -> str:
    """Convert an integer to a lowercase hexadecimal string prefixed with "0x"."""
    ...
def id(obj: Any) -> int:
    """
    Return the identity of an object. This is an integer which is guaranteed to
    be unique and constant for this object during its lifetime.
    """
    ...
def input(prompt: str = '') -> str:
    """
    Read a line from standard input and return it as a string (without a trailing
    newline). If prompt is given, it is written to standard output without a
    trailing newline first.
    """
    ...
def isinstance(obj: Any, classinfo: type | tuple) -> bool:
    """
    Return True if obj is an instance of classinfo or any of its
    subclasses. classinfo may be a class or a tuple of classes.
    """
    ...
def issubclass(cls: type, classinfo: type | tuple) -> bool:
    """
    Return True if cls is a subclass (direct, indirect, or virtual) of
    classinfo.
    """
    ...
def iter(obj: Any, sentinel: Any = None) -> Iterator[Any]:
    """
    Return an iterator object. With one argument, obj must support the
    iteration protocol. With two arguments, obj must be callable and iteration
    stops when it returns sentinel.
    """
    ...
def len(obj: Any) -> int:
    """Return the number of items in a container."""
    ...
def locals() -> dict:
    """Return a dictionary representing the current local symbol table."""
    ...
def map(function: Callable[..., Any], *iterables: Iterable[Any]) -> Iterator[Any]:
    """
    Return an iterator that applies function to every item of iterables,
    yielding the results.
    """
    ...
def max(*args: Any, key: Callable[[Any], Any] | None = None, default: Any = None) -> Any:
    """
    With a single iterable argument, return its largest item. With two or more
    arguments, return the largest argument.
    """
    ...
def min(*args: Any, key: Callable[[Any], Any] | None = None, default: Any = None) -> Any:
    """
    With a single iterable argument, return its smallest item. With two or more
    arguments, return the smallest argument.
    """
    ...
def next(iterator: Iterator[Any], default: Any = None) -> Any:
    """
    Retrieve the next item from iterator. If default is given and the
    iterator is exhausted, default is returned instead of raising
    StopIteration.
    """
    ...
def oct(x: int) -> str:
    """Convert an integer to an octal string prefixed with "0o"."""
    ...
def open(file: str, mode: str = 'r', **kwargs) -> Any:
    """
    Open file and return a corresponding file object. mode defaults to
    "r" for text reading.
    """
    ...
def ord(c: str) -> int:
    """Return the Unicode code point of a single-character string c as an integer."""
    ...
def pow(base: Any, exp: Any, mod: Any | None = None) -> Any:
    """
    Return base raised to the power exp. If mod is given, return
    base ** exp % mod (computed more efficiently than the explicit form).
    """
    ...
def print(*objects: Any, sep: str = ' ', end: str = '\n', file: Any = None) -> None:
    """
    Print objects to the text stream file, separated by sep and followed
    by end.
    """
    ...
def property(fget: Callable[[Any], Any] | None = None, fset: Callable[[Any, Any], None] | None = None, fdel: Callable[[Any], None] | None = None, doc: str | None = None) -> property:
    """
    Return a property attribute. Typically used as a decorator to define managed
    attributes on a class.
    """
    ...
def range(*args: int) -> range:
    """
    Return an immutable sequence of integers. Called as range(stop),
    range(start, stop) or range(start, stop, step).
    """
    ...
def repr(obj: Any) -> str:
    """Return a string containing a printable representation of obj."""
    ...
def reversed(seq: Any) -> Iterator[Any]:
    """Return a reverse iterator over the values of the given sequence."""
    ...
def round(number: Any, ndigits: int | None = None) -> Any:
    """
    Return number rounded to ndigits decimal places. If ndigits is omitted,
    return the nearest integer.
    """
    ...
def setattr(obj: Any, name: str, value: Any) -> None:
    """
    Set the named attribute on obj to value. The counterpart of
    getattr().
    """
    ...
def sorted(iterable: Iterable[Any], key: Callable[[Any], Any] | None = None, reverse: bool = False) -> list:
    """Return a new sorted list from the items in iterable."""
    ...
def staticmethod(func: Callable[..., Any]) -> staticmethod:
    """Transform a method into a static method. Typically used as a decorator."""
    ...
def sum(iterable: Iterable[Any], start: Any = 0) -> Any:
    """
    Sum start and the items of iterable from left to right, and return the
    total.
    """
    ...
def super(type: type | None = None, obj_or_type: Any | None = None) -> Any:
    """
    Return a proxy object that delegates method calls to a parent or sibling
    class of type. Useful for accessing inherited methods that have been
    overridden in a class.
    """
    ...
def type(obj: Any) -> type:
    """
    With one argument, return the type of obj. The returned value is a type
    object.
    """
    ...
def zip(*iterables: Iterable[Any]) -> Iterator[tuple]:
    """
    Return an iterator of tuples, where the i-th tuple contains the i-th
    element from each of the argument iterables. Iteration stops when the
    shortest input iterable is exhausted.
    """
    ...

class AssertionError(Exception):
    """Raised when an assert statement fails."""
    ...
class AttributeError(Exception):
    """Raised when an attribute reference or assignment fails."""
    ...
class Exception(Exception):
    """Common base class for all non-system-exiting exceptions."""
    ...
class ImportError(Exception):
    """Raised when an import statement fails to find the module definition."""
    ...
class IndexError(Exception):
    """Raised when a sequence subscript is out of range."""
    ...
class KeyError(Exception):
    """
    Raised when a mapping (dictionary) key is not found in the set of existing
    keys.
    """
    ...
class KeyboardInterrupt(Exception):
    """
    Raised when the user interrupts program execution, usually by pressing
    Ctrl+C on the REPL.
    See also in the context of soft_bricking.
    """
    ...
class MemoryError(Exception):
    """Raised when an operation runs out of memory."""
    ...
class NameError(Exception):
    """Raised when a local or global name is not found."""
    ...
class NotImplementedError(Exception):
    """Raised when an abstract method or unimplemented feature is invoked."""
    ...
class OSError(Exception):
    """Raised when a system function returns a system-related error."""
    ...
class RuntimeError(Exception):
    """
    Raised when an error is detected that doesn’t fall in any of the other
    categories.
    """
    ...
class StopIteration(Exception):
    """
    Raised by next() and an iterator’s __next__() method to signal
    that there are no further items.
    """
    ...
class SyntaxError(Exception):
    """Raised when the parser encounters a syntax error."""
    ...
class SystemExit(Exception):
    """
    Raised by sys.exit() to request interpreter termination.  Unlike
    most exceptions, it does not produce a traceback when uncaught.
    On the OpenMV Cam, an unhandled SystemExit currently causes a
    soft_reset of MicroPython.
    """
    ...
class TypeError(Exception):
    """
    Raised when an operation or function is applied to an object of
    inappropriate type.
    """
    ...
class ValueError(Exception):
    """
    Raised when a built-in operation or function receives an argument of the
    right type but an inappropriate value.
    """
    ...
class ZeroDivisionError(Exception):
    """Raised when the second argument of a division or modulo operation is zero."""
    ...

class bool:
    """
    Return a boolean value, i.e. one of True or False. x is converted
    using the standard truth testing procedure.
    """
    def __init__(self, x: Any = False) -> None: ...

class bytearray:
    """
    Mutable sequence of integers in the range 0-255.  Construction follows
    the same rules as bytes: from an integer (creating a zero-filled
    buffer of that size), an iterable of ints, a string with encoding,
    or any buffer-protocol object.  Supports the standard sequence operations
    plus in-place modification.
    """
    def __init__(self, source: int | str | Iterable[int] | bytes = b'', encoding: str = 'utf-8', errors: str = 'strict') -> None: ...
    def append(self, val: int) -> None:
        """
        Append a single value (an integer in the range 0-255) to the end of
        the bytearray, growing it by one byte.
        """
        ...
    def center(self, width: int, fillbyte: bytes) -> bytes:
        """
        Return a copy of the contents centered in a sequence of length width,
        padded with fillbyte. Unlike CPython, fillbyte is required. The
        data is returned unchanged when width is not greater than the current
        length.
        """
        ...
    def count(self, sub: bytes, start: int = 0, end: int = -1) -> int:
        """
        Return the number of non-overlapping occurrences of sub in the slice
        [start:end].
        """
        ...
    def endswith(self, suffix: bytes, start: int = 0, end: int = -1) -> bool:
        """
        Return True if the contents end with suffix. Unlike CPython,
        suffix cannot be a tuple of values.
        """
        ...
    def extend(self, iterable: Iterable[int]) -> None:
        """
        Append all items from iterable to the end of the bytearray. As an
        extension to CPython, any object supporting the buffer protocol may be
        used.
        """
        ...
    def find(self, sub: bytes, start: int = 0, end: int = -1) -> int:
        """
        Return the lowest index where sub is found within the slice
        [start:end], or -1 if not found.
        """
        ...
    def format(self, *args: Any, **kwargs: Any) -> str:
        """
        Perform a string formatting operation using the contents as the format
        string, returning the formatted result.
        """
        ...
    def fromhex(self, string: str) -> bytearray:
        """
        Construct a bytearray from a string of hexadecimal digit
        pairs. Whitespace between digit pairs is skipped; a non-hex character
        raises ValueError.
        """
        ...
    def hex(self, sep: str = '') -> str:
        """
        Return a string of two hexadecimal digits for each byte. If the
        optional sep (a length-1 string) is given, it is inserted between
        consecutive byte values.
        """
        ...
    def index(self, sub: bytes, start: int = 0, end: int = -1) -> int:
        """Like find(), but raise ValueError when sub is not found."""
        ...
    def isalpha(self) -> bool:
        """
        Return True if all bytes are alphabetic ASCII characters and there
        is at least one byte, otherwise False.
        """
        ...
    def isdigit(self) -> bool:
        """
        Return True if all bytes are ASCII decimal digits and there is at
        least one byte, otherwise False.
        """
        ...
    def islower(self) -> bool:
        """
        Return True if all cased bytes are lowercase and there is at least
        one cased byte, otherwise False.
        """
        ...
    def isspace(self) -> bool:
        """
        Return True if all bytes are ASCII whitespace and there is at least
        one byte, otherwise False.
        """
        ...
    def isupper(self) -> bool:
        """
        Return True if all cased bytes are uppercase and there is at least
        one cased byte, otherwise False.
        """
        ...
    def join(self, iterable: Iterable[bytes]) -> bytes:
        """
        Return a bytes object which is the concatenation of the items in
        iterable, using the bytearray contents as the separator.
        """
        ...
    def lower(self) -> bytes:
        """
        Return a copy of the contents with all ASCII uppercase characters
        converted to lowercase.
        """
        ...
    def lstrip(self, chars: bytes | None = None) -> bytes:
        """
        Return a copy with leading bytes removed. chars specifies the set of
        bytes to remove; if omitted or None, ASCII whitespace is removed.
        """
        ...
    def partition(self, sep: bytes) -> tuple:
        """
        Split at the first occurrence of sep, returning (head, sep, tail).
        If sep is not found, return the contents followed by two empty
        objects.
        """
        ...
    def replace(self, old: bytes, new: bytes, count: int = -1) -> bytes:
        """
        Return a copy with all occurrences of old replaced by new. If
        count is given, only the first count occurrences are replaced.
        """
        ...
    def rfind(self, sub: bytes, start: int = 0, end: int = -1) -> int:
        """
        Return the highest index where sub is found within the slice
        [start:end], or -1 if not found.
        """
        ...
    def rindex(self, sub: bytes, start: int = 0, end: int = -1) -> int:
        """Like rfind(), but raise ValueError when sub is not found."""
        ...
    def rpartition(self, sep: bytes) -> tuple:
        """
        Split at the last occurrence of sep, returning (head, sep, tail).
        If sep is not found, return two empty objects followed by the
        contents.
        """
        ...
    def rsplit(self, sep: bytes | None = None, maxsplit: int = -1) -> list:
        """
        Split at occurrences of sep into a list of pieces, performing at most
        maxsplit splits counting from the right. If sep is None or
        omitted, split on runs of ASCII whitespace.
        """
        ...
    def rstrip(self, chars: bytes | None = None) -> bytes:
        """
        Return a copy with trailing bytes removed. chars specifies the set of
        bytes to remove; if omitted or None, ASCII whitespace is removed.
        """
        ...
    def split(self, sep: bytes | None = None, maxsplit: int = -1) -> list:
        """
        Split at occurrences of sep into a list of pieces. If sep is
        None or omitted, split on runs of ASCII whitespace and
        leading/trailing whitespace is ignored.
        """
        ...
    def splitlines(self, keepends: bool = False) -> list:
        r"""
        Return a list of the lines, breaking at \n, \r and \r\n.
        Line breaks are excluded unless keepends is true.
        """
        ...
    def startswith(self, prefix: bytes, start: int = 0, end: int = -1) -> bool:
        """
        Return True if the contents start with prefix. Unlike CPython,
        prefix cannot be a tuple, and end is accepted but ignored.
        """
        ...
    def strip(self, chars: bytes | None = None) -> bytes:
        """
        Return a copy with leading and trailing bytes removed. chars
        specifies the set of bytes to remove; if omitted or None, ASCII
        whitespace is removed.
        """
        ...
    def upper(self) -> bytes:
        """
        Return a copy of the contents with all ASCII lowercase characters
        converted to uppercase.
        """
        ...

class bytes:
    """
    Immutable sequence of integers in the range 0-255.  Created from an
    integer (zero-filled buffer), an iterable of ints, a string with
    encoding, or any buffer-protocol object.  Bytes literals use the
    b'...' syntax.
    """
    def __init__(self, source: int | str | Iterable[int] = b'', encoding: str = 'utf-8', errors: str = 'strict') -> None: ...
    def center(self, width: int, fillbyte: bytes) -> bytes:
        """
        Return a copy centered in a sequence of length width, padded with
        fillbyte (a length-1 bytes giving the pad byte). Unlike CPython,
        fillbyte is required. The original object is returned unchanged when
        width is not greater than its length.
        """
        ...
    def count(self, sub: bytes, start: int = 0, end: int = -1) -> int:
        """
        Return the number of non-overlapping occurrences of sub in the slice
        [start:end].
        """
        ...
    def decode(self, encoding: str = 'utf-8') -> str:
        """
        Return a str decoded from the bytes. In MicroPython the
        encoding argument is accepted but effectively ignored (the bytes are
        reinterpreted as UTF-8).
        """
        ...
    def endswith(self, suffix: bytes, start: int = 0, end: int = -1) -> bool:
        """
        Return True if the bytes end with suffix. Unlike CPython,
        suffix cannot be a tuple of values to try.
        """
        ...
    def find(self, sub: bytes, start: int = 0, end: int = -1) -> int:
        """
        Return the lowest index where subsequence sub is found within the
        slice [start:end], or -1 if not found.
        """
        ...
    def format(self, *args: Any, **kwargs: Any) -> str:
        """
        Perform a string formatting operation using the bytes as the format
        string, returning the formatted result.
        """
        ...
    def fromhex(self, string: str) -> bytes:
        """
        Construct a bytes object from a string of hexadecimal digit
        pairs. Whitespace between digit pairs is skipped; a non-hex character
        raises ValueError.
        """
        ...
    def hex(self, sep: str = '') -> str:
        """
        Return a string of two hexadecimal digits for each byte. If the
        optional sep (a length-1 string) is given, it is inserted between
        consecutive byte values.
        """
        ...
    def index(self, sub: bytes, start: int = 0, end: int = -1) -> int:
        """Like find(), but raise ValueError when sub is not found."""
        ...
    def isalpha(self) -> bool:
        """
        Return True if all bytes are alphabetic ASCII characters and there
        is at least one byte, otherwise False.
        """
        ...
    def isdigit(self) -> bool:
        """
        Return True if all bytes are ASCII decimal digits and there is at
        least one byte, otherwise False.
        """
        ...
    def islower(self) -> bool:
        """
        Return True if all cased bytes are lowercase and there is at least
        one cased byte, otherwise False.
        """
        ...
    def isspace(self) -> bool:
        """
        Return True if all bytes are ASCII whitespace and there is at least
        one byte, otherwise False.
        """
        ...
    def isupper(self) -> bool:
        """
        Return True if all cased bytes are uppercase and there is at least
        one cased byte, otherwise False.
        """
        ...
    def join(self, iterable: Iterable[bytes]) -> bytes:
        """
        Return a bytes object which is the concatenation of the items in
        iterable, using the bytes object itself as the separator.
        """
        ...
    def lower(self) -> bytes:
        """
        Return a copy with all ASCII uppercase characters converted to
        lowercase.
        """
        ...
    def lstrip(self, chars: bytes | None = None) -> bytes:
        """
        Return a copy with leading bytes removed. chars specifies the set of
        bytes to remove; if omitted or None, ASCII whitespace is removed.
        """
        ...
    def partition(self, sep: bytes) -> tuple:
        """
        Split at the first occurrence of sep, returning (head, sep, tail).
        If sep is not found, return the bytes followed by two empty bytes
        objects.
        """
        ...
    def replace(self, old: bytes, new: bytes, count: int = -1) -> bytes:
        """
        Return a copy with all occurrences of old replaced by new. If
        count is given, only the first count occurrences are replaced.
        """
        ...
    def rfind(self, sub: bytes, start: int = 0, end: int = -1) -> int:
        """
        Return the highest index where sub is found within the slice
        [start:end], or -1 if not found.
        """
        ...
    def rindex(self, sub: bytes, start: int = 0, end: int = -1) -> int:
        """Like rfind(), but raise ValueError when sub is not found."""
        ...
    def rpartition(self, sep: bytes) -> tuple:
        """
        Split at the last occurrence of sep, returning (head, sep, tail).
        If sep is not found, return two empty bytes objects followed by the
        bytes.
        """
        ...
    def rsplit(self, sep: bytes | None = None, maxsplit: int = -1) -> list:
        """
        Split at occurrences of sep into a list of pieces, performing at most
        maxsplit splits counting from the right. If sep is None or
        omitted, split on runs of ASCII whitespace.
        """
        ...
    def rstrip(self, chars: bytes | None = None) -> bytes:
        """
        Return a copy with trailing bytes removed. chars specifies the set of
        bytes to remove; if omitted or None, ASCII whitespace is removed.
        """
        ...
    def split(self, sep: bytes | None = None, maxsplit: int = -1) -> list:
        """
        Split at occurrences of sep into a list of pieces. If sep is
        None or omitted, split on runs of ASCII whitespace and
        leading/trailing whitespace is ignored.
        """
        ...
    def splitlines(self, keepends: bool = False) -> list:
        r"""
        Return a list of the lines, breaking at \n, \r and \r\n.
        Line breaks are excluded unless keepends is true.
        """
        ...
    def startswith(self, prefix: bytes, start: int = 0, end: int = -1) -> bool:
        """
        Return True if the bytes start with prefix. Unlike CPython,
        prefix cannot be a tuple, and end is accepted but ignored.
        """
        ...
    def strip(self, chars: bytes | None = None) -> bytes:
        """
        Return a copy with leading and trailing bytes removed. chars
        specifies the set of bytes to remove; if omitted or None, ASCII
        whitespace is removed.
        """
        ...
    def upper(self) -> bytes:
        """
        Return a copy with all ASCII lowercase characters converted to
        uppercase.
        """
        ...

class complex:
    """Create a complex number from a real and imaginary part, or from a string."""
    def __init__(self, real: float | str = 0, imag: float = 0) -> None: ...

class dict:
    """Create a new dictionary. Equivalent to CPython’s dict."""
    def __init__(self, *args, **kwargs) -> None: ...
    def __delitem__(self, key: Any) -> None:
        """
        Delete self[key]. Implements del d[key]; raises KeyError
        if key is not present.
        """
        ...
    def __getitem__(self, key: Any) -> Any:
        """
        Return self[key]. Implements the indexing operator d[key];
        raises KeyError if key is not present.
        """
        ...
    def __setitem__(self, key: Any, value: Any) -> None:
        """Set self[key] to value. Implements d[key] = value."""
        ...
    def clear(self) -> None:
        """
        Remove all items from the dictionary, leaving it empty. Raises
        TypeError if the dictionary is fixed (read-only).
        """
        ...
    def copy(self) -> dict:
        """
        Return a shallow copy of the dictionary. The returned object has the
        same type as the original (dict or OrderedDict) but is not
        fixed.
        """
        ...
    def fromkeys(self, iterable: Iterable[Any], value: Any = None) -> dict:
        """
        Create a new dictionary with keys taken from iterable, each mapped to
        value (defaulting to None). Called on the type, e.g.
        dict.fromkeys(...).
        """
        ...
    def get(self, key: Any, default: Any = None) -> Any:
        """
        Return the value for key if it is in the dictionary, otherwise return
        default (which itself defaults to None, so this never raises
        KeyError). The dictionary is not modified.
        """
        ...
    def items(self) -> Any:
        """
        Return a dynamic view object over the (key, value) pairs that
        reflects subsequent changes to the dictionary and supports iteration,
        len(), the in operator and set-comparison operators.
        """
        ...
    def keys(self) -> Any:
        """
        Return a dynamic view object over the keys that reflects subsequent
        changes to the dictionary and supports iteration, len(), the
        in operator and set-comparison operators.
        """
        ...
    def pop(self, key: Any, default: Any = None) -> Any:
        """
        Remove key from the dictionary and return its value. If key is not
        present, return default if it was supplied; otherwise raise
        KeyError. Raises TypeError if the dictionary is fixed.
        """
        ...
    def popitem(self) -> tuple:
        """
        Remove and return an arbitrary (key, value) pair as a 2-tuple. For a
        plain dict the chosen pair is unspecified; for an OrderedDict
        the last inserted pair is removed (LIFO). Raises KeyError if the
        dictionary is empty, or TypeError if it is fixed.
        """
        ...
    def setdefault(self, key: Any, default: Any = None) -> Any:
        """
        If key is in the dictionary, return its value. Otherwise insert key
        with a value of default (defaulting to None) and return that
        value. Raises TypeError if the dictionary is fixed.
        """
        ...
    def update(self, *args: Any, **kwargs: Any) -> None:
        """
        Update the dictionary in place. At most one positional argument is
        accepted: either another dictionary, or an iterable of two-element
        (key, value) pairs (each must yield exactly two items or
        ValueError is raised). Keyword arguments are then added as
        string-keyed entries. Existing keys are overwritten. Raises
        TypeError if the dictionary is fixed.
        """
        ...
    def values(self) -> Any:
        """
        Return a dynamic view object over the values that reflects subsequent
        changes to the dictionary and supports iteration and len().
        """
        ...

class float:
    """Return a floating point number constructed from a number or string x."""
    def __init__(self, x: str | bytes | int | float = 0.0) -> None: ...

class frozenset:
    """
    Return a new frozenset object, optionally with elements taken from
    iterable. frozenset is an immutable, hashable variant of set.
    """
    def __init__(self, iterable: Iterable[Any] = ()) -> None: ...
    def copy(self) -> frozenset:
        """Return a shallow copy of the frozenset."""
        ...
    def difference(self, *others: Iterable[Any]) -> frozenset:
        """
        Return a new frozenset with elements from the frozenset that are not in
        any of others. Each argument may be any iterable.
        """
        ...
    def intersection(self, other: Iterable[Any]) -> frozenset:
        """
        Return a new frozenset with elements common to the frozenset and
        other. In MicroPython only a single other argument is accepted
        (CPython accepts multiple).
        """
        ...
    def isdisjoint(self, other: Iterable[Any]) -> bool:
        """Return True if the frozenset has no elements in common with other."""
        ...
    def issubset(self, other: Iterable[Any]) -> bool:
        """Return True if every element of the frozenset is in other."""
        ...
    def issuperset(self, other: Iterable[Any]) -> bool:
        """Return True if every element of other is in the frozenset."""
        ...
    def symmetric_difference(self, other: Iterable[Any]) -> frozenset:
        """
        Return a new frozenset with elements in either the frozenset or other
        but not both. In MicroPython only a single other argument is accepted.
        """
        ...
    def union(self, other: Iterable[Any]) -> frozenset:
        """
        Return a new frozenset with elements from the frozenset and other. In
        MicroPython only a single other argument is accepted (CPython accepts
        multiple).
        """
        ...

class int:
    def __init__(self, x: str | bytes | int | float = 0, base: int = 10) -> None: ...
    def from_bytes(self, bytes: bytes, byteorder: str) -> int:
        """
        In MicroPython, byteorder parameter must be positional (this is
        compatible with CPython).
        """
        ...
    def to_bytes(self, size: int, byteorder: str) -> bytes:
        """
        In MicroPython, byteorder parameter must be positional (this is
        compatible with CPython).
        The optional signed kwarg from CPython is not supported.
        MicroPython currently converts negative integers as signed,
        and positive as unsigned. (Details.)
        """
        ...

class list:
    """Build a new list, optionally populated from items in iterable."""
    def __init__(self, iterable: Iterable[Any] = ()) -> None: ...
    def append(self, object: Any) -> None:
        """Append object to the end of the list."""
        ...
    def clear(self) -> None:
        """Remove all items from the list, leaving it empty."""
        ...
    def copy(self) -> list:
        """Return a shallow copy of the list."""
        ...
    def count(self, value: Any) -> int:
        """Return the number of elements in the list that are equal to value."""
        ...
    def extend(self, iterable: Iterable[Any]) -> None:
        """
        Append all items from iterable to the end of the list. If iterable
        is itself a list its items are copied directly; otherwise it is
        iterated over.
        """
        ...
    def index(self, value: Any, start: int = 0, stop: int = -1) -> int:
        """
        Return the index of the first element equal to value, searching the
        slice [start:stop]. Raises ValueError if value is not
        present.
        """
        ...
    def insert(self, index: int, object: Any) -> None:
        """
        Insert object before position index. A negative index is
        interpreted relative to the end of the list, and the index is clamped to
        the valid range (so values past either end insert at the start or end).
        """
        ...
    def pop(self, index: int = -1) -> Any:
        """
        Remove and return the item at index (the last item by default). Raises
        IndexError if the list is empty or index is out of range.
        """
        ...
    def remove(self, value: Any) -> None:
        """
        Remove the first element equal to value. Raises ValueError if
        value is not present.
        """
        ...
    def reverse(self) -> None:
        """Reverse the items of the list in place."""
        ...
    def sort(self, *, key: Callable[[Any], Any] | None = None, reverse: bool = False) -> None:
        """
        Sort the items of the list in place. key and reverse are
        keyword-only. key, if given, is a function applied to each element to
        produce the comparison value; reverse sorts in descending order.
        Unlike CPython, the MicroPython list sort is not stable.
        """
        ...

class memoryview:
    """
    Create a memoryview that references obj, which must support the buffer
    protocol (e.g. bytes, bytearray, array.array).  Allows zero-copy
    access and slicing of the underlying memory; slicing a memoryview returns
    another memoryview rather than a copy.
    """
    def __init__(self, obj: Any) -> None: ...

class object:
    """
    Return a new featureless object. object is the base class for all
    classes.
    """
    def __init__(self) -> None: ...

class set:
    """Return a new set object, optionally with elements taken from iterable."""
    def __init__(self, iterable: Iterable[Any] = ()) -> None: ...
    def add(self, elem: Any) -> None:
        """Add element elem to the set."""
        ...
    def clear(self) -> None:
        """Remove all elements from the set."""
        ...
    def copy(self) -> set:
        """Return a shallow copy of the set."""
        ...
    def difference(self, *others: Iterable[Any]) -> set:
        """
        Return a new set with elements from the set that are not in any of
        others. Each argument may be any iterable.
        """
        ...
    def difference_update(self, *others: Iterable[Any]) -> None:
        """Remove from the set all elements found in any of others (in place)."""
        ...
    def discard(self, elem: Any) -> None:
        """
        Remove element elem from the set if it is present. Unlike
        remove(), this does not raise an error if elem is absent.
        """
        ...
    def intersection(self, other: Iterable[Any]) -> set:
        """
        Return a new set with elements common to the set and other. In
        MicroPython only a single other argument is accepted (CPython accepts
        multiple).
        """
        ...
    def intersection_update(self, other: Iterable[Any]) -> None:
        """
        Update the set, keeping only elements also found in other (in place).
        In MicroPython only a single other argument is accepted.
        """
        ...
    def isdisjoint(self, other: Iterable[Any]) -> bool:
        """Return True if the set has no elements in common with other."""
        ...
    def issubset(self, other: Iterable[Any]) -> bool:
        """Return True if every element of the set is in other."""
        ...
    def issuperset(self, other: Iterable[Any]) -> bool:
        """Return True if every element of other is in the set."""
        ...
    def pop(self) -> Any:
        """
        Remove and return an arbitrary element from the set. Raises
        KeyError if the set is empty.
        """
        ...
    def remove(self, elem: Any) -> None:
        """
        Remove element elem from the set. Raises KeyError if elem is
        not contained in the set.
        """
        ...
    def symmetric_difference(self, other: Iterable[Any]) -> set:
        """
        Return a new set with elements in either the set or other but not
        both. In MicroPython only a single other argument is accepted.
        """
        ...
    def symmetric_difference_update(self, other: Iterable[Any]) -> None:
        """
        Update the set, keeping only elements found in either the set or other
        but not both (in place). In MicroPython only a single other argument
        is accepted.
        """
        ...
    def union(self, other: Iterable[Any]) -> set:
        """
        Return a new set with elements from the set and other. In MicroPython
        only a single other argument is accepted (CPython accepts multiple).
        """
        ...
    def update(self, *others: Iterable[Any]) -> None:
        """Update the set, adding elements from all of others (in place)."""
        ...

class slice:
    """The slice builtin is the type that slice objects have."""
    def __init__(self) -> None: ...

class str:
    """
    Return a string version of object. If object is a bytes-like object, the
    encoding and errors arguments control decoding.
    """
    def __init__(self, object: Any = '', encoding: str = 'utf-8', errors: str = 'strict') -> None: ...
    def center(self, width: int) -> str:
        """
        Return a copy of the string centered in a field of length width, padded
        with spaces. In MicroPython only a space is used as the fill character
        (there is no fill-character argument), and the original string is
        returned unchanged when width is not greater than its length.
        """
        ...
    def count(self, sub: str, start: int = 0, end: int = -1) -> int:
        """
        Return the number of non-overlapping occurrences of sub in the slice
        [start:end]. An empty sub counts each gap between characters.
        """
        ...
    def encode(self, encoding: str = 'utf-8', errors: str = 'strict') -> bytes:
        """
        Return a bytes object encoding the string. MicroPython
        effectively ignores the arguments and uses UTF-8; errors is accepted
        but not acted upon. Equivalent to bytes(s, "utf-8").
        """
        ...
    def endswith(self, suffix: str | tuple, start: int = 0, end: int = -1) -> bool:
        """
        Return True if the string ends with the given suffix, which may be
        a single string or a tuple of strings to try. Optional start and end
        restrict the comparison to the slice [start:end].
        """
        ...
    def find(self, sub: str, start: int = 0, end: int = -1) -> int:
        """
        Return the lowest index in the string where substring sub is found
        within the slice [start:end], or -1 if it is not found.
        """
        ...
    def format(self, *args: Any, **kwargs: Any) -> str:
        """
        Perform a string formatting operation, substituting replacement fields
        delimited by braces {} with values from args and kwargs. Supports
        the standard format-specification mini-language.
        """
        ...
    def index(self, sub: str, start: int = 0, end: int = -1) -> int:
        """
        Like find(), but raise ValueError when the substring sub
        is not found in the slice [start:end].
        """
        ...
    def isalpha(self) -> bool:
        """
        Return True if all characters in the string are alphabetic and the
        string is non-empty, otherwise False.
        """
        ...
    def isdigit(self) -> bool:
        """
        Return True if all characters in the string are digits and the
        string is non-empty, otherwise False.
        """
        ...
    def islower(self) -> bool:
        """
        Return True if the string contains at least one alphabetic character
        and all such characters are lowercase, otherwise False.
        """
        ...
    def isspace(self) -> bool:
        """
        Return True if all characters in the string are whitespace and the
        string is non-empty, otherwise False.
        """
        ...
    def isupper(self) -> bool:
        """
        Return True if the string contains at least one alphabetic character
        and all such characters are uppercase, otherwise False.
        """
        ...
    def join(self, iterable: Iterable[str]) -> str:
        """
        Concatenate the strings in iterable, inserting this string as the
        separator between elements. Items must be strings, otherwise
        TypeError is raised.
        """
        ...
    def lower(self) -> str:
        """Return a copy of the string with all characters converted to lowercase."""
        ...
    def lstrip(self, chars: str | None = None) -> str:
        """
        Return a copy of the string with leading characters removed. If chars
        is omitted or None, whitespace is stripped; otherwise chars is
        treated as a set of characters to remove.
        """
        ...
    def partition(self, sep: str) -> tuple:
        """
        Split the string at the first occurrence of sep and return a 3-tuple
        (head, sep, tail). If sep is not found, return (self, "", "").
        An empty sep raises ValueError.
        """
        ...
    def replace(self, old: str, new: str, count: int = -1) -> str:
        """
        Return a copy of the string with all occurrences of substring old
        replaced by new. If count is given and non-negative, only the first
        count occurrences are replaced.
        """
        ...
    def rfind(self, sub: str, start: int = 0, end: int = -1) -> int:
        """
        Return the highest index in the string where substring sub is found
        within the slice [start:end], or -1 if it is not found.
        """
        ...
    def rindex(self, sub: str, start: int = 0, end: int = -1) -> int:
        """
        Like rfind(), but raise ValueError when the substring sub
        is not found in the slice [start:end].
        """
        ...
    def rpartition(self, sep: str) -> tuple:
        """
        Split the string at the last occurrence of sep and return a 3-tuple
        (head, sep, tail). If sep is not found, return ("", "", self).
        An empty sep raises ValueError.
        """
        ...
    def rsplit(self, sep: str | None = None, maxsplit: int = -1) -> list:
        """
        Split the string from the right into a list of substrings using sep as
        the delimiter, performing at most maxsplit splits. With no maxsplit
        (or a negative one) it behaves identically to split(); in
        MicroPython rsplit(None, n) with a non-negative n raises
        NotImplementedError.
        """
        ...
    def rstrip(self, chars: str | None = None) -> str:
        """
        Return a copy of the string with trailing characters removed. If chars
        is omitted or None, whitespace is stripped; otherwise chars is
        treated as a set of characters to remove.
        """
        ...
    def split(self, sep: str | None = None, maxsplit: int = -1) -> list:
        """
        Split the string into a list of substrings using sep as the delimiter,
        performing at most maxsplit splits. If sep is omitted or None,
        split on runs of whitespace with leading whitespace ignored; otherwise
        an empty sep raises ValueError.
        """
        ...
    def splitlines(self, keepends: bool = False) -> list:
        r"""
        Return a list of the lines in the string, breaking at \n, \r and
        \r\n. Line breaks are not included unless keepends is true.
        """
        ...
    def startswith(self, prefix: str | tuple, start: int = 0, end: int = -1) -> bool:
        """
        Return True if the string starts with the given prefix, which may
        be a single string or a tuple of strings to try. Optional start and
        end restrict the comparison to the slice [start:end].
        """
        ...
    def strip(self, chars: str | None = None) -> str:
        """
        Return a copy of the string with leading and trailing characters
        removed. If chars is omitted or None, whitespace is stripped;
        otherwise chars is treated as a set of characters to remove.
        """
        ...
    def upper(self) -> str:
        """Return a copy of the string with all characters converted to uppercase."""
        ...

class tuple:
    """
    Build a new tuple, optionally populated from items in iterable. Tuples are
    immutable sequences.
    """
    def __init__(self, iterable: Iterable[Any] = ()) -> None: ...
    def count(self, value: Any) -> int:
        """Return the number of elements in the tuple that are equal to value."""
        ...
    def index(self, value: Any, start: int = 0, stop: int = -1) -> int:
        """
        Return the index of the first element equal to value, searching the
        slice [start:stop]. Raises ValueError if value is not
        present.
        """
        ...

