# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List
import machine

class DHT11:
    """
    Driver for the DHT11 sensor. Connect the sensor’s data line to pin
    (a machine.Pin). The DHT11 reports integer values with 1
    percent relative humidity and 1 degree Celsius resolution.
    """
    def __init__(self, pin: machine.Pin) -> None: ...
    def humidity(self) -> int:
        """
        Return the relative humidity from the most recent measure()
        call, as an integer percentage (0–100).
        """
        ...
    def temperature(self) -> int:
        """
        Return the temperature from the most recent measure() call,
        as an integer in degrees Celsius.
        """
        ...

class DHT22:
    """
    Driver for the DHT22 / AM2302 sensor. Connect the sensor’s data line
    to pin (a machine.Pin). The DHT22 reports values with 0.1
    percent relative humidity and 0.1 degree Celsius resolution, and
    supports negative temperatures.
    """
    def __init__(self, pin: machine.Pin) -> None: ...
    def humidity(self) -> float:
        """
        Return the relative humidity from the most recent measure()
        call, as a float percentage (0.0–100.0).
        """
        ...
    def temperature(self) -> float:
        """
        Return the temperature from the most recent measure() call,
        as a float in degrees Celsius. Negative values are supported.
        """
        ...

class DHTBase:
    """
    Base class for DHT sensors. Not normally instantiated directly — use
    DHT11 or DHT22 instead.
    """
    def __init__(self, pin: machine.Pin) -> None: ...
    def measure(self) -> None:
        """
        Trigger a measurement on the sensor and read the 5-byte response
        into the internal buffer. Raises Exception with the message
        "checksum error" if the data checksum is invalid.
        Call this method before reading temperature() or
        humidity(). The DHT sensors require at least 1 second
        (DHT11) or 2 seconds (DHT22) between consecutive measurements.
        """
        ...

