# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any

class md5:
    """Create an MD5 hasher object and optionally feed data into it."""
    def __init__(self, data: bytes = b'') -> None: ...
    def digest(self) -> bytes:
        """
        Return the hash of all data passed through it so far, as a bytes
        object. After this method is called, no more data can be fed into the
        hash.
        """
        ...
    def update(self, data: bytes) -> None:
        """Feed more binary data into the hash."""
        ...

class sha1:
    """Create an SHA1 hasher object and optionally feed data into it."""
    def __init__(self, data: bytes = b'') -> None: ...
    def digest(self) -> bytes:
        """
        Return the hash of all data passed through it so far, as a bytes
        object. After this method is called, no more data can be fed into the
        hash.
        """
        ...
    def update(self, data: bytes) -> None:
        """Feed more binary data into the hash."""
        ...

class sha256:
    """Create an SHA256 hasher object and optionally feed data into it."""
    def __init__(self, data: bytes = b'') -> None: ...
    def digest(self) -> bytes:
        """
        Return the hash of all data passed through it so far, as a bytes
        object. After this method is called, no more data can be fed into the
        hash.
        """
        ...
    def update(self, data: bytes) -> None:
        """Feed more binary data into the hash."""
        ...

