# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List
import machine

def __read_reg(addr: int) -> int:
    """Returns the value of the IMU register at addr."""
    ...
def __write_reg(addr: int, val: int) -> None:
    """Sets the IMU register at addr to val."""
    ...
def acceleration_mg() -> Tuple[float, float, float]:
    """Returns the acceleration for (x, y, z) as a float tuple in milli-g’s."""
    ...
def angular_rate_mdps() -> Tuple[float, float, float]:
    """
    Returns the angular rate for (x, y, z) as a float tuple in
    milli-degrees-per-second.
    """
    ...
def pitch() -> float:
    """
    Returns the pitch angle of the camera module in degrees.
    0 -> Camera is standing up.

    90 -> Camera is pointing down.

    180 -> Camera is upside down.

    270 -> Camera is pointing up.
    """
    ...
def roll() -> float:
    """
    Returns the roll angle of the camera module in degrees.
    0 -> Camera is standing up.

    90 -> Camera is rotated left.

    180 -> Camera is upside down.

    270 -> Camera is rotated right.
    """
    ...
def sleep(enable: bool) -> None:
    """
    enable set to True puts the IMU sensor to sleep. False wakes it
    back up (the default).
    """
    ...
def temperature_c() -> float:
    """Returns the IMU sensor temperature in degrees Celsius."""
    ...

class IMU:
    """
    Construct an IMU object bound to an I2C bus.
    bus is an initialised machine.I2C instance connected
    to the on-board IMU(s).
    On construction the bus is scanned: if a device responds at address
    0x68 a BMI270 plus BMM150 pair is instantiated (Nano 33 BLE Sense
    Rev 2), otherwise an LSM9DS1 is instantiated (Rev 1). The underlying
    driver is kept on the imu attribute and configured with default ranges
    and output data rates.
    """
    def __init__(self, bus: 'machine.I2C') -> None: ...
    def accel(self) -> tuple[float, float, float]:
        """
        Return the latest accelerometer reading as an (x, y, z) tuple in
        units of g (standard gravities).
        """
        ...
    def gyro(self) -> tuple[float, float, float]:
        """
        Return the latest gyroscope reading as an (x, y, z) tuple in
        degrees per second.
        """
        ...
    def magnet(self) -> tuple[float, float, float]:
        """
        Return the latest magnetometer reading as an (x, y, z) tuple in
        micro-tesla (uT).
        """
        ...

