# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List

def dump(obj: Any, stream: Any, separators: Tuple[str, str] | None = None) -> None:
    """
    Serialise obj to a JSON string, writing it to the given stream.
    If specified, separators should be an (item_separator, key_separator)
    tuple. The default is (', ', ': '). To get the most compact JSON
    representation, you should specify (',', ':') to eliminate whitespace.
    """
    ...
def dumps(obj: Any, separators: Tuple[str, str] | None = None) -> str:
    """
    Return obj represented as a JSON string.
    The arguments have the same meaning as in dump.
    """
    ...
def load(stream: Any) -> Any:
    """
    Parse the given stream, interpreting it as a JSON string and
    deserialising the data to a Python object.  The resulting object is
    returned.
    Parsing continues until end-of-file is encountered.
    A ValueError is raised if the data in stream is not correctly formed.
    """
    ...
def loads(str: str | bytes) -> Any:
    """
    Parse the JSON str and return an object.  Raises ValueError if the
    string is not correctly formed.
    """
    ...

