# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List
import machine

class LPS22H:
    """
    Return an estimated altitude in metres derived from the current
    pressure and temperature readings using the international barometric
    formula referenced to a sea-level pressure of 1013.25 hPa.
    """
    def __init__(self, bus: machine.I2C, address: int = 0x5C, oneshot: bool = False) -> None: ...
    def altitude(self) -> float:
        """
        Return an estimated altitude in metres derived from the current
        pressure and temperature readings using the international barometric
        formula referenced to a sea-level pressure of 1013.25 hPa.
        """
        ...
    def pressure(self) -> float:
        """
        Return the absolute atmospheric pressure in hectopascals (hPa). In
        one-shot mode this triggers a new conversion and blocks until the
        pressure data-ready flag is set.
        """
        ...
    def set_oneshot_mode(self, oneshot: bool) -> None:
        """
        Switch the device between continuous and one-shot acquisition modes
        at runtime. Updates the ODR field of CTRL_REG1 accordingly.
        """
        ...
    def temperature(self) -> float:
        """
        Return the die temperature in degrees Celsius. In one-shot mode this
        triggers a new conversion and blocks until the temperature
        data-ready flag is set.
        """
        ...

