# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List
import machine

class LSM9DS1:
    """
    Construct an LSM9DS1 instance, verify the WHO_AM_I registers of
    both sub-devices, configure all three sensors and enable the
    accel/gyro FIFO in continuous mode.
    bus

    A configured machine.I2C bus the sensor is attached to.

    address_imu

    7-bit I2C address of the accelerometer/gyroscope sub-device.
    Defaults to 0x6B.

    address_magnet

    7-bit I2C address of the magnetometer sub-device. Defaults to
    0x1E.

    gyro_odr

    Gyroscope output data rate in Hz. Must be one of 0 (off),
    14.9, 59.5, 119, 238, 476 or 952.

    gyro_scale

    Gyroscope full-scale range in degrees-per-second. Must be one of
    245, 500 or 2000.

    accel_odr

    Accelerometer output data rate in Hz. Same set of values as
    gyro_odr.

    accel_scale

    Accelerometer full-scale range in g. Must be one of 2, 4,
    8 or 16.

    magnet_odr

    Magnetometer output data rate in Hz. Must be one of 0.625,
    1.25, 2.5, 5, 10, 20, 40 or 80.

    magnet_scale

    Magnetometer full-scale range in gauss. Must be one of 4,
    8, 12 or 16.
    """
    def __init__(self, bus: machine.I2C, address_imu: int = 0x6B, address_magnet: int = 0x1E, gyro_odr: float = 952, gyro_scale: int = 245, accel_odr: float = 952, accel_scale: int = 4, magnet_odr: int = 80, magnet_scale: int = 4) -> None: ...
    def accel(self) -> tuple[float, float, float]:
        """
        Return the acceleration vector (x, y, z) in units of standard
        gravity (1 g = 9.81 m/s²).
        """
        ...
    def calibrate_magnet(self, offset: tuple[float, float, float]) -> None:
        """
        Write a hard-iron offset vector into the magnetometer’s
        OFFSET_REG_*_M registers. The offset is given in the same units
        as magnet() returns (gauss); each component is converted to
        raw LSBs using the configured magnetometer scale before being
        written.
        """
        ...
    def gyro(self) -> tuple[float, float, float]:
        """Return the gyroscope vector (x, y, z) in degrees per second."""
        ...
    def gyro_id(self) -> bytes:
        """
        Return the single-byte WHO_AM_I register value of the
        accelerometer/gyroscope sub-device.
        """
        ...
    def iter_accel_gyro(self) -> Iterator[tuple[tuple[float, float, float], tuple[float, float, float]]]:
        """
        Generator that yields (gyro, accel) tuples for every sample
        currently available in the FIFO and stops once the FIFO is empty.
        Each component vector has the same units as gyro() and
        accel() respectively.
        """
        ...
    def magent_id(self) -> bytes:
        """
        Return the single-byte WHO_AM_I register value of the
        magnetometer sub-device.
        """
        ...
    def magnet(self) -> tuple[float, float, float]:
        """Return the magnetic-field vector (x, y, z) in gauss."""
        ...

