# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List

def dumps(value: Any, /) -> bytes:
    """
    Convert the given value to binary format and return a corresponding bytes
    object.
    Currently, code objects are the only supported values that can be converted.
    """
    ...
def loads(data: bytes, /) -> Any:
    """
    Convert the given bytes-like data to its corresponding Python object, and
    return it.
    """
    ...

