# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List

class Flash:
    """
    Gets the singleton object for accessing the SPI flash memory. This class
    gives access to the on-board SPI flash memory.
    In most cases, to store persistent data on the device, you’ll want to
    use a higher-level abstraction, for example the filesystem via Python’s
    standard file API, but this interface is useful to customise the
    filesystem configuration or implement a low-level storage
    system for your application.
    """
    def __init__(self) -> None: ...
    def ioctl(self, cmd: int, arg: int) -> Optional[int]:
        """
        These methods implement the simple and extended
        block protocol defined by
        vfs.AbstractBlockDev.
        The block size can be queried by calling ioctl(5, 0). Block numbers
        are relative to the start of the user flash storage area, not the physical
        start of flash memory.
        """
        ...
    def readblocks(self, block_num: int, buf: bytearray, offset: int) -> None:
        """
        These methods implement the simple and extended
        block protocol defined by
        vfs.AbstractBlockDev.
        The block size can be queried by calling ioctl(5, 0). Block numbers
        are relative to the start of the user flash storage area, not the physical
        start of flash memory.
        """
        ...
    def writeblocks(self, block_num: int, buf: bytes, offset: int) -> None:
        """
        These methods implement the simple and extended
        block protocol defined by
        vfs.AbstractBlockDev.
        The block size can be queried by calling ioctl(5, 0). Block numbers
        are relative to the start of the user flash storage area, not the physical
        start of flash memory.
        """
        ...

