# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List

class Flash:
    """
    These methods implement the simple and extended
    block protocol defined by
    vfs.AbstractBlockDev.

    The block size can be queried by calling ioctl(5, 0). Block numbers
    are relative to the start of the user flash storage area, not the physical
    start of flash memory.
    """
    def __init__(self) -> None: ...
    def ioctl(self, cmd: int, arg: int) -> Optional[int]:
        """
        These methods implement the simple and extended
        block protocol defined by
        vfs.AbstractBlockDev.

        The block size can be queried by calling ioctl(5, 0). Block numbers
        are relative to the start of the user flash storage area, not the physical
        start of flash memory.
        """
        ...
    def readblocks(self, block_num: int, buf: bytearray, offset: int) -> None:
        """
        These methods implement the simple and extended
        block protocol defined by
        vfs.AbstractBlockDev.

        The block size can be queried by calling ioctl(5, 0). Block numbers
        are relative to the start of the user flash storage area, not the physical
        start of flash memory.
        """
        ...
    def writeblocks(self, block_num: int, buf: bytes, offset: int) -> None:
        """
        These methods implement the simple and extended
        block protocol defined by
        vfs.AbstractBlockDev.

        The block size can be queried by calling ioctl(5, 0). Block numbers
        are relative to the start of the user flash storage area, not the physical
        start of flash memory.
        """
        ...

