# Auto-generated by tools/genpyi.py -- do not edit
"""
The mutex module provides a mutual-exclusion primitive for protecting
critical sections of code or shared data from concurrent access by an interrupt
service routine and the main thread.

Lock acquisition and release is performed via a context manager (with
statement), which blocks until the mutex is available. A non-blocking
Mutex.test() method is also provided.

Example:

    from mutex import Mutex

    mtx = Mutex()

    # Acquire for a critical section (blocks if already held).
    with mtx:
        # ... protected code, e.g. shared buffer access ...
        pass

    # Or try without blocking.
    if mtx.test():
        try:
            # ... protected code ...
            pass
        finally:
            mtx.release()
"""

from typing import Any

class MutexException(Exception):
    """
    Subclass of OSError. Raised by Mutex.release when the mutex is
    already unlocked.
    """
    ...

class Mutex:
    """Creates an unlocked mutex object."""
    def __init__(self) -> None: ...
    def release(self) -> None:
        """
        Unlock the mutex. Raises mutex.MutexException if the mutex is not
        currently locked.
        """
        ...
    def test(self) -> bool:
        """
        Try to acquire the mutex in a non-blocking way. Returns True on success
        and False if the mutex is already locked.

        To acquire the mutex in a blocking way, use the instance as a context
        manager (with statement). The mutex is released automatically on exit.
        """
        ...

