# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List

class MutexException(Exception):
    """
    Subclass of OSError. Raised by Mutex.release when the mutex is
    already unlocked.
    """
    ...

class Mutex:
    """Creates an unlocked mutex object."""
    def __init__(self) -> None: ...
    def release(self) -> None:
        """
        Unlock the mutex. Raises mutex.MutexException if the mutex is not
        currently locked.
        """
        ...
    def test(self) -> bool:
        """
        Try to acquire the mutex in a non-blocking way. Returns True on success
        and False if the mutex is already locked.
        To acquire the mutex in a blocking way, use the instance as a context
        manager (with statement). The mutex is released automatically on exit.
        """
        ...

