# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List
import machine

ORDER: int
"""
Class attribute that maps the user-facing channel order to the wire
order. Defaults to (1, 0, 2, 3), i.e. user-supplied (R, G, B[, W])
tuples are transmitted as G R B [W]. Subclasses may override
ORDER to support strips with a different wire order.
"""

class NeoPixel:
    """
    Construct a NeoPixel object for a strip of LEDs connected to pin.
    pin is a machine.Pin instance; it will be
    reconfigured as an output by the constructor.

    n is the number of LEDs in the strip.

    bpp is the number of bytes per pixel: 3 for RGB LEDs (such as
    WS2812) and 4 for RGBW LEDs (such as SK6812-RGBW).

    timing selects the bit timing. 0 selects the slow 400 kHz
    timing, 1 selects the standard 800 kHz timing used by most
    modern strips. A 4-tuple (high_0, low_0, high_1, low_1) of
    nanosecond durations may be passed instead, in the form accepted by
    machine.bitstream().
    """
    def __init__(self, pin: 'machine.Pin', n: int, bpp: int = 3, timing: int | tuple[int, int, int, int] = 1) -> None: ...
    def __getitem__(self, index: int) -> tuple[int, ...]:
        """
        Return the pixel at index from the local buffer as an RGB or RGBW
        tuple in the user-facing channel order.
        """
        ...
    def __len__(self) -> int:
        """Return the number of LEDs in the strip."""
        ...
    def __setitem__(self, index: int, val: tuple[int, ...]) -> None:
        """
        Set the pixel at index to val, an RGB or RGBW tuple. The data is
        only buffered; call write() to push it to the strip.
        """
        ...
    def fill(self, pixel: tuple[int, ...]) -> None:
        """
        Set every pixel in the strip to pixel, an RGB or RGBW tuple of
        integers in the range 0-255.
        """
        ...
    def write(self) -> None:
        """
        Transmit the buffered pixel data to the strip using
        machine.bitstream().
        """
        ...

