# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List
import machine

MATCH_ROM: int
"""
Match ROM command (0x55). Used internally by select_rom() to
address a specific device by its 64-bit ROM code.
"""
SEARCH_ROM: int
"""
Search ROM command (0xF0). Used internally by scan() to
discover devices on the bus.
"""
SKIP_ROM: int
"""
Skip ROM command (0xCC). Addresses all devices on the bus
simultaneously, skipping ROM matching.
"""

class OneWireError(Exception):
    """
    Raised when a 1-Wire operation fails. Currently raised by
    OneWire.reset() when required is True and no slave responds
    to the reset pulse.
    """
    ...

class OneWire:
    """
    Construct a 1-Wire bus master on the given machine.Pin. The
    pin is automatically configured as open-drain with a pull-up.
    ROM command constants:
    """
    def __init__(self, pin: machine.Pin) -> None: ...
    def crc8(self, data: bytes | bytearray) -> int:
        """
        Compute the Maxim/Dallas 8-bit CRC over data. The result is 0
        when data already includes a valid trailing CRC byte, which can be
        used to validate received scratchpad contents.
        """
        ...
    def readbit(self) -> int:
        """Read a single bit from the bus and return it as 0 or 1."""
        ...
    def readbyte(self) -> int:
        """
        Read a single byte from the bus and return it as an integer
        (0–255).
        """
        ...
    def readinto(self, buf: bytearray) -> None:
        """
        Read len(buf) bytes from the bus into the given pre-allocated
        buffer.
        """
        ...
    def reset(self, required: bool = False) -> bool:
        """
        Issue a reset pulse on the bus. Returns True if at least one slave
        device responded with a presence pulse, otherwise False. If
        required is True and no device responds, raises OneWireError.
        """
        ...
    def scan(self) -> list[bytearray]:
        """
        Search the bus and return a list of 8-byte ROM codes (one
        bytearray per detected device). Returns an empty list if no
        devices are present.
        """
        ...
    def select_rom(self, rom: bytes | bytearray) -> None:
        """
        Issue a reset followed by a MATCH ROM command to address the device
        whose 64-bit ROM code is in rom (an 8-byte buffer).
        """
        ...
    def write(self, buf: bytes | bytearray) -> None:
        """Write the bytes in buf to the bus."""
        ...
    def writebit(self, value: int) -> None:
        """Write a single bit (0 or 1) to the bus."""
        ...
    def writebyte(self, value: int) -> None:
        """Write a single byte (0–255) to the bus."""
        ...

