# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List

class PID:
    """
    Reset the integrator state. Clears the accumulated integral term to
    zero and clears the cached derivative value (set to NaN) so that
    the next call to PID.get_pid() re-initialises the derivative
    filter.
    """
    def __init__(self, p: float = 0, i: float = 0, d: float = 0, imax: float = 0) -> None: ...
    def get_pid(self, error: float, scaler: float) -> float:
        """
        Compute and return the PID controller output for the given error.

        error is the current error (typically target - measurement).

        scaler is a multiplicative scale factor applied to the
        proportional + derivative sum and to the integrator increment.

        The time delta between successive calls is measured internally using
        time.ticks_ms(). If more than 1000 ms elapse between calls (or on
        the first call), the integrator is reset via PID.reset_I() and
        the time delta is treated as zero for that step.

        Returns the PID output as a float.
        """
        ...
    def reset_I(self) -> None:
        """
        Reset the integrator state. Clears the accumulated integral term to
        zero and clears the cached derivative value (set to NaN) so that
        the next call to PID.get_pid() re-initialises the derivative
        filter.
        """
        ...

