# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any

def choice(sequence: Any) -> Any:
    """
    Chooses and returns one item at random from sequence (tuple, list or
    any object that supports the subscript operation).
    """
    ...
def getrandbits(n: int) -> int:
    """Return an integer with n random bits (0 <= n <= 32)."""
    ...
def randint(a: int, b: int) -> int:
    """Return a random integer in the range [a, b]."""
    ...
def random() -> float:
    """Return a random floating point number in the range [0.0, 1.0)."""
    ...
def randrange(start: int, stop: int | None = None, step: int = 1) -> int:
    """
    The first form returns a random integer from the range [0, stop).
    The second form returns a random integer from the range [start, stop).
    The third form returns a random integer from the range [start, stop) in
    steps of step.  For instance, calling randrange(1, 10, 2) will
    return odd numbers between 1 and 9 inclusive.
    """
    ...
def seed(n: int | None = None, /) -> None:
    """
    Initialise the random number generator module with the seed n,
    which should be an integer. When no argument (or None) is
    passed in, the PRNG is re-seeded from the same port-specific
    source os.urandom() uses.
    """
    ...
def uniform(a: float, b: float) -> float:
    """
    Return a random floating point number N such that a <= N <= b for a <= b,
    and b <= N <= a for b < a.
    """
    ...

