# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List

class SenmlBase:
    """
    Common base class shared by SenmlPack and SenmlRecord. It exposes no
    public API of its own; it exists so SenmlPack.add() can validate
    that an item belongs to the SenML hierarchy.
    """
    def __init__(self) -> None: ...

class SenmlPack:
    """
    Represents a SenML pack – a collection of SenmlRecord instances and
    optionally other child SenmlPack objects. When a pack only
    contains records it represents a single device; when it contains other
    packs it acts as a gateway.
    name is the SenML base name (bn) used for every record contained in
    this pack.
    callback is invoked from from_json / from_cbor whenever an inbound
    record names a previously-unknown sensor; the new SenmlRecord is passed
    as the first argument and (for nested packs) the originating device pack
    is passed as device=.... It is typically used to handle actuator
    commands.
    SenmlPack instances are iterable – iteration yields each record
    in insertion order – and may be used as a context manager so that on
    exit the pack removes itself from its parent.
    """
    def __init__(self, name: str, callback=None) -> None: ...
    actuate: Any
    """
    The callback supplied at construction time. May be re-assigned at
    runtime.
    """
    base_sum: Any
    """Optional base sum (bs) added to each record’s sum field."""
    base_time: Any
    """Optional base time (bt) added to each record’s timestamp."""
    base_unit: Any
    """Optional base unit (bu) – typically a value from SenmlUnits."""
    base_value: Any
    """
    Optional base value (bv) added to each record’s numeric value when
    encoding and subtracted on decoding. Setting a non-numeric value
    raises Exception.
    """
    name: Any
    """The pack’s base name (bn)."""
    def add(self, item: SenmlRecord | SenmlPack) -> None:
        """
        Append item to this pack. item must be a SenmlRecord or another
        SenmlPack and must not already belong to a different parent;
        otherwise Exception is raised.
        """
        ...
    def clear(self) -> None:
        """
        Remove every record/sub-pack from this pack and detach them from
        their parent reference.
        """
        ...
    def do_actuate(self, raw: dict, naming_map: dict, device: SenmlPack | None = None) -> None:
        """
        Internal helper invoked while parsing inbound data when no existing
        record matches an entry. Adds a new SenmlRecord to device (or to
        this pack) and forwards it to the callback.
        """
        ...
    def from_cbor(self, data: bytes) -> None:
        """Parse a SenML/CBOR byte string and merge the records into this pack."""
        ...
    def from_json(self, data: str) -> None:
        """
        Parse a SenML/JSON document and merge the records into this pack.
        Records that already exist (matched by name) trigger
        SenmlRecord.do_actuate(); new records are appended and the
        pack-level callback is invoked.
        """
        ...
    def remove(self, item: SenmlRecord | SenmlPack) -> None:
        """
        Remove item from this pack. Exception is raised if item is
        not a child of this pack.
        """
        ...
    def to_cbor(self) -> bytes:
        """Render the pack and its children to a SenML/CBOR byte string."""
        ...
    def to_json(self) -> str:
        """Render the pack and its children to a SenML/JSON string."""
        ...

class SenmlRecord:
    """
    Represents a single measurement inside a SenmlPack.
    name is the SenML record name (n).
    The following keyword arguments are accepted:
    value – bool, int, float, str or bytearray.
    Other types raise Exception.

    time – numeric timestamp (t).

    unit – a unit string, typically a member of SenmlUnits.

    sum – numeric integrated sum (s).

    update_time – maximum time before the sensor will provide a fresh
    reading (ut).

    callback – function invoked when an inbound payload updates this
    record. It receives the SenmlRecord as its only argument.
    SenmlRecord may be used as a context manager so that on exit it
    removes itself from its parent pack.
    """
    def __init__(self, name: str, **kwargs) -> None: ...
    actuate: Any
    """
    The callback supplied at construction time. May be re-assigned at
    runtime.
    """
    name: Any
    """Record name (n)."""
    sum: Any
    """Integrated sum field (s)."""
    time: Any
    """Timestamp associated with this measurement (t)."""
    unit: Any
    """Unit string (u)."""
    update_time: Any
    """
    Maximum time before the sensor will provide an updated reading
    (ut).
    """
    value: Any
    """
    The current value. Re-assigning checks the type; only bool,
    numbers, str and bytearray are accepted. To control the
    rendered precision of a float value, round before assignment, e.g.
    record.value = round(x, 2).
    """
    def do_actuate(self, raw: dict, naming_map: dict) -> None:
        """
        Update this record from a raw inbound SenML dictionary and, if
        present, invoke the actuate callback.
        """
        ...

class SenmlUnits:
    """
    Enumeration object whose attributes are the SenML unit symbols defined by
    RFC 8428. Each
    attribute resolves to the unit’s string code, suitable for assignment to
    SenmlRecord.unit or SenmlPack.base_unit.
    Examples of available unit attributes:
    SENML_UNIT_METER -> "m"

    SENML_UNIT_KILOGRAM -> "kg"

    SENML_UNIT_SECOND -> "s"

    SENML_UNIT_AMPERE -> "A"

    SENML_UNIT_KELVIN -> "K"

    SENML_UNIT_DEGREES_CELSIUS -> "Cel"

    SENML_UNIT_HERTZ -> "Hz"

    SENML_UNIT_VOLT -> "V"

    SENML_UNIT_WATT -> "W"

    SENML_UNIT_PASCAL -> "Pa"

    SENML_UNIT_LUX -> "lx"

    SENML_UNIT_RELATIVE_HUMIDITY -> "%RH"

    SENML_UNIT_VELOCITY -> "m/s"

    SENML_UNIT_ACCELERATION -> "m/s2"

    SENML_UNIT_DEGREES_LATITUDE -> "lat"

    SENML_UNIT_DEGREES_LONGITUDE -> "lon"

    SENML_UNIT_BIT_PER_SECOND -> "bit/s"

    SENML_UNIT_COUNTER -> "count"

    SENML_UNIT_RATIO -> "//"

    SENML_UNIT_BPM -> "beat/min"
    See the SenML unit registry in
    RFC 8428 Section 12.1
    for the complete list.
    """
    def __init__(self) -> None: ...

