# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any

GPIOA: int
"""Base address of the GPIOA peripheral."""
GPIOB: int
"""Base address of the GPIOB peripheral."""
GPIO_BSRR: int
"""Offset of the GPIO bit set/reset register."""
GPIO_IDR: int
"""Offset of the GPIO input data register."""
GPIO_ODR: int
"""Offset of the GPIO output data register."""
mem16: int
"""
Subscriptable 16-bit (halfword) memory accessor. mem16[addr] reads an
int in the range 0-65535; mem16[addr] = value writes the low 16
bits. addr must be aligned to 2 bytes.
"""
mem32: int
"""
Subscriptable 32-bit (word) memory accessor. mem32[addr] reads an
int in the range 0-0xFFFFFFFF; mem32[addr] = value writes the low
32 bits. addr must be aligned to 4 bytes.
"""
mem8: int
"""
Subscriptable 8-bit memory accessor. mem8[addr] reads an int in the
range 0-255 from the byte at addr; mem8[addr] = value writes the
low 8 bits of value. addr may be any byte-aligned address.
"""

