# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List

class TFP410:
    """
    Initializes the TFP410 DVI/HDMI controller chip.
    i2c_addr is the I2C address of the TFP410.
    """
    def __init__(self, *, i2c_addr: int = 0x3F) -> None: ...
    def hotplug_callback(self, callback: Callable[[bool], None] | None) -> None:
        """
        Registers a callback function that will be called whenever the connection
        state of an external display changes. The new connection state (bool) is
        passed as the only argument to callback.
        Pass None as callback to disable the hotplug callback.
        While a callback is registered, do not call TFP410.isconnected().
        """
        ...
    def isconnected(self) -> bool:
        """Returns True if an external display is connected, False otherwise."""
        ...

