# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List

__sha__: int
"""
Git hash of the ulab source the firmware was built from. Only
present when the firmware was built with hash information embedded.
"""
__version__: int
"""
Version string of the ulab build, including the maximum
supported number of array dimensions, e.g. "6.7.3-2D".
"""

class dtype:
    """
    Data-type descriptor for an ndarray. A dtype instance carries
    one of the type codes 'b' (bool), 'B' (uint8), 'b'
    (int8), 'H' (uint16), 'h' (int16), 'f' / 'd' (float)
    or 'D' (complex), and is what is returned by the
    ndarray.dtype property.

    The constructor accepts either a single-character type code, one of
    the integer constants exposed by numpy (numpy.uint8,
    numpy.int8, numpy.uint16, numpy.int16, numpy.float,
    numpy.bool, and – if the firmware was built with complex
    support – numpy.complex), or another dtype instance.

    When the firmware is built with ULAB_HAS_DTYPE_OBJECT disabled,
    ndarray.dtype returns the underlying type-code integer
    directly instead of a dtype object, and this class is not
    available.
    """
    def __init__(self, t: int | str | None = None) -> None: ...

