# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any

__sha__: str
"""
Git hash of the ulab source the firmware was built from. Only
present when the firmware was built with hash information embedded.
"""
__version__: str
"""
Version string of the ulab build, including the maximum
supported number of array dimensions, e.g. "6.7.3-2D".
"""

