# Auto-generated by tools/genpyi.py -- do not edit
"""
The framebuf module provides a small, allocation-free pixel
buffer with primitive drawing operations. It is intended for driving
external displays (OLEDs, LCDs, e-paper, etc.).
"""

from typing import Any


def FrameBuffer1(buffer: Any, width: int, height: int, stride: int | None = None, /) -> FrameBuffer:
    """
    Deprecated shortcut for FrameBuffer(buffer, width, height,
    framebuf.MONO_VLSB, stride). Retained for backwards compatibility;
    use the full FrameBuffer constructor instead.
    """
    ...


class FrameBuffer:
    """
    Construct a FrameBuffer object.

    - buffer – any object supporting the buffer protocol; must be
      large enough to hold stride * height pixels at the chosen
      format.
    - width – width of the frame buffer in pixels.
    - height – height of the frame buffer in pixels.
    - format – pixel format; one of the constants listed under
      framebuf-constants below. The format determines both the
      size of each pixel in buffer and how a colour integer c
      passed to any drawing method is interpreted.
    - stride – number of pixels per horizontal row, including any
      padding. Defaults to width. Set this to use a sub-region of a
      larger buffer.

    Passing a buffer that is too small, or invalid dimensions, will
    produce undefined results – the constructor does not validate every
    combination.
    """
    def __init__(self, buffer: Any, width: int, height: int, format: int, stride: int | None = None, /) -> None: ...

    def blit(self, fbuf: FrameBuffer | tuple, x: int, y: int, key: int = -1, palette: FrameBuffer | None = None) -> None:
        """
        Draw another frame buffer fbuf on top of this one with its
        top-left corner at (x, y).

        If key is given, any source pixel matching that colour value
        is treated as transparent and not drawn. When a palette is
        provided, the comparison is made against the palette output, not
        the raw fbuf value.

        fbuf can be a FrameBuffer instance or a tuple/list
        matching the constructor signature:

            (buffer, width, height, format)
            (buffer, width, height, format, stride)

        When the source is a tuple/list, buffer may be read-only.

        palette allows blitting between buffers of different formats –
        for example, rendering a monochrome glyph into an RGB565 buffer. It
        is a FrameBuffer whose format matches the destination, with
        height 1 and width equal to the number of source colours (2**N
        for an N-bit-per-pixel source). Source pixel value i is replaced
        with the colour at palette[i, 0] before drawing.
        """
        ...

    def ellipse(self, x: int, y: int, xr: int, yr: int, c: int, f: bool = False, m: int = 0) -> None:
        """
        Draw an ellipse centred on (x, y) with x-radius xr and
        y-radius yr in colour c. Equal radii produce a circle.
        f=True fills the shape instead of just outlining it.

        m is a bitmask that restricts drawing to specific quadrants
        (numbered counter-clockwise from the top-right):

        Bit

        Quadrant

        Region

        bit 0

        Q1

        Top-right

        bit 1

        Q2

        Top-left

        bit 2

        Q3

        Bottom-left

        bit 3

        Q4

        Bottom-right

        The default m=0 draws all four quadrants.
        """
        ...

    def fill(self, c: int) -> None:
        """Fill the entire frame buffer with colour c."""
        ...

    def fill_rect(self, x: int, y: int, w: int, h: int, c: int) -> None:
        """
        Fill a w x h rectangle at (x, y) with colour c.
        Equivalent to rect() with f=True.
        """
        ...

    def hline(self, x: int, y: int, w: int, c: int) -> None:
        """
        Draw a 1-pixel-thick line in colour c. hline() and
        vline() draw a horizontal/vertical line of the given length;
        line() draws a line between two arbitrary points.
        """
        ...

    def line(self, x1: int, y1: int, x2: int, y2: int, c: int) -> None:
        """
        Draw a 1-pixel-thick line in colour c. hline() and
        vline() draw a horizontal/vertical line of the given length;
        line() draws a line between two arbitrary points.
        """
        ...

    def pixel(self, x: int, y: int, c: int | None = None) -> int | None:
        """
        With no c argument, return the colour value of the pixel at
        (x, y). With c given, set that pixel to colour c.
        """
        ...

    def poly(self, x: int, y: int, coords: Any, c: int, f: bool = False) -> None:
        """
        Draw an arbitrary closed polygon (convex or concave) at offset
        (x, y) in colour c. coords must be an array of
        signed 16-bit integers laid out as
        array('h', [x0, y0, x1, y1, ..., xn, yn]). f=True fills the
        polygon instead of just outlining it.
        """
        ...

    def rect(self, x: int, y: int, w: int, h: int, c: int, f: bool = False) -> None:
        """
        Draw a rectangle at (x, y) of size w x h in colour c.
        If f is True the rectangle is filled; otherwise only a 1-pixel
        outline is drawn.
        """
        ...

    def scroll(self, xstep: int, ystep: int) -> None:
        """
        Shift the buffer contents by (xstep, ystep). Pixels shifted in
        from outside the buffer are not cleared, so a “ghost” of the
        previous contents may remain at the trailing edge.
        """
        ...

    def text(self, s: str, x: int, y: int, c: int = 1) -> None:
        """
        Draw the string s with its top-left corner at (x, y) in
        colour c. The built-in font is fixed at 8x8 pixels and cannot
        be changed. c defaults to 1.
        """
        ...

    def vline(self, x: int, y: int, h: int, c: int) -> None:
        """
        Draw a 1-pixel-thick line in colour c. hline() and
        vline() draw a horizontal/vertical line of the given length;
        line() draws a line between two arbitrary points.
        """
        ...
