# Auto-generated by tools/genpyi.py -- do not edit
"""
The protocol module exposes the OpenMV host protocol to Python. It allows
the firmware-side protocol stack to be initialized and configured, and lets
user code register custom logical channels backed by a Python object that
implements the channel interface (read, write, size, poll,
etc.). This is what desktop companion tools talk to when they stream image
data or expose interactive widgets to a connected camera.
"""

from typing import Any, Callable

CHANNEL_FLAG_LOCK: int
"""The channel implements lock/unlock."""
CHANNEL_FLAG_PHYSICAL: int
"""
The channel represents a physical transport (as opposed to a logical
data channel).
"""
CHANNEL_FLAG_READ: int
"""The channel supports reads."""
CHANNEL_FLAG_WRITE: int
"""The channel supports writes."""
CHANNEL_ID_PROFILE: int
"""
Channel ID of the built-in profiler channel (only present when the
firmware is built with the profiler enabled).
"""
CHANNEL_ID_STDIN: int
"""Channel ID of the built-in stdin channel."""
CHANNEL_ID_STDOUT: int
"""Channel ID of the built-in stdout channel."""
CHANNEL_ID_STREAM: int
"""Channel ID of the built-in stream channel."""
CHANNEL_ID_TRANSPORT: int
"""Reserved channel ID for the active transport."""

def init(crc: bool = True, seq: bool = True, ack: bool = True, events: bool = True, max_payload: int = ..., rtx_retries: int = 3, rtx_timeout_ms: int = 500, lock_interval_ms: int = 10, poll_ms: int = 0) -> None:
    """
    Initialize (or reconfigure) the protocol stack and register the default
    logical data channels (stdin, stdout, stream and, if compiled
    in, profile). Raises RuntimeError if initialization fails. The
    firmware boots with a default USB protocol stack already running, so
    calling this is needed only to change the transport or override the
    default framing parameters.

    crc enables CRC validation on protocol frames.

    seq enables sequence number tracking.

    ack enables per-frame acknowledgements.

    events enables channel event notifications.

    max_payload is the maximum payload size in bytes. If omitted the
    per-camera default below is used; it is derived from each board’s
    protocol buffer size as buffer - 10 (header) - 4 (CRC).

    Camera

    Buffer size

    Max payload

    OpenMV Cam M4 (OPENMV2)

    512

    498

    OpenMV Cam M7 (OPENMV3)

    512

    498

    OpenMV Cam H7 (OPENMV4)

    512

    498

    OpenMV Cam H7 Plus (OPENMV4P)

    4096

    4082

    OpenMV Pure Thermal (OPENMVPT)

    4096

    4082

    OpenMV Cam RT1062 (OPENMV_RT1060)

    4096

    4082

    OpenMV Cam N6 (OPENMV_N6)

    8192

    8178

    OpenMV AE3 (OPENMV_AE3)

    8192

    8178

    Arduino Portenta H7 (ARDUINO_PORTENTA_H7)

    4096

    4082

    Arduino Giga (ARDUINO_GIGA)

    4096

    4082

    Arduino Nicla Vision (ARDUINO_NICLA_VISION)

    4096

    4082

    rtx_retries is the number of retransmission attempts. Default 3.

    rtx_timeout_ms is the retransmission timeout in milliseconds (doubled
    after each timeout). Default 500.

    lock_interval_ms is the minimum lock interval in milliseconds.
    Default 10.

    poll_ms is the polling interval in milliseconds. 0 (the default)
    disables timer polling.
    """
    ...
def is_active() -> bool:
    """
    Return True if a host is currently connected and the protocol stack
    is active, otherwise False.
    """
    ...
def register(name: str, *, backend: object, flags: int = 0) -> ProtocolChannel:
    """
    Register a Python backend object as a new logical channel and return
    a ProtocolChannel handle. The backend object’s available methods
    (see protocol-backend-interface below) determine the channel’s
    capabilities; protocol.CHANNEL_FLAG_READ, protocol.CHANNEL_FLAG_WRITE
    and protocol.CHANNEL_FLAG_LOCK are added to flags automatically
    when the corresponding methods are implemented.

    name is the channel name as a string. Truncated to the firmware’s
    channel-name buffer size. Required.

    backend is the Python object implementing the backend interface.
    Required. Typically passed by keyword (backend=...).

    flags is additional channel flag bits (see the CHANNEL_FLAG_*
    constants). Optional; defaults to 0.

    Raises RuntimeError if the channel cannot be registered (e.g. no
    free channel slots).
    """
    ...

class CBORChannel:
    """
    A higher-level Python backend (provided by the frozen protocol
    package) that serializes named fields to CBOR using SenML-compatible
    integer keys. Supports display widgets (label, depth) and
    interactive controls (toggle, slider, select) with
    on_read/on_write callbacks.

    on_read is an optional callable on_read(channel) invoked before
    the channel is serialized for the host. Use it to refresh field values.

    on_write is an optional callable on_write(channel, name, value)
    invoked when the host writes a new value for a named field.
    """
    def __init__(self, on_read: Callable | None = None, on_write: Callable | None = None) -> None: ...
    def __getitem__(self, name: str) -> object:
        """
        Return the current value of the named field. For depth fields
        the binary data buffer is returned, otherwise the scalar value.
        """
        ...
    def __setitem__(self, name: str, value: Any) -> None:
        """
        Set the value of the named field. For slider fields, a
        (min, max, value) tuple updates the range and current value
        simultaneously. For depth fields, value is the binary data
        buffer.
        """
        ...
    def add(self, name: str, type: str, value: Any = None, unit: str | None = None, min: int | float | None = None, max: int | float | None = None, step: int | float | None = None, options: list | None = None, width: int | None = None, height: int | None = None) -> None:
        """
        Add a named field to the channel.

        name is the display name; must be unique within this channel.

        type is the widget type: "label", "toggle", "slider",
        "select", or "depth".

        value is the initial value. The default depends on type.

        unit is the unit string for label/slider (e.g. "Cel",
        "%RH").

        min is the minimum value (slider range or depth range).

        max is the maximum value (slider range or depth range).

        step is the step size (slider).

        options is the list of option strings (select).

        width is the pixel width (depth).

        height is the pixel height (depth).
        """
        ...
    def poll(self) -> bool:
        """
        Backend interface method. Returns True when serialized data is
        available for the host.
        """
        ...
    def read(self, offset: int, size: int) -> bytes:
        """Backend interface method. Returns a slice of the serialized buffer."""
        ...
    def size(self) -> int:
        """
        Backend interface method. Invokes on_read (if set) and returns
        the size of the serialized buffer.
        """
        ...
    def write(self, offset: int, data: bytearray) -> int:
        """
        Backend interface method. Decodes a CBOR update list and applies
        values to matching named fields, invoking on_write for each.
        """
        ...

class ProtocolChannel:
    """
    Handle returned by protocol.register. Instances are not constructed
    directly.
    """
    def __init__(self) -> None: ...
    def send_event(self, event: int, wait_ack: bool = False) -> None:
        """
        Send a channel event notification to the host.

        event is the event identifier (integer).

        wait_ack if True blocks until the host acknowledges the event.

        Raises RuntimeError if sending the event fails.
        """
        ...

class backend:
    """
    Channel backend object passed to protocol.register. The methods below
    describe the optional interface a Python backend may implement.
    """
    def __init__(self) -> None: ...
    def flush(self) -> object:
        """Flush any pending data. Return any non-None value on success."""
        ...
    def init(self) -> object:
        """
        Called once when the channel is initialized. Return any non-None
        value on success; an exception or missing return is treated as an error.
        """
        ...
    def ioctl(self, cmd: int, length: int, arg: bytearray | None) -> int:
        """
        Handle an ioctl. arg is None if length is zero, otherwise a
        bytearray referencing the C buffer. Return 0 or None on
        success, or a negative integer on error.
        """
        ...
    def is_active(self) -> bool:
        """
        For transport channels, return True if the underlying transport is
        currently connected.
        """
        ...
    def lock(self) -> bool:
        """Acquire the channel for a transfer. Return True on success."""
        ...
    def poll(self) -> bool:
        """Return True if the channel has data ready to be read by the host."""
        ...
    def read(self, offset: int, size: int) -> bytes:
        """
        Return up to size bytes starting at offset as a bytes-like
        object that supports the buffer protocol.
        """
        ...
    def readp(self, offset: int, size: int) -> bytes:
        """
        Zero-copy variant of read. Returns a buffer whose underlying memory
        is read directly by the protocol layer; the buffer must remain valid
        for the duration of the transfer.
        """
        ...
    def shape(self) -> tuple:
        """
        Return a tuple of up to four integers describing the data shape (e.g.
        image dimensions). Up to four elements are consumed by the protocol
        layer.
        """
        ...
    def size(self) -> int:
        """Return the number of bytes currently readable from the channel."""
        ...
    def unlock(self) -> bool:
        """Release the channel after a transfer. Return True on success."""
        ...
    def write(self, offset: int, data: bytearray) -> int:
        """
        Write data at offset. data is a bytearray referencing
        the C buffer directly. Return the number of bytes written, or 0 on
        default success.
        """
        ...

