# Auto-generated by tools/genpyi.py -- do not edit
"""
This module provides functionality specific to STM32 microcontrollers, including
direct access to peripheral registers.
"""

from typing import Any

ADC1: int
"""
Base address of ADC1. ADC2 / ADC3 appear on MCUs with
multiple ADC blocks.
"""
DAC: int
"""Base address of the DAC peripheral, on MCUs that have one."""
DMA1: int
"""
Base address of DMA1. DMA2 is present on most STM32s; H7-class
parts also expose BDMA, MDMA and (on the N6) HPDMA /
GPDMA.
"""
EXTI: int
"""Base address of the External Interrupt / Event Controller."""
FLASH: int
"""
Base address of the embedded flash controller (the peripheral, not
the flash array itself).
"""
GPIOA: int
"""
Base address of the GPIOA peripheral. GPIOB … GPIOK (range
depends on the MCU package) follow the same pattern.
"""
GPIO_BSRR: int
"""Offset of the GPIO bit set/reset register within any GPIOx base."""
GPIO_IDR: int
"""Offset of the GPIO input data register."""
GPIO_ODR: int
"""Offset of the GPIO output data register."""
I2C1: int
"""Base address of the I2C1 peripheral. I2C2 … I2C4 follow."""
PWR: int
"""Base address of the Power Control peripheral."""
RCC: int
"""Base address of the Reset and Clock Control peripheral."""
RCC_CFGR: int
"""Offset of the RCC clock configuration register."""
RCC_CR: int
"""Offset of the RCC clock control register."""
SPI1: int
"""
Base address of the SPI1 peripheral. Additional SPI instances appear
as SPI2, SPI3, … up to the MCU’s count.
"""
SYSCFG: int
"""Base address of the System Configuration Controller."""
TIM1: int
"""
Base address of the TIM1 advanced-control timer. General-purpose and
basic timers (TIM2 … TIM17 as available) follow the same naming.
"""
TIM_CCR1: int
"""
Offset of the timer capture/compare register 1. TIM_CCR2 …
TIM_CCR4 follow on timers that have multiple channels.
"""
TIM_CR1: int
"""Offset of the timer control register 1."""
USART1: int
"""
Base address of the USART1 peripheral. Other USART / UART instances
are exposed under USART2, USART3, UART4 … as available.
"""
USART_CR1: int
"""Offset of the USART/UART control register 1."""
mem16: int
"""
Subscriptable 16-bit (halfword) memory accessor. mem16[addr] reads an
int in the range 0-65535; mem16[addr] = value writes the low 16
bits. addr must be aligned to 2 bytes.
"""
mem32: int
"""
Subscriptable 32-bit (word) memory accessor. mem32[addr] reads an
int in the range 0-0xFFFFFFFF; mem32[addr] = value writes the low
32 bits. addr must be aligned to 4 bytes.
"""
mem8: int
"""
Subscriptable 8-bit memory accessor. mem8[addr] reads an int in the
range 0-255 from the byte at addr; mem8[addr] = value writes the
low 8 bits of value. addr may be any byte-aligned address.
"""


def __getattr__(name: str) -> int:
    """
    Dynamic-attribute fallback: any CMSIS symbol exposed by the firmware that
    isn’t individually listed above (e.g. stm.FDCAN1, stm.OCTOSPI1,
    stm.GPIO_AFR, the various bit-field shifts and masks, …) still
    resolves to its absolute address or offset as an int.

    The runtime module populates these symbols directly into its globals dict
    at import time, so __getattr__ is never actually invoked. The signature
    is exposed solely so static type checkers (Pyright, Pylance, mypy)
    accept stm.<any CMSIS name> without a “module has no attribute”
    diagnostic.
    """
    ...
