# Auto-generated by tools/genpyi.py -- do not edit
r"""
This module implements “foreign data interface” for MicroPython. The idea
behind it is similar to CPython’s ctypes modules, but the actual API is
different, streamlined and optimized for small size. The basic idea of the
module is to define data structure layout with about the same power as the
C language allows, and then access it using familiar dot-syntax to reference
sub-fields.

Usage examples:

    import uctypes

    # Example 1: Subset of ELF file header
    # https://wikipedia.org/wiki/Executable_and_Linkable_Format#File_header
    ELF_HEADER = {
        "EI_MAG": (0x0 | uctypes.ARRAY, 4 | uctypes.UINT8),
        "EI_DATA": 0x5 | uctypes.UINT8,
        "e_machine": 0x12 | uctypes.UINT16,
    }

    # "f" is an ELF file opened in binary mode
    buf = f.read(uctypes.sizeof(ELF_HEADER, uctypes.LITTLE_ENDIAN))
    header = uctypes.struct(uctypes.addressof(buf), ELF_HEADER, uctypes.LITTLE_ENDIAN)
    assert header.EI_MAG == b"\x7fELF"
    assert header.EI_DATA == 1, "Oops, wrong endianness. Could retry with uctypes.BIG_ENDIAN."
    print("machine:", hex(header.e_machine))


    # Example 2: In-memory data structure, with pointers
    COORD = {
        "x": 0 | uctypes.FLOAT32,
        "y": 4 | uctypes.FLOAT32,
    }

    STRUCT1 = {
        "data1": 0 | uctypes.UINT8,
        "data2": 4 | uctypes.UINT32,
        "ptr": (8 | uctypes.PTR, COORD),
    }

    # Suppose you have address of a structure of type STRUCT1 in "addr"
    # uctypes.NATIVE is optional (used by default)
    struct1 = uctypes.struct(addr, STRUCT1, uctypes.NATIVE)
    print("x:", struct1.ptr[0].x)


    # Example 3: Access to CPU registers. Subset of STM32F4xx WWDG block
    WWDG_LAYOUT = {
        "WWDG_CR": (0, {
            # BFUINT32 here means size of the WWDG_CR register
            "WDGA": 7 << uctypes.BF_POS | 1 << uctypes.BF_LEN | uctypes.BFUINT32,
            "T": 0 << uctypes.BF_POS | 7 << uctypes.BF_LEN | uctypes.BFUINT32,
        }),
        "WWDG_CFR": (4, {
            "EWI": 9 << uctypes.BF_POS | 1 << uctypes.BF_LEN | uctypes.BFUINT32,
            "WDGTB": 7 << uctypes.BF_POS | 2 << uctypes.BF_LEN | uctypes.BFUINT32,
            "W": 0 << uctypes.BF_POS | 7 << uctypes.BF_LEN | uctypes.BFUINT32,
        }),
    }

    WWDG = uctypes.struct(0x40002c00, WWDG_LAYOUT)

    WWDG.WWDG_CFR.WDGTB = 0b10
    WWDG.WWDG_CR.WDGA = 1
    print("Current counter:", WWDG.WWDG_CR.T)
"""

from typing import Any

ARRAY: int
"""
Marks a descriptor field as a fixed-length array of another type.
An array field is either (offset | ARRAY, count | element_type)
for arrays of scalars or
(offset | ARRAY, count, element_descriptor) for arrays of
structures. The number of elements is fixed at descriptor time.
"""
BIG_ENDIAN: int
"""Layout type for a big-endian packed structure."""
FLOAT32: int
"""
IEEE 754 single-precision floating-point (4 bytes). Reads and writes
are converted to/from a Python float.
"""
FLOAT64: int
"""
IEEE 754 double-precision floating-point (8 bytes). Reads and writes
are converted to/from a Python float.
"""
INT16: int
"""Signed 16-bit integer. Range -32768 – 32767."""
INT32: int
"""Signed 32-bit integer. Range -0x80000000 – 0x7FFFFFFF."""
INT64: int
"""Signed 64-bit integer. Range -0x8000000000000000 – 0x7FFFFFFFFFFFFFFF."""
INT8: int
"""Signed 8-bit integer. Range -128 – 127."""
LITTLE_ENDIAN: int
"""
Layout type for a little-endian packed structure. (Packed means that every
field occupies exactly as many bytes as defined in the descriptor, i.e.
the alignment is 1).
"""
NATIVE: int
"""
Layout type for a native structure - with data endianness and alignment
conforming to the ABI of the system on which MicroPython runs.
"""
PTR: int
"""
Marks a descriptor field as a pointer to another type. A pointer
field is written as a two-tuple
(offset | PTR, target_type_or_descriptor). Dereferencing the
pointer yields a typed view into the address it holds.
"""
UINT16: int
"""Unsigned 16-bit integer. Range 0 – 65535."""
UINT32: int
"""Unsigned 32-bit integer. Range 0 – 0xFFFFFFFF."""
UINT64: int
"""Unsigned 64-bit integer. Range 0 – 0xFFFFFFFFFFFFFFFF."""
UINT8: int
"""Unsigned 8-bit integer. Range 0 – 255."""
VOID: int
"""
Alias for UINT8. Provided so that C-style void * fields
can be described idiomatically as (uctypes.PTR, uctypes.VOID).
"""


def addressof(obj: Any) -> int:
    """
    Return address of an object. Argument should be bytes, bytearray or
    other object supporting buffer protocol (and address of this buffer
    is what actually returned).
    """
    ...


def bytearray_at(addr: int, size: int) -> bytearray:
    """
    Capture memory at the given address and size as bytearray object.
    Unlike bytes_at() function above, memory is captured by reference,
    so it can be both written too, and you will access current value
    at the given memory address.
    """
    ...


def bytes_at(addr: int, size: int) -> bytes:
    """
    Capture memory at the given address and size as bytes object. As bytes
    object is immutable, memory is actually duplicated and copied into
    bytes object, so if memory contents change later, created object
    retains original value.
    """
    ...


def sizeof(struct: dict | Any, layout_type: int = NATIVE, /) -> int:
    """
    Return size of data structure in bytes. The struct argument can be
    either a structure class or a specific instantiated structure object
    (or its aggregate field).
    """
    ...


class struct:
    """
    Instantiate a “foreign data structure” object based on structure address in
    memory, descriptor (encoded as a dictionary), and layout type (see below).
    """
    def __init__(self, addr: int, descriptor: dict, layout_type: int = NATIVE, /) -> None: ...
