name: CI

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -U sphinx sphinx_rtd_theme sphinxcontrib.jquery

    - name: Build docs
      working-directory: micropython/docs
      run: python -m sphinx -b html -d build/doctrees . build/html

    - name: Generate Python stubs
      run: |
        python genpyi.py \
          --docs-dir micropython/docs/build/html/_sources/library/ \
          --pyi-dir micropython/docs/build/stubs

    - uses: actions/upload-artifact@v4
      with:
        name: html
        path: micropython/docs/build/html/

    - uses: actions/upload-artifact@v4
      with:
        name: stubs
        path: micropython/docs/build/stubs/

    - name: Sync built docs into repository
      run: |
        cp -r micropython/docs/build/html/* docs/
        rm -rf docs/stubs
        cp -r micropython/docs/build/stubs docs/stubs
        touch docs/.nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs
        git commit -m "Update documentation" -a || true
        # Commit fails if no changes; ignore.

    - name: Push documentation changes
      uses: ad-m/github-push-action@master
      with:
        branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Pushes to another repository
      if: startsWith(github.ref, 'refs/tags/v')
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: 'micropython/docs/build/html'
        destination-github-username: 'openmv'
        destination-repository-name: 'qt-creator'
        target-branch: openmv-qtc-14.0.2
        target-directory: 'share/qtcreator/html'
