# Auto-generated by tools/genpyi.py -- do not edit
from typing import Any, Optional, Union, Tuple, List

def fft(r: ndarray, c: ndarray | None = None) -> tuple[ndarray, ndarray]:
    """
    Compute the one-dimensional discrete Fourier Transform of r.
    Parameters

    r – a one-dimensional array whose length is a power of two. Holds the
    real part of the input signal.

    c – an optional one-dimensional array of the same length as r,
    containing the imaginary part of the input. If omitted, the
    imaginary part is assumed to be zero.

    Returns

    a 2-tuple (real, imag) of numpy.ndarray objects holding
    the real and imaginary parts of the transform.

    Raises

    ValueError – if the length of the input is not a power of two.
    When ulab is compiled with ULAB_SUPPORTS_COMPLEX and
    ULAB_FFT_IS_NUMPY_COMPATIBLE set to 1, the function instead takes a
    single (possibly complex) array and returns a complex array, in the same
    manner as numpy.fft.fft.
    """
    ...
def ifft(r: ndarray, c: ndarray | None = None) -> tuple[ndarray, ndarray]:
    """
    Compute the one-dimensional inverse discrete Fourier Transform.
    Parameters

    r – a one-dimensional array whose length is a power of two. Holds the
    real part of the spectrum.

    c – an optional one-dimensional array of the same length as r,
    containing the imaginary part of the spectrum. If omitted, the
    imaginary part is assumed to be zero.

    Returns

    a 2-tuple (real, imag) of numpy.ndarray objects
    holding the real and imaginary parts of the inverse transform.
    The result is normalised by N (the number of samples), so that
    ifft(fft(x)) reproduces the original input.

    Raises

    ValueError – if the length of the input is not a power of two.
    When ulab is compiled with ULAB_SUPPORTS_COMPLEX and
    ULAB_FFT_IS_NUMPY_COMPATIBLE set to 1, the function takes a single
    (possibly complex) array and returns a complex array.
    """
    ...

